//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MailboxContentViewCellLayoutValues.h"

@interface _DefaultMailboxContentViewCellLayoutValues : _MailboxContentViewCellLayoutValues
{
}

- (long long)dateAlignment;
- (long long)linesOfSummaryForCompact:(_Bool)arg1;
- (_Bool)isSubjectVisible;
- (double)defaultRowHeight;
- (double)compactRowHeight;
- (id)backgroundColorForSelectedState:(unsigned long long)arg1 disclosureEnabled:(_Bool)arg2;
- (id)subjectFont;
- (id)addressFont;
- (double)topPadding;

@end

