//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ConversationSource.h"

@interface _IncludeRelatedMessagesConversationSource : ConversationSource
{
}

- (_Bool)_shouldSearchAllMailForConversation;
- (id)_remoteConversationCriterion;
- (id)_localConversationCriterion;
- (id)excludingMailboxesCriterion;
- (id)excludedMailboxes;
- (id)allExcludedMailboxes;

@end

