//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor, UIFont;

@interface _MailboxContentViewCellLayoutValues : NSObject
{
    double _bottomMargin;
    double _leading;
    double _dateCapHeight;
    double _subjectCapHeight;
    double _summaryCapHeight;
    double _bottomPadding;
    double _topMargin;
    double _topPadding;
    double _addressCapHeight;
    UIFont *_addressFont;
    UIFont *_subjectFont;
    UIFont *_summaryFont;
    UIFont *_dateFont;
    UIFont *_mailboxFont;
    double _defaultRowHeight;
    double _compactRowHeight;
    UIColor *_subjectColor;
    UIColor *_summaryColor;
    _Bool _subjectVisible;
    long long _dateAlignment;
    struct CGPoint _recipientLabelCorrection;
}

+ (void)invalidateSharedInstances;
+ (id)sharedExpandedInstance;
+ (id)sharedTopHitsInstance;
+ (id)sharedDefaultInstance;
@property(nonatomic) double bottomMargin; // @synthesize bottomMargin=_bottomMargin;
@property(nonatomic) double topMargin; // @synthesize topMargin=_topMargin;
@property(readonly, nonatomic) long long dateAlignment; // @synthesize dateAlignment=_dateAlignment;
@property(readonly, nonatomic, getter=isSubjectVisible) _Bool subjectVisible; // @synthesize subjectVisible=_subjectVisible;
@property(readonly, nonatomic) struct CGPoint recipientLabelCorrection; // @synthesize recipientLabelCorrection=_recipientLabelCorrection;
@property(readonly, nonatomic) double topPadding; // @synthesize topPadding=_topPadding;
@property(readonly, nonatomic) double defaultRowHeight; // @synthesize defaultRowHeight=_defaultRowHeight;
@property(readonly, nonatomic) double compactRowHeight; // @synthesize compactRowHeight=_compactRowHeight;
@property(readonly, nonatomic) UIFont *subjectFont; // @synthesize subjectFont=_subjectFont;
@property(readonly, nonatomic) UIFont *addressFont; // @synthesize addressFont=_addressFont;
@property(readonly, nonatomic) UIFont *dateFont;
@property(readonly, nonatomic) UIFont *mailboxFont;
@property(readonly, nonatomic) UIFont *summaryFont;
- (long long)linesOfSummaryForCompact:(_Bool)arg1;
@property(readonly, nonatomic) double summaryCapHeight;
@property(readonly, nonatomic) double subjectCapHeight;
@property(readonly, nonatomic) double dateCapHeight;
@property(readonly, nonatomic) double leading;
@property(readonly, nonatomic) double bottomPadding;
@property(readonly, nonatomic) double addressCapHeight;
- (long long)subjectNumberOfLines;
- (double)addressAndSubjectHeight;
- (double)heightWithNumberOfSummaryLines:(long long)arg1;
@property(readonly, nonatomic) UIColor *summaryColor;
@property(readonly, nonatomic) UIColor *subjectColor;
- (id)backgroundColorForSelectedState:(unsigned long long)arg1 disclosureEnabled:(_Bool)arg2;
- (void)invalidate;
- (void)layoutMarginsDidChange:(struct UIEdgeInsets)arg1;
- (void)dealloc;

@end

