//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MessageSuggestionSession.h"

@class NSMutableSet;

@interface _MessageSuggestionSessionProxy : MessageSuggestionSession
{
    MessageSuggestionSession *_proxy;
    NSMutableSet *_callsToAction;
}

- (void)didIgnoreAction:(id)arg1;
- (void)didConfirmAction:(id)arg1;
- (id)contactForCallToAction:(id)arg1;
- (id)eventForCallToAction:(id)arg1;
- (void)setEvent:(id)arg1 forCallToAction:(id)arg2;
- (void)setContact:(id)arg1 forCallToAction:(id)arg2;
- (void)addCallsToAction:(id)arg1;
- (id)callsToAction;
- (id)eventStore;
- (id)initWithMessageSuggestionSession:(id)arg1;
- (void)dealloc;

@end

