//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFAttachment;

@interface _MFAttachmentInfo : NSObject
{
    _Bool _mailDrop;
    _Bool _image;
    MFAttachment *_attachment;
}

@property(nonatomic, getter=isImage) _Bool image; // @synthesize image=_image;
@property(nonatomic, getter=isMailDrop) _Bool mailDrop; // @synthesize mailDrop=_mailDrop;
@property(retain, nonatomic) MFAttachment *attachment; // @synthesize attachment=_attachment;
- (void)dealloc;

@end

