//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFSceneView.h"

@class UIView, _MFActorSnapshotView;

@interface _MFActorItemView : MFSceneView
{
    UIView *_dimmingView;
    _MFActorSnapshotView *_snapshotView;
    _Bool _hasTransparentBackground;
    UIView *_contentView;
    UIView *_backgroundView;
    struct UIEdgeInsets _contentInsets;
}

@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
@property(nonatomic) _Bool hasTransparentBackground; // @synthesize hasTransparentBackground=_hasTransparentBackground;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) _MFActorSnapshotView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(readonly, nonatomic) UIView *dimmingView; // @synthesize dimmingView=_dimmingView;
- (void)layoutHeaderView;
- (void)layoutSubviews;
- (void)updateCornerRadii;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

