//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MessageConsumer.h"

@class MFMessageStore, NSArray, NSMutableArray;

@interface _MFBatchedMessageConsumer : NSObject <MessageConsumer>
{
    NSMutableArray *_messagesAccumulator;
    unsigned long long _batchSize;
    MFMessageStore *_messageStore;
    CDUnknownBlockType _filter;
}

@property(copy, nonatomic) CDUnknownBlockType filter; // @synthesize filter=_filter;
@property(retain, nonatomic) MFMessageStore *messageStore; // @synthesize messageStore=_messageStore;
@property(nonatomic) unsigned long long batchSize; // @synthesize batchSize=_batchSize;
@property(retain, nonatomic) NSMutableArray *messagesAccumulator; // @synthesize messagesAccumulator=_messagesAccumulator;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *messages;
- (_Bool)shouldCancel;
- (void)newMessagesAvailable:(id)arg1;
- (id)initWithBatchSize:(unsigned long long)arg1 messageStore:(id)arg2 filter:(CDUnknownBlockType)arg3;

@end

