//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _MFConversationViewUpdateContext : NSObject
{
    struct CGPoint _contentOffsetAdjustment;
}

+ (id)contextWithContentOffsetAdjustment:(struct CGPoint)arg1;
@property(nonatomic) struct CGPoint contentOffsetAdjustment; // @synthesize contentOffsetAdjustment=_contentOffsetAdjustment;

@end

