//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

@interface _MFConversationViewCollectionView : UICollectionView
{
}

- (id)description;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (struct NSDirectionalEdgeInsets)updateLayoutMargins;
- (struct NSDirectionalEdgeInsets)_updateLayoutMarginsForFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) __weak id <_MFConversationViewCollectionViewDelegate> delegate; // @dynamic delegate;

@end

