//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewDelegate.h"

@protocol _MFConversationViewCollectionViewDelegate <UICollectionViewDelegate>
- (void)collectionViewMarginsDidChange:(struct NSDirectionalEdgeInsets)arg1;
- (struct NSDirectionalEdgeInsets)layoutMarginsForCollectionViewFrame:(struct CGRect)arg1;
@end

