//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIFont, UILabel;

@interface _MFExpandableCaptionViewDetailToggleButton : UIButton
{
    UILabel *_showDetailsLabel;
    UILabel *_hideDetailsLabel;
    _Bool _detailsVisible;
    UIFont *_font;
}

@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(nonatomic) _Bool detailsVisible; // @synthesize detailsVisible=_detailsVisible;
- (id)viewForFirstBaselineLayout;
- (id)viewForLastBaselineLayout;
- (struct CGSize)intrinsicContentSize;
- (void)setHighlighted:(_Bool)arg1;
- (void)setContentHorizontalAlignment:(long long)arg1;
- (void)setTitle:(id)arg1 forState:(unsigned long long)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

