//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMessageCollectionInfo, MessageMiniMall;

@interface _MFExpandedSection : NSObject
{
    MessageMiniMall *_mall;
    MFMessageCollectionInfo *_collectionInfo;
}

@property(retain, nonatomic) MFMessageCollectionInfo *collectionInfo; // @synthesize collectionInfo=_collectionInfo;
@property(retain, nonatomic) MessageMiniMall *mall; // @synthesize mall=_mall;
- (void)dealloc;

@end

