//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLocale, NSString;

@interface _MFFuzzyStringComparisonMatcherKey : NSObject
{
    NSString *_string;
    NSLocale *_locale;
    unsigned long long _options;
}

+ (id)matcherKeyWithString:(id)arg1 locale:(id)arg2 options:(unsigned long long)arg3;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithString:(id)arg1 locale:(id)arg2 options:(unsigned long long)arg3;
- (id)init;

@end

