//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMapTable;

@interface _MFMessageContentURLProtocolRegistry : NSObject
{
    NSLock *_lock;
    NSMapTable *_storage;
}

+ (id)sharedRegistry;
@property(readonly, nonatomic) NSMapTable *storage; // @synthesize storage=_storage;
- (id)loadingContextForURL:(id)arg1;
- (id)URLForLoadingContext:(id)arg1 scheme:(id)arg2;
- (id)init;
- (void)dealloc;

@end

