//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MFContainsSuggestion.h"

@class NSString;

@interface _MFPeopleContainsSuggestion : _MFContainsSuggestion
{
    NSString *_suggestionFormatString;
}

+ (_Bool)supportsSecureCoding;
@property(copy, nonatomic) NSString *suggestionFormatString; // @synthesize suggestionFormatString=_suggestionFormatString;
- (void).cxx_destruct;
- (id)category;
- (id)title;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

