//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class MFSearchScopedSuggestion, NSString;

@interface _MFSearchSuggestionAtom : NSObject <NSSecureCoding>
{
    MFSearchScopedSuggestion *_suggestion;
    NSString *_editingString;
}

+ (id)atomWithSuggestion:(id)arg1 editingString:(id)arg2;
+ (_Bool)supportsSecureCoding;
@property(readonly, copy, nonatomic) NSString *editingString; // @synthesize editingString=_editingString;
@property(readonly, nonatomic) MFSearchScopedSuggestion *suggestion; // @synthesize suggestion=_suggestion;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *displayName;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSuggestion:(id)arg1 editingString:(id)arg2;

@end

