//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MFAtomFieldEditor.h"

@class MFAtomSearchBar, _MFSearchAtomTextView;

@interface _MFSearchAtomFieldEditor : _MFAtomFieldEditor
{
    id <_MFSearchAtomViewTappedStateProtocol> _searchAtomViewTapStateDelegate;
}

@property(nonatomic) __weak id <_MFSearchAtomViewTappedStateProtocol> searchAtomViewTapStateDelegate; // @synthesize searchAtomViewTapStateDelegate=_searchAtomViewTapStateDelegate;
- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (double)_baselineOffsetFromBottom;
- (double)_firstBaselineOffsetFromTop;
- (_Bool)canBecomeFirstResponder;
@property(readonly, nonatomic, getter=_searchBar) MFAtomSearchBar *searchBar;
@property(readonly, nonatomic, getter=_hostView) _MFSearchAtomTextView *hostView;

@end

