//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class MFSearchSuggestionPhraseManager, MFSearchSuggestionsGenerator, NSArray, NSNumber, NSProgress;

@interface _MFSearchSuggestionsOperation : NSOperation
{
    NSNumber *_identifier;
    MFSearchSuggestionPhraseManager *_phraseManager;
    NSArray *_suggesters;
    MFSearchSuggestionsGenerator *_suggestionsGenerator;
    NSProgress *_progress;
}

+ (id)suggestionsOperationWithPhraseManager:(id)arg1 suggestionsGenerator:(id)arg2 identifier:(id)arg3;
- (void).cxx_destruct;
- (void)main;
- (void)cancel;
- (id)initWithPhraseManager:(id)arg1 suggestionsGenerator:(id)arg2 identifier:(id)arg3;

@end

