//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFAtomTextView.h"

#import "_MFSearchAtomViewTappedStateProtocol.h"
#import "_UISearchBarTextFieldOrMailReplacement.h"

@class MFAtomSearchBar, NSString, _MFAtomSearchBarFieldEditorBackgroundView, _MFSearchAtomFieldEditor;

@interface _MFSearchAtomTextView : MFAtomTextView <_UISearchBarTextFieldOrMailReplacement, _MFSearchAtomViewTappedStateProtocol>
{
    _MFAtomSearchBarFieldEditorBackgroundView *_effectBackgroundBottom;
    _MFAtomSearchBarFieldEditorBackgroundView *_effectBackgroundTop;
    _Bool _tapped;
}

+ (Class)_backgroundViewClass;
+ (Class)_fieldEditorClass;
@property(nonatomic, getter=isTapped) _Bool tapped; // @synthesize tapped=_tapped;
- (void).cxx_destruct;
- (void)_setBackgroundViewsAlpha:(double)arg1;
- (void)_setForegroundViewsAlpha:(double)arg1;
- (void)_setAnimatesBackgroundCornerRadius:(_Bool)arg1;
- (void)setText:(id)arg1;
- (id)searchText;
- (void)updateForBackdropStyle:(unsigned long long)arg1;
- (id)_createEffectsBackgroundViewWithStyle:(unsigned long long)arg1 applyFilter:(id)arg2;
- (void)_updateBackgroundView:(id)arg1 withStyle:(unsigned long long)arg2 filter:(id)arg3;
- (void)_setEnabled:(_Bool)arg1 animated:(_Bool)arg2;
- (id)textInputTraits;
@property(readonly, nonatomic, getter=_fieldEditor) _MFSearchAtomFieldEditor *fieldEditor;
@property(readonly, nonatomic, getter=_searchBar) MFAtomSearchBar *searchBar;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

