//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface _MFVelocityIntegratorDataPoint : NSObject
{
    NSDate *_timestamp;
    struct CGVector _translation;
    struct CGPoint _point;
}

+ (id)sampleWithPoint:(struct CGPoint)arg1 previousSample:(id)arg2;
@property(nonatomic) struct CGPoint point; // @synthesize point=_point;
@property(nonatomic) struct CGVector translation; // @synthesize translation=_translation;
@property(copy, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
- (void)resetTimestamp;
- (_Bool)isSampleDistinctFromTouchLocation:(struct CGPoint)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithPoint:(struct CGPoint)arg1 previousSample:(id)arg2;
- (id)init;

@end

