//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AutoFetchController.h"
#import "MFDiagnosticsGenerator.h"

@class NSArray, NSMutableDictionary, NSString, NSTimer;

@interface AutoFetchController : NSObject <MFDiagnosticsGenerator, AutoFetchController>
{
    id <AutoFetchControllerDataSource> _dataSource;
    double _lastNonvisibleAutoFetchDate;
    NSMutableDictionary *_accountResponsiveness;
    unsigned long long _outstandingAccountChangeFetchRequests;
    int _autoFetchState;
    int _fetchType;
    int _pendingFetchType;
    _Bool _lastAutoFetchHadErrors;
    _Bool _lastAutoFetchHadSources;
    NSArray *_fetchAccounts;
    NSArray *_pendingFetchAccounts;
    NSArray *_visibleSources;
    NSArray *_visibleSourceJobInvocations;
    unsigned long long _outstandingAutoFetchRequests;
    NSTimer *_networkWakeupTimeout;
    unsigned int _isReachable:1;
    unsigned int _monitoringReachability:1;
    unsigned int _tryFetchWhenReachable:1;
    id <MFAccountsProvider> _accountsProvider;
    NSArray *_jobList;
}

+ (id)sharedController;
@property(retain, nonatomic) NSArray *jobList; // @synthesize jobList=_jobList;
@property(retain, nonatomic) id <MFAccountsProvider> accountsProvider; // @synthesize accountsProvider=_accountsProvider;
- (id)copyDiagnosticInformation;
- (void)_finishAutoFetch;
- (void)_createJobListFinished:(id)arg1;
- (void)_scheduleAllJobs;
- (void)_createJobList;
- (void)_reportSynchronousFetchCompletion:(id)arg1;
- (void)_checkForWiFi;
- (_Bool)_shouldAutoFetchAccount:(id)arg1 whenVisible:(_Bool)arg2;
- (void)_checkForReachability;
- (oneway void)_reportReachabilityTimeout:(id)arg1;
- (void)_reportReachabilityChange:(id)arg1;
- (void)_cleanUpReachabilityTimer;
- (void)_startAutoFetch:(int)arg1 withAccounts:(id)arg2;
- (void)_accountChangedFinished;
- (void)_fetchCompleted:(id)arg1;
- (void)_accountContentsDidChange:(id)arg1;
- (void)_fetchChangedUids:(id)arg1 forAccount:(id)arg2;
- (void)_fetchChangedUids:(id)arg1 forAccount:(id)arg2 options:(int)arg3;
- (void)_doFetchChangedUids:(id)arg1 forAccount:(id)arg2 options:(int)arg3;
- (void)_scheduleRequest:(id)arg1 priority:(int)arg2 selector:(SEL)arg3;
- (void)_scheduleRetryRequest:(id)arg1 priority:(int)arg2 selector:(SEL)arg3;
- (id)_invocationWithTarget:(id)arg1 priority:(int)arg2;
@property(nonatomic) int autoFetchState;
- (oneway void)networkConfigurationChanged;
- (oneway void)stopAutoFetch;
- (oneway void)startAutoFetch;
- (void)fetchNowWithType:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (oneway void)fetchNow:(int)arg1 withMailboxes:(id)arg2;
- (oneway void)fetchNow:(int)arg1 withSources:(id)arg2;
- (oneway void)fetchNow:(int)arg1 withAccounts:(id)arg2;
- (oneway void)fetchNow:(int)arg1;
- (_Bool)_tryFetch:(int)arg1 withAccounts:(id)arg2;
- (_Bool)_tryFetch:(int)arg1;
- (_Bool)isIdle;
- (void)_freeSpaceStatusDidChange:(id)arg1;
- (oneway void)setDataSource:(id)arg1;
- (id)freeSpaceMonitor;
- (void)dealloc;
- (id)initWithAccountsProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

