//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CNContactProperty, CNUnknownContactsController;

@protocol CNUnknownContactsControllerDelegate <NSObject>

@optional
- (void)unknownContactsControllerDidComplete:(CNUnknownContactsController *)arg1;
- (_Bool)unknownContactsController:(CNUnknownContactsController *)arg1 shouldPerformDefaultActionForContactProperty:(CNContactProperty *)arg2;
@end

