//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LibrarySearchSource.h"

@class MFLibraryMessage;

@interface ConversationSource : LibrarySearchSource
{
    MFLibraryMessage *_referenceMessage;
}

+ (id)conversationSourceForLibrary:(id)arg1 includeRelatedMessages:(_Bool)arg2 referenceMessage:(id)arg3 primarySources:(id)arg4;
@property(retain, nonatomic) MFLibraryMessage *referenceMessage; // @synthesize referenceMessage=_referenceMessage;
- (id)_missingReferencesCriterion;
- (_Bool)shouldThreadConversations;
- (id)_fetchRemoteMessages;
- (void)_fetchLocalMessages;
- (id)effectiveCriterion;
- (long long)fetchNumOlderMessages:(unsigned long long)arg1 preservingUID:(id)arg2;
- (_Bool)canLoadOlderMessages;
- (_Bool)_shouldSearchAllMailForConversation;
- (id)_remoteConversationCriterion;
- (id)_localConversationCriterion;
- (void)dealloc;
- (id)initWithLibrary:(id)arg1 primarySources:(id)arg2 referenceMessage:(id)arg3;

@end

