//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMessageCriterion, NSArray, NSString;

@interface FavoriteItem : NSObject
{
    NSString *_syncKey;
    unsigned long long _type;
    _Bool _selected;
    _Bool _shouldSync;
    _Bool _expanded;
    MFMessageCriterion *_criterion;
    NSArray *_subItems;
}

+ (id)itemFromDictionary:(id)arg1;
+ (_Bool)_defaultShouldExpand;
+ (_Bool)_defaultShouldSync;
+ (id)itemForOutbox;
+ (id)itemForSharedMailboxWithType:(unsigned long long)arg1 selected:(_Bool)arg2;
+ (id)itemForUnifiedMailboxWithType:(int)arg1 selected:(_Bool)arg2;
+ (id)itemForInboxWithAccount:(id)arg1 selected:(_Bool)arg2;
+ (id)itemForMailbox:(id)arg1 selected:(_Bool)arg2 shouldSync:(_Bool)arg3;
+ (id)itemForMailbox:(id)arg1 selected:(_Bool)arg2;
+ (id)itemForAccount:(id)arg1;
@property(copy, nonatomic) NSArray *subItems; // @synthesize subItems=_subItems;
@property(nonatomic, getter=isExpanded) _Bool expanded; // @synthesize expanded=_expanded;
@property(nonatomic) _Bool shouldSync; // @synthesize shouldSync=_shouldSync;
@property(readonly, nonatomic) MFMessageCriterion *criterion; // @synthesize criterion=_criterion;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, nonatomic) unsigned long long sourceType;
- (id)description;
@property(readonly, nonatomic, getter=isExpandableInEditMode) _Bool expandableInEditMode;
@property(readonly, nonatomic, getter=isExpandable) _Bool expandable;
- (id)persistentIdForMigration;
- (void)wasChangedExternally;
- (void)wasRemovedFromCollecion:(id)arg1;
- (void)wasAddedToCollection:(id)arg1;
- (id)syncValue;
- (id)syncKey;
- (void)configureCell:(id)arg1;
@property(readonly, nonatomic) _Bool acceptsMessageTransfers;
- (id)representingMailboxes;
- (id)representingMailbox;
- (id)account;
- (void)wasSelected:(id)arg1 indexPath:(id)arg2 accessoryTapped:(_Bool)arg3;
- (id)badgeCountString;
- (id)applicationShortcutIcon;
- (struct CGPoint)iconOffset;
- (id)iconTintColor;
- (id)defaultIcon;
- (long long)_defaultCellAccessoryType;
- (_Bool)isSelected;
- (void)setSelected:(_Bool)arg1;
- (_Bool)isDeletable;
- (_Bool)isMovable;
- (_Bool)isVisible;
- (id)displayName;
- (id)dictionaryRepresentation;
- (void)dealloc;
- (id)initWithDictionary:(id)arg1;
- (id)initWithType:(unsigned long long)arg1;

@end

