//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FavoriteItem, MFMailboxUid, MailAccount, NSIndexPath;

@protocol FavoriteItemSelectionTarget <NSObject>
- (void)showVIPSettingsAnimated:(_Bool)arg1;
- (void)selectCombinedInboxWithSourceType:(unsigned long long)arg1 item:(FavoriteItem *)arg2 animated:(_Bool)arg3;
- (void)selectCombinedMailboxWithType:(int)arg1 item:(FavoriteItem *)arg2 animated:(_Bool)arg3;
- (void)selectMailbox:(MFMailboxUid *)arg1 item:(FavoriteItem *)arg2 andPopToMailboxController:(_Bool)arg3 animated:(_Bool)arg4;
- (void)selectMailbox:(MFMailboxUid *)arg1 item:(FavoriteItem *)arg2 animated:(_Bool)arg3;
- (void)selectAccount:(MailAccount *)arg1 item:(FavoriteItem *)arg2 indexPath:(NSIndexPath *)arg3 animated:(_Bool)arg4;
@end

