//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MailboxUtilsClient.h"

@class FavoriteItem, NSMutableArray, NSRecursiveLock, NSString, NSUbiquitousKeyValueStore;

@interface FavoritesManager : NSObject <MailboxUtilsClient>
{
    NSString *_storagePath;
    NSMutableArray *_mailboxCollections;
    NSRecursiveLock *_lock;
    NSUbiquitousKeyValueStore *_kvStore;
    _Bool _showingOutbox;
    _Bool _showingSingleAccount;
    _Bool _loadingMailboxes;
    NSMutableArray *_visibleMailboxCollections;
    FavoriteItem *_lastSelectedItem;
}

+ (void)performTransaction:(CDUnknownBlockType)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) FavoriteItem *lastSelectedItem; // @synthesize lastSelectedItem=_lastSelectedItem;
- (void)_keyValueStoreChangedExternally:(id)arg1;
- (void)_updateOutboxStatus:(id)arg1;
- (void)_mailboxNameChanged:(id)arg1;
- (void)_mailboxListingChanged:(id)arg1;
- (void)_processNewMailboxes:(id)arg1;
- (void)_processOrphanedMailboxes:(id)arg1;
- (void)_watchedMailboxesChanged:(id)arg1;
- (void)_sharedMailboxControllerBadgeCountDidChange:(id)arg1;
- (void)_accountsDidChange:(id)arg1;
- (void)_loadMailboxesAfterMailboxListingChanged;
- (void)_loadMailboxes:(_Bool)arg1;
- (void)_loadMailboxesForcibly:(id)arg1;
- (_Bool)shouldHideNotesForAccount:(id)arg1;
- (_Bool)shouldHideInbox;
- (void)shouldReloadMailboxesWithOutbox:(id)arg1;
- (void)_mergeExternalChanges:(unsigned long long)arg1 changedKeys:(id)arg2;
- (void)syncLocalChanges:(id)arg1 removed:(id)arg2;
- (void)_syncLocalChanges_nts:(id)arg1 removed:(id)arg2;
- (id)_copyKVValueForItem:(id)arg1;
- (void)_postNotification;
- (void)_postNotificationChangedItems:(id)arg1;
- (id)indexPathForItem:(id)arg1;
- (id)_indexPathForSharedMailboxControllerOfSourceType:(unsigned long long)arg1;
- (void)_writeLocalData;
- (id)copyMailboxSources;
- (void)refreshCollectionForItemExpansion:(id)arg1;
- (_Bool)updateCollections:(id)arg1 withItems:(id)arg2;
- (void)moveItemOfCollection:(id)arg1 fromIndex:(long long)arg2 toIndex:(long long)arg3;
- (void)_invalidateVisibleMailboxCollections;
- (id)visibleMailboxUids;
- (id)orderedFavoriteMailboxesForAccount:(id)arg1 includeUnifiedMailboxes:(_Bool)arg2;
- (id)favoriteMailboxesForAccount:(id)arg1;
- (id)visibleItemsOfType:(unsigned long long)arg1;
- (id)itemsOfType:(unsigned long long)arg1;
- (id)accountsCollection;
- (id)mailboxesCollection;
- (id)visibleMailboxCollections;
- (id)collectionContainingItem:(id)arg1;
- (void)removeItemAtIndexPath:(id)arg1;
- (id)itemAtIndexPath:(id)arg1;
- (_Bool)_addSharedMailboxItems;
- (void)_createDefaultCollections;
- (void)_migrateItemOrder;
- (void)_reload;
- (void)_reloadAccountMailboxItems;
- (void)dealloc;
- (id)init;

@end

