//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SearchOperation.h"

@class NSMutableDictionary, NSProgress, NSSet;

@interface FullSearchOperation : SearchOperation
{
    NSProgress *_progress;
    struct os_unfair_lock_s _accountsLock;
    NSSet *_accounts;
    struct os_unfair_lock_s _remoteSearchCoordinatorsByAccountIdentifierLock;
    NSMutableDictionary *_remoteSearchCoordinatorsByAccountIdentifier;
}

+ (id)fullSearchForManager:(id)arg1 searchContext:(id)arg2 sources:(id)arg3 library:(id)arg4;
- (void).cxx_destruct;
- (id)_orderedMailboxesForAccount:(id)arg1;
- (id)_orderedEnumeratorForSources:(id)arg1 withAccount:(id)arg2;
- (void)_performRemoteSearchForAccount:(id)arg1 coordinator:(id)arg2;
- (id)_performRemoteSearchesForAccount:(id)arg1;
- (id)_performRemoteSearchesWithSources:(id)arg1 accountID:(id)arg2;
- (void)performRemoteSearches;
- (void)performLocalSearch;
- (id)_remoteSearchableSourcesByAccount;
- (void)accountsChanged:(id)arg1;
- (void)updateWithAccounts:(id)arg1;
- (id)accounts;
- (void)main;
- (void)cancel;
- (id)progress;
- (_Bool)_shouldPerformRemoteSearch;
- (_Bool)_shouldPerformLocalSearch;
- (id)initWithManager:(id)arg1 library:(id)arg2 sources:(id)arg3 searchContext:(id)arg4;

@end

