//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListItemsController.h"

@interface IndividualSwipeOptionController : PSListItemsController
{
    _Bool _showArchiveFooter;
}

- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (_Bool)_canSelectOptionAtIndex:(unsigned long long)arg1;
- (id)itemsFromParent;
- (void)listItemSelected:(id)arg1;
- (void)viewDidLoad;

@end

