//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SearchOperation.h"

@class NSProgress;

@interface LocalSearchOperation : SearchOperation
{
    NSProgress *_progress;
}

+ (id)localSearchForManager:(id)arg1 searchContext:(id)arg2 sources:(id)arg3 library:(id)arg4;
- (void).cxx_destruct;
- (void)performLocalSearch;
- (void)main;
- (id)progress;
- (id)initWithManager:(id)arg1 library:(id)arg2 sources:(id)arg3 searchContext:(id)arg4;

@end

