//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "EditFavoritesControllerDelegate.h"
#import "FavoriteItemSelectionTarget.h"
#import "MailStatusBarDelegate.h"
#import "MailboxEditingControllerDelegate.h"
#import "UITableViewDropDelegate_Private.h"

@class MailboxContentViewController, NSArray, NSMutableDictionary, NSString, UIBarButtonItem, UIMultiColumnViewController;

@interface MailboxPickerController : UITableViewController <UITableViewDropDelegate_Private, EditFavoritesControllerDelegate, FavoriteItemSelectionTarget, MailboxEditingControllerDelegate, MailStatusBarDelegate>
{
    struct CGPoint _savedContentOffset;
    NSMutableDictionary *_headerViews;
    NSArray *_watchedMailboxes;
    NSArray *_defaultToolbarItems;
    NSArray *_editingToolbarItems;
    UIBarButtonItem *_composeButton;
    _Bool _viewIsVisible;
    _Bool _isRefreshing;
    _Bool _observingFavoritesManagerChanges;
    _Bool _showingVIPSettings;
    _Bool _showingFavoritesEditor;
    _Bool _showingAddButton;
    _Bool _nextTableViewUpdateRequiresReload;
    UIMultiColumnViewController *_multiColumnViewController;
    unsigned long long _numVisibleColumns;
    MailboxContentViewController *_mailboxContentViewController;
    id <MFAccountsProvider> _accountsProvider;
}

@property(retain, nonatomic) id <MFAccountsProvider> accountsProvider; // @synthesize accountsProvider=_accountsProvider;
@property(nonatomic) _Bool nextTableViewUpdateRequiresReload; // @synthesize nextTableViewUpdateRequiresReload=_nextTableViewUpdateRequiresReload;
@property(retain, nonatomic) MailboxContentViewController *mailboxContentViewController; // @synthesize mailboxContentViewController=_mailboxContentViewController;
@property(nonatomic) _Bool showingAddButton; // @synthesize showingAddButton=_showingAddButton;
@property(nonatomic) _Bool showingFavoritesEditor; // @synthesize showingFavoritesEditor=_showingFavoritesEditor;
@property(nonatomic) _Bool showingVIPSettings; // @synthesize showingVIPSettings=_showingVIPSettings;
@property(nonatomic) unsigned long long numVisibleColumns; // @synthesize numVisibleColumns=_numVisibleColumns;
@property(nonatomic) UIMultiColumnViewController *multiColumnViewController; // @synthesize multiColumnViewController=_multiColumnViewController;
- (id)badgeCount;
- (_Bool)shouldShowSubtitle;
- (id)mailboxQualifier;
- (long long)_tableView:(id)arg1 dataOwnerForDropSession:(id)arg2 withDestinationIndexPath:(id)arg3;
- (id)tableView:(id)arg1 dropSessionDidUpdate:(id)arg2 withDestinationIndexPath:(id)arg3;
- (void)tableView:(id)arg1 performDropWithCoordinator:(id)arg2;
- (void)tableView:(id)arg1 dropSessionDidExit:(id)arg2;
- (void)tableView:(id)arg1 dropSessionDidEnter:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldSpringLoadRowAtIndexPath:(id)arg2 withContext:(id)arg3;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willDeselectRowAtIndexPath:(id)arg2;
- (_Bool)selectFavoriteItemAtIndexPath:(id)arg1 animated:(_Bool)arg2;
- (_Bool)selectFavoriteItem:(id)arg1 animated:(_Bool)arg2;
- (_Bool)_selectFavoriteItem:(id)arg1 indexPath:(id)arg2 animated:(_Bool)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)_configureAccountsCell:(id)arg1 forItem:(id)arg2;
- (void)_configureFlattenedCell:(id)arg1 forItem:(id)arg2;
- (void)_configureMailboxCell:(id)arg1 indexPath:(id)arg2 mailbox:(id)arg3;
- (id)_cellForAddButtonInTableView:(id)arg1 atIndexPath:(id)arg2;
- (void)_configureTableCell:(id)arg1 indexPath:(id)arg2 item:(id)arg3 collection:(id)arg4;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)_detailsDisclosureButtonTapped:(id)arg1;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (_Bool)isCellSelectable:(id)arg1 atIndexPath:(id)arg2;
- (_Bool)_isAddButton:(id)arg1 indexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldDrawTopSeparatorForSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)_updateCheckmarkColor:(id)arg1;
- (void)_updatedSelectedState:(id)arg1;
- (void)_reloadRowsAtIndexPaths:(id)arg1;
- (void)_reloadTableViewData;
- (void)editFavoritesControllerDidFinish:(id)arg1;
- (void)showVIPSettingsAnimated:(_Bool)arg1;
- (void)selectCombinedInboxWithSourceType:(unsigned long long)arg1 item:(id)arg2 animated:(_Bool)arg3;
- (void)replaceMailboxContentWithViewController:(id)arg1 deselectMailboxRow:(_Bool)arg2 animated:(_Bool)arg3;
- (void)_popToMailboxPickerController:(_Bool)arg1 andPushMailboxContentViewControllerIfNecessaryAnimated:(_Bool)arg2;
- (void)_useMultiColumnViewControllerToShowViewController:(id)arg1 animated:(_Bool)arg2;
- (void)selectCombinedMailboxWithType:(int)arg1 item:(id)arg2 animated:(_Bool)arg3;
- (void)selectMailbox:(id)arg1 item:(id)arg2 animated:(_Bool)arg3;
- (void)selectMailbox:(id)arg1 item:(id)arg2 andPopToMailboxController:(_Bool)arg3 animated:(_Bool)arg4;
- (void)_presentMailboxEditControllerForAccount:(id)arg1 mailbox:(id)arg2 animated:(_Bool)arg3;
- (void)_presentViewControllerOverCurrentContext:(id)arg1 animated:(_Bool)arg2;
- (void)selectAccount:(id)arg1 item:(id)arg2 indexPath:(id)arg3 animated:(_Bool)arg4;
- (void)_detailViewControllerConfigurationChanged:(id)arg1;
- (_Bool)shouldAutorotate;
- (void)_updateMailboxSelectionAnimated:(_Bool)arg1;
- (void)_applicationDidBecomeActive:(id)arg1;
- (void)_collectionDidInvalidateVisibleItems:(id)arg1;
- (void)_watchedMailboxesDidChange:(id)arg1;
- (void)_significantTimeChange:(id)arg1;
- (void)_flagStyleDidChange:(id)arg1;
- (void)_contentSizeCategoryChanged:(id)arg1;
- (void)_vipSendersDidChange:(id)arg1;
- (void)_sharedMailboxControllerBadgeCountDidChange:(id)arg1;
- (void)_updateCellForSourceType:(id)arg1;
- (void)_favoritesDidChange:(id)arg1;
- (void)_accountsDidChange:(id)arg1;
@property(readonly, retain, nonatomic) MailboxContentViewController *topMailboxContentViewController;
- (id)watchedMailboxes;
- (void)dismissAndUnfocus;
- (void)mailboxEditingControllerDidFinish:(id)arg1;
- (void)newMailboxClicked:(id)arg1;
- (void)_addFavoriteButtonClicked;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (struct NSDirectionalEdgeInsets)mf_extraContentMargins;
- (void)_updateToolbarItems:(_Bool)arg1;
- (void)_setBackButtonTitle:(id)arg1;
- (void)prepareToContinueDisplayingMessage;
- (void)_updateSharedMailboxesExposure:(int)arg1;
- (int)propagateChangeDownwards:(id)arg1;
- (void)_getRotationContentSettings:(CDStruct_e950349b *)arg1;
- (void)applicationWillSuspend;
- (void)viewDidUnload;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)_removeFavoritesManagerObservations;
- (void)_addFavoritesManagerObservations;
- (void)_refreshMailboxList;
- (void)pulledToRefresh:(id)arg1;
- (void)statusBarProgressDidChange:(id)arg1;
- (void)updateIsRefreshing;
@property(nonatomic) _Bool isRefreshing;
- (id)selectedAccounts;
- (_Bool)containsMultipleAccounts;
- (void)_registerNotifications;
- (void)dealloc;
- (id)initWithAccountsProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

