//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, UITextView;

@interface MailboxPredictorDebugViewController : UIViewController
{
    NSString *_algorithm;
    NSString *_result;
    NSString *_output;
    CDUnknownBlockType _dismissBlock;
    UITextView *_outputTextView;
}

@property(retain) UITextView *outputTextView; // @synthesize outputTextView=_outputTextView;
@property(copy) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(copy) NSString *output; // @synthesize output=_output;
@property(copy) NSString *result; // @synthesize result=_result;
@property(copy) NSString *algorithm; // @synthesize algorithm=_algorithm;
- (void).cxx_destruct;
- (void)_dismiss;
- (void)selectAll:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)viewDidLoad;
- (id)initWithAlgoritm:(id)arg1 result:(id)arg2 output:(id)arg3 dismiss:(CDUnknownBlockType)arg4;

@end

