//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "MailboxUtilsClient.h"

@class MFMailboxUid, MailAccount, NSArray;

@interface MailboxListViewControllerBase : UITableViewController <MailboxUtilsClient>
{
    unsigned int _loadingMailboxes:1;
    _Bool _preventNextScrollbarFlash;
    _Bool _promoteFavorites;
    _Bool _interactiveTransitionWasCancelled;
    MailAccount *_account;
    MFMailboxUid *_selectedMailbox;
    NSArray *_sortedMailboxes;
    id _mailboxSelectionTarget;
}

+ (long long)tableViewStyle;
@property(nonatomic) __weak id mailboxSelectionTarget; // @synthesize mailboxSelectionTarget=_mailboxSelectionTarget;
@property(retain, nonatomic) NSArray *sortedMailboxes; // @synthesize sortedMailboxes=_sortedMailboxes;
@property(retain, nonatomic) MFMailboxUid *selectedMailbox; // @synthesize selectedMailbox=_selectedMailbox;
@property(retain, nonatomic) MailAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)indexPathForSelection;
- (_Bool)shouldHideNotesForAccount:(id)arg1;
- (_Bool)shouldHideInbox;
- (void)shouldReloadMailboxesWithOutbox:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)mailboxListingChanged:(id)arg1;
- (void)_loadMailboxesAfterMailboxListingChanged;
- (void)_popToMailboxListViewController;
- (void)_loadMailboxes:(_Bool)arg1;
- (void)_loadExtraMailboxes;
- (void)_loadMailboxesForcibly:(id)arg1;
- (void)_loadMailboxes;
- (id)_ntsMailboxesForAccount:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)didSelectMailbox:(id)arg1 changed:(_Bool)arg2 animated:(_Bool)arg3;
- (void)setSelectedMailbox:(id)arg1 forceChange:(_Bool)arg2 animated:(_Bool)arg3;
- (void)setSelectedMailbox:(id)arg1 animated:(_Bool)arg2;
- (void)viewWillReappear:(_Bool)arg1;
- (void)viewWillFirstAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setViewingContext:(id)arg1;
- (void)viewDidLoad;
- (double)_defaultRowHeight;
- (void)viewDidAppear:(_Bool)arg1;
- (void)preventNextScrollbarFlash;
- (id)indexPathForMailbox:(id)arg1;
- (id)mailboxForIndexPath:(id)arg1;
- (void)dealloc;
- (id)init;

@end

