//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface MailErrorHandler : NSObject
{
    NSMutableSet *_displayedErrorDescriptions;
    NSMutableSet *_sslErrorAccountsDisplayed;
}

- (id)_alertTitleWithError:(id)arg1;
- (void)_presentAlertWithSettingsButtonForAccount:(id)arg1 error:(id)arg2;
- (void)_promptUserToTryAlternateSettingsFromAccountHealer:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_promptUserForPasswordWithAccount:(id)arg1 error:(id)arg2;
- (void)_promptUserForWebLoginWithAccount:(id)arg1 error:(id)arg2;
- (void)_changeSetManagerEncounteredError:(id)arg1;
- (void)_redirectToRecoveryURL:(id)arg1;
- (void)displayError:(id)arg1 forAccount:(id)arg2 mode:(int)arg3;
- (void)_displayError:(id)arg1 forAccount:(id)arg2 mode:(int)arg3;
- (id)preferencesURLForAccount:(id)arg1 error:(id)arg2;
- (id)sanitizedErrorForError:(id)arg1 forAccount:(id)arg2;
- (void)didDisplayError:(id)arg1;
- (_Bool)shouldDisplayError:(id)arg1 forAccount:(id)arg2 mode:(int)arg3;
- (void)reset;
- (void)dealloc;
- (id)init;

@end

