//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class MFTaskAssertion, NSDictionary, NSString;

@interface MailPersistentStorageSaveOperation : NSOperation
{
    NSDictionary *_groupDictionary;
    NSString *_destinationPath;
    id <MFCancelable> _finishedObservation;
    MFTaskAssertion *_taskAssertion;
}

@property(retain, nonatomic) MFTaskAssertion *taskAssertion; // @synthesize taskAssertion=_taskAssertion;
@property(retain, nonatomic) id <MFCancelable> finishedObservation; // @synthesize finishedObservation=_finishedObservation;
@property(copy, nonatomic) NSString *destinationPath; // @synthesize destinationPath=_destinationPath;
@property(copy, nonatomic) NSDictionary *groupDictionary; // @synthesize groupDictionary=_groupDictionary;
- (void)main;
- (id)initWithDestinationPath:(id)arg1 groupDictionary:(id)arg2;
- (void)dealloc;

@end

