//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MailAccount.h"

@interface MailAccount (NanoMail)
+ (id)nano_bridgeSettingsInboxesFromAccounts:(id)arg1;
+ (id)nano_activeMailAccounts;
- (id)nano_account;
@end

