//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISplitViewController.h"

#import "MFApplicationSceneActor.h"
#import "UIGestureRecognizerDelegate.h"
#import "UISplitViewControllerDelegate.h"
#import "UISplitViewControllerDelegatePrivate.h"

@class MailDetailNavigationController, MailNavigationController, NSMutableArray, NSString, UIImage, UIMultiColumnViewController, UIPanGestureRecognizer, UITapGestureRecognizer;

@interface MailSplitViewController : UISplitViewController <UISplitViewControllerDelegate, UISplitViewControllerDelegatePrivate, UIGestureRecognizerDelegate, MFApplicationSceneActor>
{
    UIPanGestureRecognizer *_overlaySwipeRecognizer;
    UITapGestureRecognizer *_overlayTapRecognizer;
    unsigned long long _lastGestureRecognized;
    double _panHysteresisHorizontalLocation;
    NSMutableArray *_detailDimmingViews;
    _Bool _detailDimmed;
    _Bool _isInEditMode;
    _Bool _overlayGesturesEnabled;
    _Bool _primaryAlwaysVisible;
    _Bool _primaryHasFocus;
    MailNavigationController *_messageListNavController;
    MailDetailNavigationController *_messageDetailNavController;
    UIMultiColumnViewController *_multiColumnController;
    unsigned long long _numVisibleColumns;
    UIImage *_mailDisplayModeButtonImage;
    NSString *_mailDisplayModeButtonTitle;
}

@property(nonatomic) _Bool primaryHasFocus; // @synthesize primaryHasFocus=_primaryHasFocus;
@property(copy, nonatomic) NSString *mailDisplayModeButtonTitle; // @synthesize mailDisplayModeButtonTitle=_mailDisplayModeButtonTitle;
@property(retain, nonatomic) UIImage *mailDisplayModeButtonImage; // @synthesize mailDisplayModeButtonImage=_mailDisplayModeButtonImage;
@property(nonatomic) unsigned long long numVisibleColumns; // @synthesize numVisibleColumns=_numVisibleColumns;
@property(nonatomic, getter=isPrimaryAlwaysVisible) _Bool primaryAlwaysVisible; // @synthesize primaryAlwaysVisible=_primaryAlwaysVisible;
@property(readonly, nonatomic) UIMultiColumnViewController *multiColumnController; // @synthesize multiColumnController=_multiColumnController;
@property(nonatomic) _Bool overlayGesturesEnabled; // @synthesize overlayGesturesEnabled=_overlayGesturesEnabled;
@property(readonly, nonatomic) MailDetailNavigationController *messageDetailNavController; // @synthesize messageDetailNavController=_messageDetailNavController;
@property(readonly, nonatomic) MailNavigationController *messageListNavController; // @synthesize messageListNavController=_messageListNavController;
- (void)_updateDisplayModeButtonItem_Staged;
- (void)didBecomeActiveSceneActor;
- (void)applicationSceneController:(id)arg1 willTransitionToTraitCollection:(id)arg2 withTransitionCoordinator:(id)arg3;
- (void)unfocusViewController:(id)arg1 sender:(id)arg2 animated:(_Bool)arg3;
- (void)focusViewController:(id)arg1 sender:(id)arg2 animated:(_Bool)arg3;
- (void)_forceTwoColumnMode;
- (void)_forceSingleColumnMode;
- (_Bool)usePadTransferStyle;
- (_Bool)_gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)_tapRecognizerShouldBegin:(id)arg1;
- (_Bool)_swipeRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_slideInOrNavigateBack:(_Bool)arg1;
- (void)_swipedBack:(id)arg1;
- (void)_tappedDimmingView:(id)arg1;
- (void)_createAndAttachOverlayGestures;
- (void)_splitViewController:(id)arg1 willUpdateDisplayModeButtonItemForTargetMode:(long long)arg2 withHidden:(_Bool *)arg3 image:(id *)arg4 title:(id *)arg5 showsBackButtonIndicator:(_Bool *)arg6;
- (void)_splitViewController:(id)arg1 didEndAnimatedTransitionToStateRequest:(id)arg2;
- (void)_splitViewController:(id)arg1 willBeginAnimatedTransitionToStateRequest:(id)arg2;
- (_Bool)_splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3 forRestorationOfCollapsedWhileSuspendedWithPrimaryVisible:(_Bool)arg4;
- (_Bool)_splitViewControllerIsPrimaryVisible:(id)arg1;
- (_Bool)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
- (_Bool)_conversationViewControllerHasReferenceMessage;
- (id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2;
- (void)_dismissVisiblePopoverInPrimaryViewController;
- (void)splitViewController:(id)arg1 willChangeToDisplayMode:(long long)arg2;
- (id)_mailboxContentViewController;
- (void)traitCollectionDidChange:(id)arg1;
- (void)iterateNavigationControllersWithBlock:(CDUnknownBlockType)arg1;
- (void)setFocusedViewController:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (_Bool)isDetailVisible;
- (void)setDetailDimmed:(_Bool)arg1 aboveViewControllers:(id)arg2 animated:(_Bool)arg3;
- (void)_setDetailDimmingViewsHidden:(_Bool)arg1;
- (void)_setDetailDimmingViewsAlpha:(double)arg1 removeViews:(_Bool)arg2 animated:(_Bool)arg3;
- (void)_removeDetailDimmingViews;
- (void)_addDetailDimmingViewToViewController:(id)arg1;
- (void)setPrimaryVisible:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)_isPortrait;
- (_Bool)isCollapsed;
- (void)dealloc;
- (id)initWithMultiColumnController:(id)arg1 mailNavigationController:(id)arg2 mailDetailNavigationController:(id)arg3 numVisibleColumns:(unsigned long long)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

