//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MFProgressToolbar, MailStatusIndeterminateView, MailStatusProgressBarView, MailStatusUpdateView;

@interface MailStatusBarView : UIView
{
    id <MailStatusBarViewDelegate> _delegate;
    MailStatusProgressBarView *_progressStatusView;
    MailStatusUpdateView *_updateView;
    MailStatusIndeterminateView *_indeterminateView;
    long long _state;
    MFProgressToolbar *_toolbarView;
}

@property(retain, nonatomic) MFProgressToolbar *toolbarView; // @synthesize toolbarView=_toolbarView;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setNeedsDisplay;
- (void)updateForMiniBarState:(_Bool)arg1;
- (void)showIndeterminateStatusWithStatus:(id)arg1;
- (void)showProgressBarWithStatus:(id)arg1;
- (void)showUpdateStatusWithStatus:(id)arg1;
- (void)switchSubviewToView:(id)arg1 showProgress:(_Bool)arg2;
- (void)setDelegate:(id)arg1;
- (void)setTarget:(id)arg1 withAction:(SEL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

