//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MailStatusBar;

@interface MailStatusBarObserver : NSObject
{
    MailStatusBar *_statusbar;
}

@property(readonly, nonatomic) MailStatusBar *statusbar; // @synthesize statusbar=_statusbar;
- (void).cxx_destruct;
- (void)checkForiCloudQuotaUpsellOffer;
- (void)deliveryQueueDeliverySynchronouslyFinished:(id)arg1;
- (void)deliveryQueueDeliverySynchronouslyStarted:(id)arg1;
- (void)deliveryQueueStartedProcessing:(id)arg1;
- (void)startObservingMonitor:(id)arg1;
- (void)monitorFinished:(id)arg1;
- (void)autofetchMailboxStartNotification:(id)arg1;
- (void)connectionEstablished:(id)arg1;
- (void)unreadCountChanged:(id)arg1;
- (void)icqOfferDidChange:(id)arg1;
- (void)accountStatusChanged:(id)arg1;
- (id)initWithStatusBar:(id)arg1;

@end

