//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFDiagnosticsGenerator.h"
#import "MailStatusBarViewDelegate.h"

@class MFAccountStatusManager, MailStatusBarObserver, MailStatusBarView, NSDictionary, NSMutableDictionary, NSNumber, NSObject<OS_dispatch_queue>, NSSet, NSString;

@interface MailStatusBar : NSObject <MFDiagnosticsGenerator, MailStatusBarViewDelegate>
{
    id <MailStatusBarDelegate> _delegate;
    NSNumber *_badgeCount;
    _Bool _shouldShowSubtitle;
    _Bool _showsSubtitleString;
    unsigned long long _unreadCount;
    unsigned long long _unsentCount;
    MailStatusBarView *_ourBarView;
    long long _state;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_mailboxStatuses;
    NSSet *_visibleMailboxes;
    NSDictionary *_currentStatus;
    MailStatusBarObserver *_observer;
    MFAccountStatusManager *_accountStatusManager;
    CDUnknownBlockType _pressedBlock;
    struct CGRect _frame;
}

+ (id)mailStatusBarButtonItem;
+ (id)sharedStatusBar;
@property(copy, nonatomic) CDUnknownBlockType pressedBlock; // @synthesize pressedBlock=_pressedBlock;
@property(retain, nonatomic) MFAccountStatusManager *accountStatusManager; // @synthesize accountStatusManager=_accountStatusManager;
@property(readonly, nonatomic) MailStatusBarObserver *observer; // @synthesize observer=_observer;
@property(retain, nonatomic) NSDictionary *currentStatus; // @synthesize currentStatus=_currentStatus;
@property(retain, nonatomic) NSSet *visibleMailboxes; // @synthesize visibleMailboxes=_visibleMailboxes;
@property(retain, nonatomic) NSMutableDictionary *mailboxStatuses; // @synthesize mailboxStatuses=_mailboxStatuses;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) MailStatusBarView *ourBarView; // @synthesize ourBarView=_ourBarView;
@property(readonly, nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) _Bool showsSubtitleString; // @synthesize showsSubtitleString=_showsSubtitleString;
@property(nonatomic) unsigned long long unsentCount; // @synthesize unsentCount=_unsentCount;
@property(nonatomic) unsigned long long unreadCount; // @synthesize unreadCount=_unreadCount;
- (void).cxx_destruct;
- (void)updateBarItemTitle:(id)arg1 secondaryTitle:(id)arg2;
- (void)tintColorDidChange;
- (id)mailboxQualifier;
- (_Bool)shouldShowSubtitle;
- (long long)interfaceOrientation;
- (id)copyDiagnosticInformation;
- (CDUnknownBlockType)handleAccountErrorActionForAccountErrors:(id)arg1;
- (id)accountStatusErrorMessageForAccountStatusErrors:(id)arg1;
- (id)accountStatusErrors;
- (void)checkForChangeAndNotify;
- (void)refreshView;
- (void)_setNeedsDisplay;
- (void)setNeedsDisplay;
- (_Bool)timeThresholdHasPast:(double)arg1;
- (_Bool)nts_rebuildStatus;
- (void)nts_checkForChangeAndNotify;
- (id)nts_mailboxStatusForMailbox:(id)arg1;
- (void)nts_resetMailboxStatus:(id)arg1;
- (void)nts_monitorFinished:(id)arg1;
- (void)_unreadCountChangedForMailbox:(id)arg1;
- (void)nts_updateMailboxStatus:(id)arg1 forMonitor:(id)arg2 andStatus:(id)arg3;
- (void)nts_startWatchingMailbox:(id)arg1;
- (void)nts_setVisibleMailboxes:(id)arg1;
- (void)connectionEstablished;
- (void)autofetchDidStartForMailbox:(id)arg1 andMonitor:(id)arg2;
- (void)unreadCountChangedForMailbox:(id)arg1;
- (void)updateMailboxStatusesWithICQOffer:(id)arg1;
- (void)updateMailboxForAccountStatusChange;
- (void)addMailbox:(id)arg1;
- (void)setDelegate:(id)arg1 withVisibleMailboxes:(id)arg2;
- (void)monitorFinished:(id)arg1;
- (void)subtitlePressed;
- (void)setMonitor:(id)arg1 status:(id)arg2 forMailbox:(id)arg3;
- (void)handleMonitorStatusChange:(id)arg1 status:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)_barView:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

