//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView;

@interface MailboxGroupedPickerTableCell : UITableViewCell
{
    UIImageView *_mailboxIcon;
    unsigned int _level;
    unsigned int _disabled:1;
    _Bool _rootMailbox;
}

@property(nonatomic, getter=isRootMailbox) _Bool rootMailbox; // @synthesize rootMailbox=_rootMailbox;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)horizontalContentOffset;
- (void)setCurrentMailbox:(_Bool)arg1;
- (void)setCellEnabled:(_Bool)arg1;
- (_Bool)isCellEnabled;
- (void)dealloc;
- (int)levelForMailbox:(id)arg1;
- (void)setMailbox:(id)arg1;
- (id)nameForMailbox:(id)arg1;
- (void)setMailboxType:(int)arg1;
- (void)_setupMailboxIconForImage:(id)arg1;
- (id)_mailboxTextFont;
- (void)_updateContentSizeSettings;
- (void)_preferredContentSizeCategoryDidChange:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

