//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFTableViewCell.h"

@class NSSet, UIButton, UIColor, UIImageView, UILabel;

@interface MailboxTableCell : MFTableViewCell
{
    NSSet *_mailboxes;
    struct CGPoint _iconOffset;
    UIImageView *_leftAccessoryImageView;
    UILabel *_unreadCountLabel;
    UIButton *_detailsDisclosureButton;
    unsigned int _level;
    unsigned int _disabled:1;
    unsigned int _disabledForEditing:1;
    _Bool _hasLeftAccessory;
    _Bool _hideUnreadCountForEditing;
    _Bool _expandable;
    _Bool _expanded;
    _Bool _forceZeroSeparatorInset;
    unsigned int _flattenHierarchy;
    id _userInfo;
    UIColor *_titleColor;
    long long _leftAccessoryType;
    long long _extraIndentLevel;
    UIImageView *_expansionAccessoryImageView;
    UIImageView *_expansionEditingAccessoryImageView;
    id <MFCancelable> _unreadCountToken;
}

+ (id)expansionAccessoryHighlightedImage;
+ (id)expansionAccessoryImage;
+ (id)_disclosureImageWithColor:(id)arg1;
+ (id)subtitleFont;
+ (id)titleFont;
+ (double)twoLineTopBottomPadding;
+ (double)defaultRowHeight;
+ (void)invalidateCachedLayoutInformation;
@property(retain, nonatomic) id <MFCancelable> unreadCountToken; // @synthesize unreadCountToken=_unreadCountToken;
@property(retain, nonatomic) UIImageView *expansionEditingAccessoryImageView; // @synthesize expansionEditingAccessoryImageView=_expansionEditingAccessoryImageView;
@property(retain, nonatomic) UIImageView *expansionAccessoryImageView; // @synthesize expansionAccessoryImageView=_expansionAccessoryImageView;
@property(nonatomic) _Bool forceZeroSeparatorInset; // @synthesize forceZeroSeparatorInset=_forceZeroSeparatorInset;
@property(nonatomic) long long extraIndentLevel; // @synthesize extraIndentLevel=_extraIndentLevel;
@property(nonatomic, getter=isExpanded) _Bool expanded; // @synthesize expanded=_expanded;
@property(nonatomic, getter=isExpandable) _Bool expandable; // @synthesize expandable=_expandable;
@property(nonatomic) long long leftAccessoryType; // @synthesize leftAccessoryType=_leftAccessoryType;
@property(nonatomic) _Bool hideUnreadCountForEditing; // @synthesize hideUnreadCountForEditing=_hideUnreadCountForEditing;
@property(nonatomic) _Bool hasLeftAccessory; // @synthesize hasLeftAccessory=_hasLeftAccessory;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) unsigned int flattenHierarchy; // @synthesize flattenHierarchy=_flattenHierarchy;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_updateUnreadCount;
- (id)_unreadCountForMailboxes:(id)arg1;
- (id)_scriptingInfo;
- (struct CGPoint)destinationPointForAnimation;
- (void)layoutSubviews;
- (void)_doRefreshExpansionAccessoryImageView;
- (void)_doCleanupExpansionAccessoryViews;
- (id)_expansionAccessoryImageView;
- (id)_multiselectBackgroundColor;
- (void)prepareForReuse;
- (id)_leftAccessoryImageView;
- (void)_updateMailboxName;
- (void)_setUnreadCount:(unsigned long long)arg1;
- (void)_removeUnreadCount;
- (void)setCellEnabled:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)setDetailsDisclosureButton:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setIconOffset:(struct CGPoint)arg1;
- (void)setIcon:(id)arg1 withOffset:(struct CGPoint)arg2;
- (void)setIcon:(id)arg1;
- (_Bool)isCellEnabled;
- (void)setDisabledForEditing:(_Bool)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_updateUnreadCountLabelVisibilityAnimated:(_Bool)arg1;
- (_Bool)_shouldUnreadCountBeVisible;
- (void)setBadgeCount:(long long)arg1;
- (void)setMailboxes:(id)arg1 showUnreadCount:(_Bool)arg2;
- (void)setMailboxes:(id)arg1;
- (void)_invalidateLayout;
- (void)dealloc;
- (void)_updateContentSizeSettings;
- (void)_preferredContentSizeCategoryDidChange:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

