//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MailboxContentViewController.h"

#import "MFAtomSearchBarDelegate.h"
#import "MFSearchResultsUpdating.h"
#import "MFSearchSuggestionsGeneratorDelegate.h"
#import "MFSearchSuggestionsViewControllerDelegate.h"
#import "MSSearchSessionControllerDataSource.h"
#import "MessageMiniMallObserver.h"

@class MFMailMessageLibrary, MFSearchMailboxSuggester, MFSearchProgressView, MFSearchSuggestionsGenerator, MFSearchSuggestionsViewController, MFSpotlightSuggester, MSDiagnosticManager, MessageMiniMall, NSSet, NSString, NSTimer, SearchScopeControl, UIView;

@interface MailboxContentSearchViewController : MailboxContentViewController <MessageMiniMallObserver, MFSearchSuggestionsViewControllerDelegate, MFSearchSuggestionsGeneratorDelegate, MSSearchSessionControllerDataSource, MFAtomSearchBarDelegate, MFSearchResultsUpdating>
{
    MFSearchSuggestionsGenerator *_suggestionsGenerator;
    MFSearchSuggestionsViewController *_suggestionsViewController;
    MFSpotlightSuggester *_spotlightSuggester;
    MFSearchMailboxSuggester *_mailboxSuggester;
    NSSet *_alwaysVisibleCategories;
    NSSet *_basicCategories;
    NSString *_lastPhrase;
    unsigned long long _searchTermLength;
    SearchScopeControl *_searchGlobalScopeControl;
    NSSet *_mailboxes;
    struct {
        unsigned int globalScopeControlDisabled:1;
        unsigned int localMailboxSearchOnly:1;
        unsigned int dismissedSuggestions:1;
        unsigned int enableSuggestionDisplay:1;
        unsigned int excludeTrashFromSearches:1;
        unsigned int hasStartedRemoteSearch:1;
    } _flags;
    _Bool _generateCannedSuggestions;
    _Bool _enablePresentationAnimation;
    _Bool _userSelectedTopHit;
    _Bool _topHitsPresent;
    NSSet *_presentingSources;
    id <MFCancelable> _contentInsetObservation;
    id <MFCancelable> _scrollIndicatorInsetsObservation;
    UIView *_snapshotViewForDismissal;
    NSString *_initialSearchString;
    id _suggestionsIdentifier;
    NSTimer *_beginSearchTimer;
    MessageMiniMall *_suggestionsMall;
    MFSearchProgressView *_searchProgressView;
    id <MFCancelable> _searchProgressViewDisplayCancellable;
    unsigned long long _searchStartAbsoluteTime;
}

@property(nonatomic) unsigned long long searchStartAbsoluteTime; // @synthesize searchStartAbsoluteTime=_searchStartAbsoluteTime;
@property(nonatomic) _Bool topHitsPresent; // @synthesize topHitsPresent=_topHitsPresent;
@property(nonatomic) _Bool userSelectedTopHit; // @synthesize userSelectedTopHit=_userSelectedTopHit;
@property(retain, nonatomic) id <MFCancelable> searchProgressViewDisplayCancellable; // @synthesize searchProgressViewDisplayCancellable=_searchProgressViewDisplayCancellable;
@property(retain, nonatomic) MFSearchProgressView *searchProgressView; // @synthesize searchProgressView=_searchProgressView;
@property(retain, nonatomic) MessageMiniMall *suggestionsMall; // @synthesize suggestionsMall=_suggestionsMall;
@property(retain, nonatomic) NSTimer *beginSearchTimer; // @synthesize beginSearchTimer=_beginSearchTimer;
@property(retain, nonatomic) id suggestionsIdentifier; // @synthesize suggestionsIdentifier=_suggestionsIdentifier;
@property(copy, nonatomic) NSString *initialSearchString; // @synthesize initialSearchString=_initialSearchString;
@property(nonatomic) _Bool enablePresentationAnimation; // @synthesize enablePresentationAnimation=_enablePresentationAnimation;
@property(retain, nonatomic) UIView *snapshotViewForDismissal; // @synthesize snapshotViewForDismissal=_snapshotViewForDismissal;
@property(retain, nonatomic) id <MFCancelable> scrollIndicatorInsetsObservation; // @synthesize scrollIndicatorInsetsObservation=_scrollIndicatorInsetsObservation;
@property(retain, nonatomic) id <MFCancelable> contentInsetObservation; // @synthesize contentInsetObservation=_contentInsetObservation;
@property(nonatomic) _Bool generateCannedSuggestions; // @synthesize generateCannedSuggestions=_generateCannedSuggestions;
@property(copy, nonatomic) NSSet *presentingSources; // @synthesize presentingSources=_presentingSources;
- (void).cxx_destruct;
- (void)globalSearchScopeChanged:(id)arg1;
- (int)emailProviderForSearchSessionController:(id)arg1;
- (unsigned long long)percentOfMessagesIndexedForSearchSessionController:(id)arg1;
- (unsigned long long)numberOfMessagesLeftToIndexForSearchSessionController:(id)arg1;
@property(readonly, nonatomic) MSDiagnosticManager *diagnosticManager;
- (id)selectionModel:(id)arg1 sourcesForMessageInfos:(id)arg2;
- (_Bool)atomSearchBar:(id)arg1 storeRepresentedObjects:(id)arg2 onPasteboard:(id)arg3;
- (id)atomSearchBar:(id)arg1 representedObjectsFromPasteboard:(id)arg2;
- (id)supportedPasteboardTypesForAtomSearchBar:(id)arg1;
- (void)searchButtonTappedForAtomSearchBar:(id)arg1;
- (void)atomSearchBar:(id)arg1 selectedScopeButtonIndexDidChange:(long long)arg2 forRepresentedObject:(id)arg3;
- (long long)atomSearchBar:(id)arg1 selectedScopeButtonIndexForRepresentedObject:(id)arg2;
- (id)atomSearchBar:(id)arg1 scopeButtonTitlesForRepresentedObject:(id)arg2;
- (id)atomSearchBar:(id)arg1 atomViewForRepresentedObject:(id)arg2;
- (id)containingViewForAtomSearchBar:(id)arg1;
- (void)searchSuggestionsViewController:(id)arg1 didDismissPreviewViewController:(id)arg2 committing:(_Bool)arg3;
- (void)searchSuggestionsViewController:(id)arg1 previewingContext:(id)arg2 commitViewController:(id)arg3;
- (id)searchSuggestionsViewController:(id)arg1 previewingContext:(id)arg2 viewControllerForMessage:(id)arg3 indexInformation:(id)arg4 view:(id)arg5 canShowAsConversation:(_Bool)arg6;
- (_Bool)shouldDisableGlobalScopeControlForSearchSuggestionsController:(id)arg1;
- (long long)selectedScopeIndexForSearchSuggestionsController:(id)arg1;
- (void)searchSuggestionsViewController:(id)arg1 didSelectSearchScopeIndex:(long long)arg2;
- (void)searchSuggestionsViewController:(id)arg1 didSelectSuggestion:(id)arg2;
- (void)searchSuggestionsViewController:(id)arg1 didSelectMessage:(id)arg2 indexInformation:(id)arg3 mall:(id)arg4;
- (void)displayMessage:(id)arg1 options:(unsigned long long)arg2 animated:(_Bool)arg3;
- (id)addressStringForSearchSuggestionsController:(id)arg1 addressList:(id)arg2;
- (id)scopeIdentifierForPeopleSuggestions;
- (_Bool)searchSuggestionsViewController:(id)arg1 shouldShowSuggestionsForCategory:(id)arg2;
- (void)getDefaultPersonScopeIdentifier:(id *)arg1 alternativeScopeIdentifier:(id *)arg2;
- (id)basicCategories;
- (id)alwaysVisibleCategories;
- (void)suggestionsGenerator:(id)arg1 finishedWithIdentifier:(id)arg2;
- (void)suggestionsGenerator:(id)arg1 hasSuggestions:(id)arg2 categories:(id)arg3 forIdentifier:(id)arg4;
- (void)_addSearchEngagementIncludeSuggestionsEngagement:(_Bool)arg1;
- (id)_generateUserSuggestionsEngagement;
- (id)_engagementAtomsTypesFromSearchBarItems:(id)arg1;
- (void)beginSearchWithString:(id)arg1 searchController:(id)arg2;
- (void)_beginSearchWithInitialString;
- (void)noteCriterionUpdated:(unsigned long long)arg1;
- (_Bool)_shouldUpdateSearchForOptions:(unsigned long long)arg1;
- (id)basicSearchText;
- (_Bool)_shouldSearchCurrentMailboxOnly;
- (id)criterion;
- (id)_criterionForTopSuggestedPeople;
- (id)localMailboxCriterion;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (id)_currentEditingStringForSearchBar:(id)arg1;
- (void)invokeTapToRadar;
- (void)_searchTapToRadarButtonSelected:(id)arg1;
- (id)_searchTapToRadarButtonItem;
- (id)_additionalBarButtonItems;
@property(nonatomic, getter=isSearchSuggestionsVisible) _Bool searchSuggestionsVisible;
- (void)_cleanupInsetObservations;
- (void)_setupInsetObservations;
- (void)_generateSuggestionsForPhrase:(id)arg1;
- (void)_configureSuggestersUsingPhraseManager:(id)arg1;
- (id)_phraseManagerForPhrase:(id)arg1;
- (id)baseSpotlightSuggesterPredicate;
- (id)exclusionPredicate;
- (id)excludedMailboxes;
- (id)allExcludedMailboxes;
- (_Bool)atomSearchBar:(id)arg1 hasAtomFromCategory:(id)arg2;
- (_Bool)atomSearchBar:(id)arg1 hasAtomWithSelectedScopeIdentifier:(id)arg2;
- (id)atomSearchBar;
- (void)selectInitialMessageForConversationViewController:(id)arg1;
- (id)conversationViewController:(id)arg1 messagesToActOnForReferenceMessage:(id)arg2;
- (void)conversationViewController:(id)arg1 didRemoveAllVisibleMessages:(id)arg2;
- (_Bool)conversationViewController:(id)arg1 canAdvanceToNextConversationWithDirection:(int)arg2;
- (void)_updateTableForSettingsOrTimeChange:(id)arg1;
- (void)_showTableFooterContinueSearchingView:(_Bool)arg1;
- (_Bool)allowsAutoSelectionOfInitialMessage;
- (_Bool)_shouldUpdateBarButtons;
- (void)miniMallMessageCountDidChange:(id)arg1;
- (void)miniMallDidFinishSearch:(id)arg1;
- (void)_logSearchPerformance;
- (void)_setInEditMode:(_Bool)arg1 animated:(_Bool)arg2;
- (id)mailboxes;
- (void)setMailboxes:(id)arg1;
@property(readonly, nonatomic) MFMailMessageLibrary *mailMessageLibrary;
- (_Bool)isSearching;
- (id)toolbarItems;
- (void)setToolbarItems:(id)arg1 animated:(_Bool)arg2;
- (id)targetViewControllerForAction:(SEL)arg1 sender:(id)arg2;
- (id)navigationController;
- (id)splitViewController;
- (void)willMoveToParentViewController:(id)arg1;
- (void)_updateTableHeaderView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)didDismissSearchController:(id)arg1;
- (void)willDismissSearchController:(id)arg1;
- (void)_prepareSnapshotViewForDismissal;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willPresentSearchController:(id)arg1;
- (void)_configureSearchWithTableView:(id)arg1;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

