//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCSChange.h"

@class MCSMessageOperation, NSSet;

@interface MailMessageChangeSet : MCSChange
{
    NSSet *_messagesSet;
    NSSet *_messagesMarkedRead;
    NSSet *_messagesMarkedUnread;
    NSSet *_messagesUnflagged;
    NSSet *_messagesFlagged;
    MCSMessageOperation *_operation;
}

@property(readonly) MCSMessageOperation *operation; // @synthesize operation=_operation;
- (id)_unreadCountAdjustmentByMailboxForCriterion:(id)arg1;
- (unsigned long long)adjustUnreadCount:(unsigned long long)arg1 withCriterion:(id)arg2;
- (id)URLStrings;
- (id)accounts;
- (id)stores;
- (id)copyChangeSetForFullPath:(id)arg1;
- (id)description;
- (_Bool)isRevertible;
- (void)_adjustStatusCountsForRevert:(_Bool)arg1;
- (_Bool)revert;
- (_Bool)commit;
- (id)applyPendingChangeToObjects:(id)arg1;
- (id)messagesSet;
- (void)_populateMessageSets;
- (long long)localizedChangeDescriptionPriority;
- (id)localizedChangeDescription;
- (id)localizedErrorTitle;
- (id)localizedErrorDescription;
- (void)_setMessages:(id)arg1;
- (void)dealloc;
- (id)initWithMessages:(id)arg1 unreadMessages:(id)arg2 readMessages:(id)arg3 flaggedMessages:(id)arg4 unflaggedMessages:(id)arg5 operation:(id)arg6;
- (id)initWithMessages:(id)arg1 operation:(id)arg2;

@end

