//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MailboxGroupedPickerTableCell.h"

@interface MailMailboxGroupedPickerTableCell : MailboxGroupedPickerTableCell
{
    _Bool _alwaysDisplayAsTopLevel;
}

@property(nonatomic) _Bool alwaysDisplayAsTopLevel; // @synthesize alwaysDisplayAsTopLevel=_alwaysDisplayAsTopLevel;
- (double)horizontalContentOffset;
- (id)nameForMailbox:(id)arg1;
- (int)levelForMailbox:(id)arg1;
- (double)fontSize;

@end

