//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MessageCallToActionFormatter.h"

@class MessageCallToActionListUnsubscribe;

@interface MessageCallToActionListUnsubscribeFormatter : MessageCallToActionFormatter
{
    MessageCallToActionListUnsubscribe *_callToAction;
}

@property(retain, nonatomic) MessageCallToActionListUnsubscribe *callToAction; // @synthesize callToAction=_callToAction;
- (id)actionTitle;
- (id)subtitle;
- (id)title;
- (void)dealloc;
- (id)initWithCallsToAction:(id)arg1;

@end

