//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MessageStatusIndicatorManager : NSObject
{
    unsigned long long _indicatorOptions;
    unsigned long long _disabledIndicatorOptions;
    _Bool _useMiniIcons;
}

+ (unsigned long long)statusIndicatorOptionsForMessageFlags:(unsigned long long)arg1 conversationFlags:(unsigned long long)arg2;
+ (id)unreadFlaggedImageWithUnreadColor:(id)arg1 flaggedColor:(id)arg2 mini:(_Bool)arg3;
+ (id)miniFlagShapeImage;
+ (id)flagShapeImage;
+ (id)miniDotIndicatorImage;
+ (id)dotIndicatorImage;
@property(nonatomic) unsigned long long indicatorOptions; // @synthesize indicatorOptions=_indicatorOptions;
@property(nonatomic) _Bool useMiniIcons; // @synthesize useMiniIcons=_useMiniIcons;
- (_Bool)_indicatorOptionsAreDisabled:(unsigned long long)arg1;
- (void)_setIndicatorOptions:(unsigned long long)arg1 disabled:(_Bool)arg2;
- (id)statusIndicatorImageWithOptionsMask:(unsigned long long)arg1;
- (id)statusIndicatorImageWithOptions:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long effectiveIndicatorOptions;
@property(nonatomic) _Bool hidesAttachmentIndicator;
@property(nonatomic) _Bool hidesVIPIndicator;
@property(nonatomic) _Bool hidesUnreadIndicator;

@end

