//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "MFSuggestionHandlingDelegate.h"

@class MessageCallToAction, MessageSuggestionSession, NSMutableArray, NSString;

@interface MessageCallsToActionController : UITableViewController <MFSuggestionHandlingDelegate>
{
    NSMutableArray *_groupTitles;
    NSMutableArray *_groupedCallsToAction;
    MessageSuggestionSession *_suggestionSession;
    id <MFSuggestionHandlingDelegate> _delegate;
    MessageCallToAction *_inProgressAction;
}

@property(retain, nonatomic) MessageCallToAction *inProgressAction; // @synthesize inProgressAction=_inProgressAction;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)displayMultipleCallsToAction:(id)arg1 presentationSource:(id)arg2;
- (void)didIgnoreAction:(id)arg1;
- (void)_hideAction:(id)arg1;
- (id)indexPathForAction:(id)arg1 containingGroup:(id *)arg2;
- (void)didConfirmAction:(id)arg1;
- (void)ignoreAction:(id)arg1;
- (void)showConfirmationForAction:(id)arg1 presentationSource:(id)arg2;
- (struct CGSize)preferredContentSize;
- (void)recalculateCellGroups;
- (id)_titleForCategory:(long long)arg1;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithSuggestionSession:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

