//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivity.h"

@class UIPrintPageRenderer;

@interface MessagePrintQuicklookableAttachmentActivity : UIActivity
{
    UIPrintPageRenderer *_pageRenderer;
}

@property(retain, nonatomic) UIPrintPageRenderer *pageRenderer; // @synthesize pageRenderer=_pageRenderer;
- (void)performActivity;
- (_Bool)canPerformWithActivityItems:(id)arg1;
- (id)activityImage;
- (id)activityTitle;
- (id)activityType;
- (void)dealloc;
- (id)initWithPrintPageRenderer:(id)arg1;

@end

