//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MessageCallToAction.h"

@class MFListUnsubscribeSuggestion, NSString;

@interface MessageCallToActionListUnsubscribe : MessageCallToAction
{
    NSString *_title;
    NSString *_subtitle;
}

+ (id)callToActionForListUnsubscribeSuggestion:(id)arg1;
- (void)ignore;
- (void)confirm;
- (id)confirmationViewController;
- (id)supplementaryActionTitle;
- (id)secondaryActionTitle;
- (id)primaryActionTitle;
- (id)subtitle;
- (id)title;
- (_Bool)hideAfterConfirming;
@property(readonly, retain, nonatomic) MFListUnsubscribeSuggestion *listUnsubscribeSuggestion;
- (id)mixedBundleIdentifier;
- (id)bundleIdentifier;
- (long long)compare:(id)arg1;
- (void)dealloc;

@end

