//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "MFPopoverPresentationSource.h"

@class NSArray, NSAttributedString, NSLayoutConstraint, NSString, UIImage, UIImageView, UILabel, UILayoutGuide;

@interface MessageSuggestionTitleControl : UIControl <MFPopoverPresentationSource>
{
    NSLayoutConstraint *_subtitleTrailingPaddingConstraint;
    NSLayoutConstraint *_iconStackTrailingConstraint;
    NSLayoutConstraint *_iconStackWidthConstraint;
    NSLayoutConstraint *_iconStackVerticalConstraint;
    NSLayoutConstraint *_topMarginConstraint;
    NSLayoutConstraint *_actionLabelTopSubtitleConstraint;
    NSLayoutConstraint *_actionLabelTopTitleConstraint;
    NSLayoutConstraint *_subtitleBottomMarginConstraint;
    NSArray *_interLabelPaddingConstraints;
    NSArray *_bottomMarginConstraints;
    UILayoutGuide *_userContentGuide;
    _Bool _usingLargeTextLayout;
    double _iconStackMargin;
    UIImageView *_iconStack;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_actionLabel;
}

+ (double)bottomMarginConstant;
+ (double)interLabelBaselineDeltaConstant;
+ (double)interLabelPaddingConstant;
+ (double)topMarginConstant;
+ (id)subtitleFont;
+ (id)titleFont;
@property(readonly, retain, nonatomic) UILabel *actionLabel; // @synthesize actionLabel=_actionLabel;
@property(readonly, retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, retain, nonatomic) UIImageView *iconStack; // @synthesize iconStack=_iconStack;
@property(readonly, nonatomic) double iconStackMargin; // @synthesize iconStackMargin=_iconStackMargin;
- (void).cxx_destruct;
- (void)mf_setAsSourceForPopoverPresentationController:(id)arg1;
- (void)contentSizeCategoryDidChangeNotification:(id)arg1;
@property(readonly, nonatomic) UILayoutGuide *userContentGuide;
- (id)viewForLastBaselineLayout;
- (id)viewForFirstBaselineLayout;
@property(copy, nonatomic) NSAttributedString *subtitleAttributedText;
@property(copy, nonatomic) NSString *subtitleText;
@property(copy, nonatomic) NSString *actionText;
@property(copy, nonatomic) NSString *titleText;
- (void)tintColorDidChange;
- (void)setTintColor:(id)arg1;
@property(retain, nonatomic) UIImage *iconImage;
- (id)constraintsForEdges:(unsigned long long)arg1 withinView:(id)arg2 useLayoutMarginsGuide:(_Bool)arg3;
- (void)_setupConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

