//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivity.h"

@class MFAttachment;

@interface MessageQuicklookImageAttachmentsActivity : UIActivity
{
    id <MFAttachmentHandlingDelegate> _delegate;
    MFAttachment *_attachment;
}

@property(retain, nonatomic) MFAttachment *attachment; // @synthesize attachment=_attachment;
@property(nonatomic) __weak id <MFAttachmentHandlingDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_cleanup;
- (void)performActivity;
- (id)_beforeActivity;
- (_Bool)canPerformWithActivityItems:(id)arg1;
- (id)activityImage;
- (id)activityTitle;
- (id)activityType;
- (void)dealloc;
- (id)initWithAttachmentHandlingDelegate:(id)arg1 context:(long long)arg2 attachment:(id)arg3;

@end

