//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MessageCallToAction.h"

#import "CNContactViewControllerDelegate.h"

@class NSString, SGRealtimeContact;

@interface MessageCallToActionRealtimeContact : MessageCallToAction <CNContactViewControllerDelegate>
{
    NSString *_title;
    NSString *_subtitle;
}

+ (id)callToActionForRealtimeContact:(id)arg1;
- (void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2;
- (_Bool)contactViewController:(id)arg1 shouldPerformDefaultActionForContactProperty:(id)arg2;
- (void)ignore;
- (void)confirm;
- (id)confirmationViewController;
- (id)supplementaryActionTitle;
- (id)secondaryActionTitle;
- (id)primaryActionTitle;
- (id)subtitle;
- (id)title;
@property(readonly, retain, nonatomic) SGRealtimeContact *realtimeContact;
- (id)bundleIdentifier;
- (long long)compare:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

