//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageHeaderViewBlock.h"

@class MessageSuggestionTitleControl, NSArray, NSLayoutConstraint, UIView;

@interface MessageSuggestionBannerView : MFMessageHeaderViewBlock
{
    _Bool _didSetAccessoryViewConstraints;
    id <MessageSuggestionDataSource> _dataSource;
    id <MFSuggestionHandlingDelegate> _suggestionHandlingDelegate;
    NSArray *_callsToAction;
    MessageSuggestionTitleControl *_titleControl;
    NSArray *_titleControlConstraints;
    UIView *_accessoryView;
    NSLayoutConstraint *_titleControlLeadingConstraint;
    NSLayoutConstraint *_accessoryViewVerticalConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *accessoryViewVerticalConstraint; // @synthesize accessoryViewVerticalConstraint=_accessoryViewVerticalConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleControlLeadingConstraint; // @synthesize titleControlLeadingConstraint=_titleControlLeadingConstraint;
@property(nonatomic) _Bool didSetAccessoryViewConstraints; // @synthesize didSetAccessoryViewConstraints=_didSetAccessoryViewConstraints;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(retain, nonatomic) NSArray *titleControlConstraints; // @synthesize titleControlConstraints=_titleControlConstraints;
@property(retain, nonatomic) MessageSuggestionTitleControl *titleControl; // @synthesize titleControl=_titleControl;
@property(retain, nonatomic) NSArray *callsToAction; // @synthesize callsToAction=_callsToAction;
@property(nonatomic) __weak id <MFSuggestionHandlingDelegate> suggestionHandlingDelegate; // @synthesize suggestionHandlingDelegate=_suggestionHandlingDelegate;
@property(nonatomic) __weak id <MessageSuggestionDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)setSeparatorDrawsFlushWithTrailingEdge:(_Bool)arg1;
- (void)setSeparatorDrawsFlushWithLeadingEdge:(_Bool)arg1;
- (void)setDisplayMetrics:(id)arg1;
- (void)_disclousureButtonTapped:(id)arg1;
- (void)_dismissButtonTapped:(id)arg1;
- (void)_actionControlTapped:(id)arg1;
- (void)_prefetchGeocodeInformation;
- (id)_subtitleAttributesDictionaryForCallsToAction:(id)arg1;
- (void)_updateBanner;
- (void)reloadData;
- (id)_disclosureIconImage;
- (id)_accessoryDisclosureButton;
- (id)_accessoryDismissButton;
- (id)_accessoryViewForType:(long long)arg1;
- (void)updateAccessoryViewWithType:(long long)arg1;
- (void)contentSizeCategoryDidChangeNotification:(id)arg1;
- (void)_setupAccessoryViewVerticalConstraint;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

