//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFSuggestionHandlingDelegate.h"
#import "NSCopying.h"

@class EKEventStore, NSArray, NSMutableSet, NSString;

@interface MessageSuggestionSession : NSObject <MFSuggestionHandlingDelegate, NSCopying>
{
    NSMutableSet *_callsToAction;
    EKEventStore *_eventStore;
    struct __CFDictionary *_resultsMapping;
    id <MFSuggestionHandlingDelegate> _delegate;
}

@property(nonatomic) __weak id <MFSuggestionHandlingDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_setResult:(id)arg1 forCallToAction:(id)arg2;
- (id)_resultForCallToAction:(id)arg1;
- (void)didIgnoreAction:(id)arg1;
- (void)didConfirmAction:(id)arg1;
- (void)ignoreAction:(id)arg1;
- (void)displayMultipleCallsToAction:(id)arg1 presentationSource:(id)arg2;
- (void)showConfirmationForAction:(id)arg1 presentationSource:(id)arg2;
- (id)contactForCallToAction:(id)arg1;
- (id)eventForCallToAction:(id)arg1;
- (void)setEvent:(id)arg1 forCallToAction:(id)arg2;
- (void)setContact:(id)arg1 forCallToAction:(id)arg2;
@property(readonly, nonatomic) EKEventStore *eventStore;
@property(readonly, nonatomic) NSArray *callsToAction;
- (void)addCallsToAction:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithCallsToAction:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

