//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFAccount, MFError;

@interface MFAccountHealer : NSObject
{
    MFAccount *_account;
    MFAccount *_alternateAccount;
    MFError *_error;
}

@property(readonly, nonatomic) MFError *error; // @synthesize error=_error;
@property(readonly, nonatomic) MFAccount *alternateAccount; // @synthesize alternateAccount=_alternateAccount;
@property(readonly, nonatomic) MFAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_renewCredentialsWithError:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_overwriteAccount:(id)arg1 withAlternateAccount:(id)arg2;
- (id)_lastTimeConnectToACEDBForAccount:(id)arg1;
- (id)_getMailAccountFromDeliveryAccount:(id)arg1;
- (id)_fetchServerFromACEDB:(id)arg1 forIncomingServer:(_Bool)arg2;
- (_Bool)_shouldHealAccount:(id)arg1 withNewAccount:(id)arg2;
- (id)_alternateAccount;
- (_Bool)shouldHealFromAlternateAccount;
- (void)healFromAlternateAccountWithCompletion:(CDUnknownBlockType)arg1;
- (void)healSilentlyWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithAccount:(id)arg1 error:(id)arg2;

@end

