//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MFGradientView, NSString, UILabel;

@interface MFActorItemHeaderView : UIView
{
    UIView *_backgroundView;
    NSString *_title;
    double _cornerRadius;
    double _bottomInset;
    MFGradientView *_bottomExtensionView;
    UIView *_contentView;
    UILabel *_titleLabel;
    UIView *__safeAreaView;
}

@property(retain, nonatomic) UIView *_safeAreaView; // @synthesize _safeAreaView=__safeAreaView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) MFGradientView *bottomExtensionView; // @synthesize bottomExtensionView=_bottomExtensionView;
@property(nonatomic) double bottomInset; // @synthesize bottomInset=_bottomInset;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)_createPrimaryViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

