//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFAccount, MFError;

@interface MFAccountStatus : NSObject
{
    MFAccount *_account;
    long long _status;
    MFError *_error;
}

@property(retain, nonatomic) MFError *error; // @synthesize error=_error;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) MFAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)initWithAccount:(id)arg1;
- (id)initWithAccount:(id)arg1 accountStatus:(long long)arg2 error:(id)arg3;

@end

