//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFMailboxPredictionEventCounter.h"

@class NSString;

@interface MFAggDEventCounter : NSObject <MFMailboxPredictionEventCounter>
{
    NSString *_modelName;
}

@property(copy, nonatomic) NSString *modelName; // @synthesize modelName=_modelName;
- (void).cxx_destruct;
- (id)_keyForEvent:(unsigned long long)arg1 context:(unsigned long long)arg2 prediction:(id)arg3 mailbox:(id)arg4;
- (id)_nameForEvent:(unsigned long long)arg1 wasCorrect:(_Bool)arg2;
- (id)_nameForContext:(unsigned long long)arg1 numPredictions:(unsigned long long)arg2;
- (_Bool)_predictionWasCorrect:(id)arg1 mailbox:(id)arg2;
- (void)countEvent:(unsigned long long)arg1 context:(unsigned long long)arg2 prediction:(id)arg3 mailbox:(id)arg4;
- (id)initWithModelName:(id)arg1;

@end

