//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MFActorItemSnapshotCacheDelegate.h"
#import "MFKeyCommandReacting.h"
#import "MFTiltedTabViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UISpringLoadedInteractionBehavior.h"
#import "UISpringLoadedInteractionEffect.h"
#import "UIViewControllerTransitioningDelegate.h"

@class MFActorItemSnapshotCache, MFNullAnimationTransitionCoordinator, MFRoundedCornerCutoutView, MFTiltedTabView, MFVelocityIntegrator, NSArray, NSMapTable, NSMutableArray, NSString, NSTimer, SBSAssertion, UIPanGestureRecognizer, UITapGestureRecognizer, UIView, UIViewController<MFApplicationSceneActor>, _MFActorItem;

@interface MFApplicationSceneController : UIViewController <MFTiltedTabViewDelegate, MFActorItemSnapshotCacheDelegate, MFKeyCommandReacting, UISpringLoadedInteractionBehavior, UISpringLoadedInteractionEffect, UIGestureRecognizerDelegate, UIViewControllerTransitioningDelegate>
{
    long long _currentStatusBarStyle;
    UIView *_containerView;
    UIView *_sceneDimmingView;
    MFRoundedCornerCutoutView *_backgroundCutoutView;
    MFVelocityIntegrator *_velocityIntegrator;
    int _lockedAxis;
    struct CGRect _axisTransitionZone;
    struct CGPoint _lastTouchPosition;
    struct CGPoint _lastDirectionChangePoint;
    double _lastDirectionChangeTime;
    struct CGPoint _activeActorStartCenter;
    UITapGestureRecognizer *_engageTapGesture;
    UIPanGestureRecognizer *_engagePanGesture;
    id <UISpringLoadedInteractionEffect> _springLoadedDraftShelfEffect;
    NSTimer *_purgingTimer;
    NSMapTable *_actorItemToDecayTimeMapTable;
    NSMutableArray *_actorItems;
    _MFActorItem *_activeActorItem;
    _MFActorItem *_primaryActorItem;
    struct UIViewController *_primaryViewController;
    MFNullAnimationTransitionCoordinator *_activeTransitionCoordinator;
    MFTiltedTabView *_tiltedTabView;
    unsigned long long _tabItemIndexToSelect;
    _MFActorItem *_interactivelyAnimatingActorItem;
    MFActorItemSnapshotCache *_snapshotCache;
    struct {
        unsigned int primaryViewProstrated:1;
        unsigned int primaryViewConstricted:1;
        unsigned int exposeModeActivated:1;
        unsigned int prefersSideLayout:1;
        unsigned int prepareRadiusAnimationOnFirstLayout:1;
    } _flags;
    _Bool _automaticallyPurgesInactiveActors;
    _Bool _showWallpaperBackground;
    id <MFApplicationSceneDelegate> _sceneDelegate;
    SBSAssertion *_wallpaperSuspensionAssertion;
}

@property(retain, nonatomic) SBSAssertion *wallpaperSuspensionAssertion; // @synthesize wallpaperSuspensionAssertion=_wallpaperSuspensionAssertion;
@property(retain, nonatomic) MFNullAnimationTransitionCoordinator *activeTransitionCoordinator; // @synthesize activeTransitionCoordinator=_activeTransitionCoordinator;
@property(nonatomic, getter=isShowingWallpaperBackground) _Bool showWallpaperBackground; // @synthesize showWallpaperBackground=_showWallpaperBackground;
@property(nonatomic) id <MFApplicationSceneDelegate> sceneDelegate; // @synthesize sceneDelegate=_sceneDelegate;
@property(nonatomic) _Bool automaticallyPurgesInactiveActors; // @synthesize automaticallyPurgesInactiveActors=_automaticallyPurgesInactiveActors;
- (id)allActorDescriptions;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)coordinateAnimationWithDuration:(double)arg1 animations:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (id)coordinateAnimationWithDuration:(double)arg1 delay:(double)arg2 usingSpringWithDamping:(double)arg3 initialSpringVelocity:(double)arg4 options:(unsigned long long)arg5 animations:(CDUnknownBlockType)arg6 completion:(CDUnknownBlockType)arg7;
- (_Bool)shouldAutorotate;
- (double)tiltedTabView:(id)arg1 alphaValueForItemAtIndex:(unsigned long long)arg2;
- (struct CATransform3D)tiltedTabView:(id)arg1 expanded:(_Bool)arg2 layerTransformForItemAtIndex:(unsigned long long)arg3;
- (struct CGRect)tiltedTabView:(id)arg1 frameForItemAtIndex:(unsigned long long)arg2;
- (double)tiltedTabView:(id)arg1 headerHeightForItemAtIndex:(unsigned long long)arg2;
- (void)tiltedTabView:(id)arg1 didMoveItemAtIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (void)tiltedTabView:(id)arg1 closeItemAtIndex:(unsigned long long)arg2;
- (_Bool)tiltedTabView:(id)arg1 canCloseItemAtIndex:(unsigned long long)arg2;
- (void)tiltedTabView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2;
- (void)tiltedTabView:(id)arg1 relinquishSnapshotView:(id)arg2 forItemAtIndex:(unsigned long long)arg3;
- (void)tiltedTabView:(id)arg1 relinquishContentView:(id)arg2 forItemAtIndex:(unsigned long long)arg3;
- (id)tiltedTabView:(id)arg1 headerViewForItemAtIndex:(unsigned long long)arg2;
- (id)tiltedTabView:(id)arg1 maskCutoutViewForItemAtIndex:(unsigned long long)arg2;
- (id)tiltedTabView:(id)arg1 snapshotViewForItemAtIndex:(unsigned long long)arg2;
- (struct UIEdgeInsets)tiltedTabView:(id)arg1 expanded:(_Bool)arg2 edgeInsetsForItemAtIndex:(unsigned long long)arg3;
- (id)tiltedTabView:(id)arg1 contentViewForItemAtIndex:(unsigned long long)arg2;
- (long long)numberOfItemsInTiltedTabView:(id)arg1;
- (void)tiltedTabViewDidDismiss:(id)arg1;
- (void)tiltedTabViewDidScroll:(id)arg1;
- (void)tiltedTabViewWillDismiss:(id)arg1;
- (void)tiltedTabViewDidPresent:(id)arg1;
- (void)tiltedTabViewDidLayoutItems:(id)arg1;
- (void)tiltedTabViewWillPresent:(id)arg1;
- (id)_actorItemAtIndex:(unsigned long long)arg1;
- (id)snapshotCache:(id)arg1 updatedSnapshotForItemWithIdentifier:(id)arg2;
- (_Bool)snapshotCache:(id)arg1 shouldEvictSnapshotForItemWithIdentifier:(id)arg2;
- (void)snapshotCache:(id)arg1 didEvictSnapshotForItemWithIdentifier:(id)arg2;
- (void)snapshotCache:(id)arg1 didCacheSnapshotForItemWithIdentifier:(id)arg2;
- (id)_generateSnapshotImageForActorView:(id)arg1;
- (id)_actorItemForSnapshotIdentifier:(id)arg1;
- (void)_invalidatePurgingDecayForActorItem:(id)arg1;
- (void)_beginPurgingDecayForActorItemIfNecessary:(id)arg1;
- (void)_purgeInactiveActorsTimerFired:(id)arg1;
- (_Bool)_resurrectActorItemIfNecessary:(id)arg1;
- (void)_purgeInactiveActorsBeyondDepthThreshold;
- (void)_purgeActorItem:(id)arg1;
- (_Bool)_sceneDelegateSupportsPurgingAndResurrection;
- (id)targetForAction:(SEL)arg1 withSender:(id)arg2;
- (id)keyCommands;
- (void)_makeTopActorItemActiveCommandInvoked:(id)arg1;
- (void)_withdrawActiveActorItemKeyCommandInvoked:(id)arg1;
- (_Bool)_withdrawActiveActorItemKeyCommandIsAvailable;
- (void)interaction:(id)arg1 didChangeWithContext:(id)arg2;
- (_Bool)shouldAllowInteraction:(id)arg1 withContext:(id)arg2;
- (void)_addSpringLoadedInteractionToActorItem:(id)arg1;
- (void)_springLoadWithInteractionContext:(id)arg1;
- (void)_activateDraftsFromShelf;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_setPrimaryViewConstrictedForBottomShelf:(_Bool)arg1;
- (void)_handleEngagePanGesture:(id)arg1;
- (void)_handleEngageTapGesture:(id)arg1;
- (struct CGRect)_engagementRectForActor:(id)arg1;
- (void)_ensureSnapshotsAreUpToDate;
- (id)_currentlyVisibleActorItems;
- (void)_sceneStateDidChange;
- (id)_allSnapshotIdentifiers;
- (_Bool)restoreStateFromDisk;
- (void)flushRestorableStateToDisk;
- (void)forciblyPurgeAllInactiveActorViewControllers;
- (id)actorViewControllersOfKind:(Class)arg1;
@property(readonly, nonatomic) NSArray *actorViewControllers; // @dynamic actorViewControllers;
- (void)setExposeModeActivated:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=isExposeModeActivated) _Bool exposeModeActivated;
- (void)withdrawActiveViewControllerAnimated:(_Bool)arg1;
- (void)_dismissMarkedUpComposeFromOnTopOfQuickLook:(id)arg1 options:(id)arg2;
- (void)dismissViewController:(struct UIViewController *)arg1 animated:(_Bool)arg2 options:(id)arg3;
- (void)dismissViewController:(struct UIViewController *)arg1 animated:(_Bool)arg2;
- (void)presentModalViewController:(struct UIViewController *)arg1 animated:(_Bool)arg2 options:(id)arg3;
- (void)presentModalViewController:(struct UIViewController *)arg1 animated:(_Bool)arg2;
- (void)_presentActorItem:(id)arg1 animated:(_Bool)arg2 options:(id)arg3;
- (struct UIViewController *)activeViewController;
@property(retain, nonatomic) UIViewController<MFApplicationSceneActor> *primaryViewController; // @dynamic primaryViewController;
- (id)primarySplitViewController;
- (void)_removeActorItem:(id)arg1;
- (id)_actorItemForActorViewController:(struct UIViewController *)arg1 encodedActor:(id)arg2 createIfNecessary:(_Bool)arg3;
- (id)_actorItemForActorViewController:(struct UIViewController *)arg1 createIfNecessary:(_Bool)arg2;
- (void)_setActiveActorItem:(id)arg1 animated:(_Bool)arg2;
- (void)_didWithdrawActorItem:(id)arg1;
- (void)_willWithdrawActorItem:(id)arg1;
- (void)_suspendWallpaperAnimationIfNecessary;
- (void)_layoutActorViewControllers;
- (void)_layoutActorItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)_layoutPrimaryViewControllerView;
- (void)_getPrimaryViewBounds:(struct CGRect *)arg1 center:(struct CGPoint *)arg2;
- (void)_layoutActiveViewControllerView;
- (void)_layoutTiltedTabView;
- (double)_activeActorTopPadding;
- (double)_bottomShelfHeight;
- (struct CGRect)_activeViewControllerFrame;
- (double)_preferredWidthForActiveActorItem;
- (void)_setDimmingViewDimmed:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_updatePrimaryActorMaskProstrated:(_Bool)arg1 animated:(_Bool)arg2;
- (CDStruct_f4676b61)_primaryRadiiProstrated:(_Bool)arg1 atRest:(_Bool)arg2;
- (void)_setPrimaryViewProstrated:(_Bool)arg1 animated:(_Bool)arg2 force:(_Bool)arg3;
- (void)_setPrimaryViewProstrated:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_animate:(_Bool)arg1 sceneForActiveActorItem:(id)arg2;
- (id)undoManager;
- (_Bool)canBecomeFirstResponder;
- (_Bool)_secondaryActorItemsObscurePrimaryActorItem;
- (_Bool)_sideComposeSupportedWithBounds:(struct CGRect)arg1;
- (void)_setStatusBarStyle:(long long)arg1 animated:(_Bool)arg2;
- (_Bool)_useRegularSizeClassBehavior;
- (id)_additionalViewControllersToCheckForUserActivity;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)_applicationDidBecomeActive:(id)arg1;
- (void)_applicationDidEnterBackground:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)_layoutPrimaryComponents;
- (void)viewDidLoad;
- (id)initWithPrimaryViewController:(struct UIViewController *)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

