//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFAtomTextViewDelegate.h"

@class MFAtomTextView, NSString;

@protocol MFAtomTextViewDelegateInternal <MFAtomTextViewDelegate>
- (_Bool)_atomTextView:(MFAtomTextView *)arg1 shouldReplaceRepresentedObject:(id)arg2 replacementText:(NSString *)arg3;
@end

