//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CNUnknownContactsControllerDelegate.h"
#import "EKICSPreviewControllerDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UIPopoverPresentationControllerDelegate.h"

@class CNUnknownContactsController, EKICSPreviewController, MFRFC822AttachmentDataProvider, NSString, UIDocumentInteractionController, UIViewController;

@interface MFAttachmentShowcase : NSObject <CNUnknownContactsControllerDelegate, UIDocumentInteractionControllerDelegate, EKICSPreviewControllerDelegate, UIPopoverPresentationControllerDelegate>
{
    union {
        NSObject *_controller;
        EKICSPreviewController *_icsPreviewController;
        UIDocumentInteractionController *_uidic;
        CNUnknownContactsController *_vcardController;
    } _controller;
    MFRFC822AttachmentDataProvider *_rfc822DataProvider;
    id <UIDocumentInteractionControllerDelegate> _documentInteractionControllerDelegate;
    UIViewController *_presentingViewController;
    id <MFAttachmentShowcaseDelegate> _delegate;
}

+ (unsigned long long)displayTypeForAttachment:(id)arg1;
@property(nonatomic) id <MFAttachmentShowcaseDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
@property(nonatomic) __weak id <UIDocumentInteractionControllerDelegate> documentInteractionControllerDelegate; // @synthesize documentInteractionControllerDelegate=_documentInteractionControllerDelegate;
- (void).cxx_destruct;
- (void)icsPreviewControllerWantsDismissal:(id)arg1;
- (void)popoverPresentationControllerDidDismissPopover:(id)arg1;
- (void)unknownContactsControllerDidComplete:(id)arg1;
- (_Bool)unknownContactsController:(id)arg1 shouldPerformDefaultActionForContactProperty:(id)arg2;
- (id)documentInteractionControllerForAttachment:(id)arg1;
- (id)_rfc822AttachmentViewControllerForAttachment:(id)arg1;
- (_Bool)_queueProvisioningProfileAttachmentForAcceptance:(id)arg1 error:(out id *)arg2;
- (id)_eventPreviewControllerForICSAttachment:(id)arg1 managed:(_Bool)arg2 error:(out id *)arg3;
- (id)_controllerForVCardAttachment:(id)arg1;
- (void)_doneButtonTapped:(id)arg1;
- (void)finishedPresenting;
- (_Bool)presentAttachment:(id)arg1 showcaseInfo:(id)arg2 error:(out id *)arg3 delegate:(id)arg4;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

