//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CNAvatarView.h"

@class MFFuture;

@interface MFAvatarView : CNAvatarView
{
    MFFuture *_displayedContact;
}

@property(retain, nonatomic) MFFuture *displayedContact; // @synthesize displayedContact=_displayedContact;
- (void).cxx_destruct;
- (void)dealloc;
- (id)displayPersonForEmailAddress:(id)arg1 usingContactStore:(id)arg2;

@end

