//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@interface MFBridgeSettingsMailboxSelection : NSObject
{
    unsigned long long _inboxesFilterTypes;
    NSSet *_selectedMailboxes;
}

@property(retain, nonatomic) NSSet *selectedMailboxes; // @synthesize selectedMailboxes=_selectedMailboxes;
@property(nonatomic) unsigned long long inboxesFilterTypes; // @synthesize inboxesFilterTypes=_inboxesFilterTypes;
- (id)description;
- (void)dealloc;

@end

