//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_UINavigationBarTitleView.h"

#import "MFCollapsibleHeaderContentViewDelegate.h"

@class CADisplayLink, MFCollapsibleHeaderContentView, NSString, UILabel, UIScrollView;

@interface MFCollapsibleHeaderView : _UINavigationBarTitleView <MFCollapsibleHeaderContentViewDelegate>
{
    _Bool _titleDidChange;
    _Bool _collapsed;
    id <MFCollapsibleHeaderViewDelegate> _delegate;
    NSString *_title;
    NSString *_superTitle;
    MFCollapsibleHeaderContentView *_contentView;
    MFCollapsibleHeaderContentView *_collapsedContentView;
    UIScrollView *_hostScrollView;
    UILabel *_superTitleLabel;
    double _initialScrollPosition;
    CADisplayLink *_displayLink;
    double _previousProgress;
    double _currentProgress;
    double _targetProgress;
    double _xScale;
}

@property(nonatomic) double xScale; // @synthesize xScale=_xScale;
@property(nonatomic) double targetProgress; // @synthesize targetProgress=_targetProgress;
@property(nonatomic) double currentProgress; // @synthesize currentProgress=_currentProgress;
@property(nonatomic) double previousProgress; // @synthesize previousProgress=_previousProgress;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(nonatomic) double initialScrollPosition; // @synthesize initialScrollPosition=_initialScrollPosition;
@property(retain, nonatomic) UILabel *superTitleLabel; // @synthesize superTitleLabel=_superTitleLabel;
@property(nonatomic) UIScrollView *hostScrollView; // @synthesize hostScrollView=_hostScrollView;
@property(retain, nonatomic) MFCollapsibleHeaderContentView *collapsedContentView; // @synthesize collapsedContentView=_collapsedContentView;
@property(retain, nonatomic) MFCollapsibleHeaderContentView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic, getter=isCollapsed) _Bool collapsed; // @synthesize collapsed=_collapsed;
@property(copy, nonatomic) NSString *superTitle; // @synthesize superTitle=_superTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) __weak id <MFCollapsibleHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGAffineTransform)_transformForLocation:(long long)arg1;
- (void)transitionCompleted:(long long)arg1 willBeDisplayed:(_Bool)arg2;
- (void)performTransition:(long long)arg1 willBeDisplayed:(_Bool)arg2;
- (void)transitionWillBegin:(long long)arg1 willBeDisplayed:(_Bool)arg2;
- (void)contentDidChange;
- (void)layoutMarginsDidChange;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)contentViewDidCompleteTextLayout:(id)arg1;
- (void)contentView:(id)arg1 didLayoutWithContentHeight:(double)arg2;
@property(readonly, nonatomic) double contentHeight;
- (void)_displayLinkDidFire:(id)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)hostScrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)hostScrollViewDidScroll:(id)arg1;
- (void)hostScrollViewWillBeginDragging:(id)arg1;
- (void)setCollapsed:(_Bool)arg1 animated:(_Bool)arg2;
- (double)_maximumTravel;
- (void)layoutSubviews;
- (void)_updateHeightWithProgress:(double)arg1;
- (void)_updateAnchorPointForContentView:(id)arg1;
- (void)_pinContentViewsAroundText;
- (struct UIEdgeInsets)_contentInsetsWithExclusionRects:(id)arg1 wantsUniformHorizontalInsets:(_Bool)arg2;
- (void)_updateContentViewMargins;
- (void)setBounds:(struct CGRect)arg1;
- (double)_maximumSuperTitleWidthForViewBounds:(struct CGRect)arg1;
- (void)_updateSuperTitleLabelLayoutWithBounds:(struct CGRect)arg1;
- (void)_createPrimaryViews;
- (id)_collapsedFont;
- (id)_expandedFont;
- (void)_updateFontBasedAttributes;
- (void)_fontMetricCacheDidInvalidate:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

