//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MFConversationViewCellSizeTracker : NSObject
{
    NSMutableDictionary *_intrinsicCellSizes;
    id <MFConversationViewCellSizeTrackerDelegate> _delegate;
}

@property(nonatomic) id <MFConversationViewCellSizeTrackerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)resetCellSizesForCellsWithMessageIDs:(id)arg1;
- (void)resetAllCellSizes;
- (void)setIntrinsicSize:(struct CGSize)arg1 forCellWithMessageID:(id)arg2;
- (id)intrinsicSizesForCellsWithMessageIDs:(id)arg1;
- (struct CGSize)intrinsicSizeForCellWithMessageID:(id)arg1;
- (struct CGSize)displaySizeForCellWithMessageID:(id)arg1;
- (id)init;
- (void)dealloc;

@end

