//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMailMessage;

@interface MFConversationHandoffCoordinator : NSObject
{
    id <MFUserActivityProvider> _userActivityProvider;
    id <MFCurrentVisibleMessageStrategy> _currentVisibleMessageStrategy;
    MFMailMessage *_handoffMessage;
}

@property(retain, nonatomic) MFMailMessage *handoffMessage; // @synthesize handoffMessage=_handoffMessage;
@property(retain, nonatomic) id <MFCurrentVisibleMessageStrategy> currentVisibleMessageStrategy; // @synthesize currentVisibleMessageStrategy=_currentVisibleMessageStrategy;
@property(nonatomic) __weak id <MFUserActivityProvider> userActivityProvider; // @synthesize userActivityProvider=_userActivityProvider;
- (void).cxx_destruct;
- (void)_updateUserActivity:(id)arg1 withHandoffAvailabilityForMessage:(id)arg2;
- (void)_updateUserActivity:(id)arg1 withSearchableItemAttributeSetForMessage:(id)arg2;
- (id)_createUserActivity;
- (void)updateHandoffMessageBasedOnMessageVisibility;
- (void)updateUserActivityState;
- (void)dealloc;
- (id)initWithUserActivityProvider:(id)arg1 currentVisibleMessageStrategy:(id)arg2;

@end

