//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageHeaderViewBlock.h"

#import "CNAvatarViewDelegate.h"
#import "MFAddressAtomProvider.h"
#import "MFExpandableCaptionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class CNContactStore, MFAddressAtomStatusManager, MFAvatarView, MFExpandableCaptionView, MFModernLabelledAtomList, MessageViewStatusIndicatorManager, NSArray, NSLayoutConstraint, NSString, UIDateLabel, UILayoutGuide, UIStackView, UITapGestureRecognizer, UITextView;

@interface MFConversationItemHeaderBlock : MFMessageHeaderViewBlock <CNAvatarViewDelegate, MFExpandableCaptionViewDelegate, MFAddressAtomProvider, UIGestureRecognizerDelegate>
{
    unsigned long long _displayedMessageFlags;
    unsigned long long _displayedConversationFlags;
    _Bool _showDetails;
    CNContactStore *_contactStore;
    id <MFConversationItemHeaderBlockDelegate> _delegate;
    long long _displayOptions;
    MFModernLabelledAtomList *_primaryAtomList;
    UITextView *_subjectTextView;
    UIDateLabel *_timestampLabel;
    UIStackView *_primaryStackView;
    MFExpandableCaptionView *_captionView;
    MFAvatarView *_avatarView;
    UILayoutGuide *_statusIndicatorLayoutGuide;
    MessageViewStatusIndicatorManager *_statusIndicatorManager;
    NSLayoutConstraint *_firstBaselineConstraint;
    NSLayoutConstraint *_avatarBottomConstraint;
    NSLayoutConstraint *_toggleButtonFirstBaselineConstraint;
    NSLayoutConstraint *_toggleButtonTrailingConstraint;
    NSLayoutConstraint *_subjectTrailingConstraint;
    NSLayoutConstraint *_bottomConstraint;
    NSLayoutConstraint *_subjectTextViewTrailingConstraint;
    NSArray *_timestampLabelConstraints;
    UITapGestureRecognizer *_tapRecognizer;
}

@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(retain, nonatomic) NSArray *timestampLabelConstraints; // @synthesize timestampLabelConstraints=_timestampLabelConstraints;
@property(retain, nonatomic) NSLayoutConstraint *subjectTextViewTrailingConstraint; // @synthesize subjectTextViewTrailingConstraint=_subjectTextViewTrailingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *bottomConstraint; // @synthesize bottomConstraint=_bottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *subjectTrailingConstraint; // @synthesize subjectTrailingConstraint=_subjectTrailingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toggleButtonTrailingConstraint; // @synthesize toggleButtonTrailingConstraint=_toggleButtonTrailingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toggleButtonFirstBaselineConstraint; // @synthesize toggleButtonFirstBaselineConstraint=_toggleButtonFirstBaselineConstraint;
@property(retain, nonatomic) NSLayoutConstraint *avatarBottomConstraint; // @synthesize avatarBottomConstraint=_avatarBottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *firstBaselineConstraint; // @synthesize firstBaselineConstraint=_firstBaselineConstraint;
@property(retain, nonatomic) MessageViewStatusIndicatorManager *statusIndicatorManager; // @synthesize statusIndicatorManager=_statusIndicatorManager;
@property(retain, nonatomic) UILayoutGuide *statusIndicatorLayoutGuide; // @synthesize statusIndicatorLayoutGuide=_statusIndicatorLayoutGuide;
@property(retain, nonatomic) MFAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) MFExpandableCaptionView *captionView; // @synthesize captionView=_captionView;
@property(retain, nonatomic) UIStackView *primaryStackView; // @synthesize primaryStackView=_primaryStackView;
@property(retain, nonatomic) UIDateLabel *timestampLabel; // @synthesize timestampLabel=_timestampLabel;
@property(retain, nonatomic) UITextView *subjectTextView; // @synthesize subjectTextView=_subjectTextView;
@property(retain, nonatomic) MFModernLabelledAtomList *primaryAtomList; // @synthesize primaryAtomList=_primaryAtomList;
@property(nonatomic) long long displayOptions; // @synthesize displayOptions=_displayOptions;
@property(nonatomic) id <MFConversationItemHeaderBlockDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
- (id)_footnoteFont;
- (id)_subheadFont;
- (id)_headlineFont;
- (void)_updateFonts;
- (void)_tappedHeader:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)shouldDecorateAtomListWithSMIMEStatus:(id)arg1;
- (void)iterateDisplayedAtomListsWithBlock:(CDUnknownBlockType)arg1;
- (void)setSeparatorDrawsFlushWithTrailingEdge:(_Bool)arg1;
- (void)setSeparatorIsHidden:(_Bool)arg1;
- (void)_primaryAddressAtomWasTapped:(id)arg1;
- (void)expandableCaptionView:(id)arg1 didTapAtom:(id)arg2 forSender:(_Bool)arg3;
- (_Bool)_shouldDisplaySubjectWhenExpanded;
- (void)expandableCaptionView:(id)arg1 willBecomeExpanded:(_Bool)arg2 withAnimationCoordinator:(id)arg3;
- (id)expandableCaptionView:(id)arg1 displayNameForEmailAddress:(id)arg2 abbreviated:(_Bool)arg3;
- (void)_tearDownSubjectTextView;
- (void)_setUpSubjectTextView;
- (void)setShowsHeaderDetails:(_Bool)arg1 animated:(_Bool)arg2;
- (id)presentingViewControllerForAvatarView:(id)arg1;
- (void)setMessageFlags:(unsigned long long)arg1 conversationFlags:(unsigned long long)arg2;
- (void)_layoutStatusIndicatorsInRect:(struct CGRect)arg1;
- (void)_updateStatusIndicators;
- (void)_flagStyleDidChange:(id)arg1;
- (void)_updateTimestampLabels;
- (void)_updateDisplayedContact;
- (void)displayMessage:(id)arg1;
- (void)prepareForReuse;
- (void)traitCollectionDidChange:(id)arg1;
- (_Bool)_shouldShowSubject;
- (_Bool)_hasConversationLayout;
- (void)_updateSubjectText;
- (void)_updateSubjectVisibility;
- (void)_updateSubviewConstraints;
- (void)_updateAvatarConstraints;
- (void)_updateStyle;
- (void)layoutSubviews;
- (void)setDisplayMetrics:(id)arg1;
- (void)_updateStackViewSpacing;
- (void)updateConstraints;
- (void)initializePrimaryLayoutConstraints;
- (void)createPrimaryViews;
@property(readonly, nonatomic) MFAddressAtomStatusManager *atomManager;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 contactStore:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

