//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CNContactViewControllerDelegate.h"
#import "MFArrowControlsViewDelegate.h"
#import "MFCollapsibleHeaderViewDelegate.h"
#import "MFConversationCellConfiguratorDelegate.h"
#import "MFConversationViewCellSizeTrackerDelegate.h"
#import "MFConversationViewControllerDelegate.h"
#import "MFKeyCommandReacting.h"
#import "MFKeyboardAvoidable.h"
#import "MFMessageViewControllerDelegate.h"
#import "MFMoveToPredictionTriageInteractionDelegate.h"
#import "MFPassthroughViewProvider.h"
#import "MFPreviewable.h"
#import "MFSwipableCollectionViewLayoutDelegate.h"
#import "MFTransferStackControllerDelegate.h"
#import "MFUserActivityProvider.h"
#import "MessageMiniMallObserver.h"
#import "UICollectionViewDragDelegate_Private.h"
#import "UIGestureRecognizerDelegate.h"
#import "_MFConversationViewCollectionViewDelegate.h"

@class CNContactStore, LongPressableButtonItem, MFArrowControlsView, MFAttachmentManager, MFCancelationToken, MFCollapsibleHeaderView, MFCollectionViewPagingAnimator, MFConversationAssistantContextProvider, MFConversationCellConfigurator, MFConversationCellExpansionGestureRecognizer, MFConversationCurrentVisibleMessageStrategy, MFConversationHandoffCoordinator, MFConversationViewFlowLayout, MFConversationViewNavigationAnimationController, MFLazyCache, MFMailMessage, MFMailMessageLibrary, MFMessageDisplayMetrics, MFMessageViewControllerReuseQueue, MFPriorityLoadingQueue, MFSparseMutable64IndexSet, MFSwipableCollectionViewLayout, MFTextSelectionScrollHandler, MFTransferSplitViewController, MSMessageLoadingAnalyticController, MessageMiniMall, NSArray, NSIndexPath, NSMapTable, NSString, NSUserActivity, NoSelectedMessageView, UIBarButtonItem, UICollectionView, UIKeyCommand, UIPanGestureRecognizer, _MFConversationViewCollectionView, _MFConversationViewUpdateContext;

@interface MFConversationViewController : UIViewController <MFKeyboardAvoidable, MessageMiniMallObserver, MFMessageViewControllerDelegate, MFPreviewable, MFSwipableCollectionViewLayoutDelegate, UICollectionViewDragDelegate_Private, MFPassthroughViewProvider, CNContactViewControllerDelegate, MFArrowControlsViewDelegate, MFMoveToPredictionTriageInteractionDelegate, MFConversationViewControllerDelegate, MFKeyCommandReacting, MFTransferStackControllerDelegate, UIGestureRecognizerDelegate, MFConversationViewCellSizeTrackerDelegate, _MFConversationViewCollectionViewDelegate, MFCollapsibleHeaderViewDelegate, MFUserActivityProvider, MFConversationCellConfiguratorDelegate>
{
    MFLazyCache *_mostRecentAncestorCache;
    MFLazyCache *_displayNameCache;
    MFLazyCache *_loadingContextCache;
    MFPriorityLoadingQueue *_loadingContextQueue;
    NSMapTable *_delayedReadCancelables;
    MFSparseMutable64IndexSet *_disabledMarkAsReadMessageHashes;
    struct CGPoint _layoutInvalidationContentOffset;
    double _nextAvailableLoadMoreInterval;
    MFCollapsibleHeaderView *_conversationHeaderView;
    _MFConversationViewCollectionView *_conversationView;
    MFSwipableCollectionViewLayout *_defaultConversationLayout;
    MFConversationViewFlowLayout *_singleMessageLayout;
    MFConversationCellConfigurator *_cellConfigurator;
    _MFConversationViewUpdateContext *_currentUpdateContext;
    MFCollectionViewPagingAnimator *_pagingAnimator;
    NSArray *_defaultBarButtons;
    LongPressableButtonItem *_deleteButtonItem;
    UIBarButtonItem *_markButtonItem;
    UIBarButtonItem *_replyButtonItem;
    UIBarButtonItem *_transferButtonItem;
    UIBarButtonItem *_arrowControlsButtonItem;
    UIBarButtonItem *_leftSpaceItem;
    MFArrowControlsView *_arrowControlsView;
    NoSelectedMessageView *_noSelectedMessageView;
    UIKeyCommand *_keyCommands[12];
    double _adjustmentForKeyboard;
    UIPanGestureRecognizer *_popRecognizer;
    MFConversationCellExpansionGestureRecognizer *_cellExpansionRecognizer;
    NSArray *_messageSources;
    MFMessageViewControllerReuseQueue *_messageViewControllerReuseQueue;
    struct {
        unsigned int shouldShowToolbar:1;
        unsigned int shouldShowDisplayModeButton:1;
        unsigned int shouldShowNavigationArrows:1;
        unsigned int shouldShowArchiveButton:1;
        unsigned int scrollToReferenceMessageOnNextAppearance:1;
        unsigned int nextArrowPressAdvancesConversation:1;
        unsigned int isUpdatingSources:1;
        unsigned int userDidCollapseBottomPadding:1;
        unsigned int viewIsVisible:1;
        unsigned int includeRelatedMessages:1;
        unsigned int viewIsDisappearing:1;
        unsigned int isRotating:1;
        unsigned int wasBeingPreviewed:1;
    } _flags;
    _Bool _isBeingPreviewed;
    _Bool _isPrimary;
    _Bool _messagesShowSourceMailbox;
    _Bool _toolbarHidden;
    _Bool _shownAsConversation;
    _Bool _shouldShowNoMessageSelectedView;
    unsigned long long _conversationSortOrder;
    UIBarButtonItem *_doneButton;
    MessageMiniMall *_mall;
    MFMailMessage *_referenceMessage;
    MFConversationViewNavigationAnimationController *_animationController;
    id <MFConversationViewControllerDelegate> _delegate;
    CNContactStore *_contactStore;
    MFMessageDisplayMetrics *_displayMetrics;
    MFConversationHandoffCoordinator *_handoffCoordinator;
    NSIndexPath *_pinnedIndexPath;
    NSString *_conversationSubject;
    MFTransferSplitViewController *_transferController;
    id <MFMailboxPrediction> _mailboxPrediction;
    MFTextSelectionScrollHandler *_textSelectionScrollHandler;
    MFConversationAssistantContextProvider *_assistantContextProvider;
    MFConversationCurrentVisibleMessageStrategy *_currentVisibleMessageStrategy;
    UIBarButtonItem *_contactLeftDoneButton;
    NSIndexPath *_removedSingleMessageIndexPath;
    MSMessageLoadingAnalyticController *_messageLoadingAnalyticController;
    MFCancelationToken *_barButtonConnectivityCancelable;
    long long _resizingState;
    NSArray *_resizingContentViews;
    struct CGPoint _initialScrollOffset;
}

@property(copy, nonatomic) NSArray *resizingContentViews; // @synthesize resizingContentViews=_resizingContentViews;
@property(nonatomic) long long resizingState; // @synthesize resizingState=_resizingState;
@property(retain, nonatomic) MFCancelationToken *barButtonConnectivityCancelable; // @synthesize barButtonConnectivityCancelable=_barButtonConnectivityCancelable;
@property(retain, nonatomic) MSMessageLoadingAnalyticController *messageLoadingAnalyticController; // @synthesize messageLoadingAnalyticController=_messageLoadingAnalyticController;
@property(retain, nonatomic) NSIndexPath *removedSingleMessageIndexPath; // @synthesize removedSingleMessageIndexPath=_removedSingleMessageIndexPath;
@property(retain, nonatomic) UIBarButtonItem *contactLeftDoneButton; // @synthesize contactLeftDoneButton=_contactLeftDoneButton;
@property(retain, nonatomic) MFConversationCurrentVisibleMessageStrategy *currentVisibleMessageStrategy; // @synthesize currentVisibleMessageStrategy=_currentVisibleMessageStrategy;
@property(retain, nonatomic) MFConversationAssistantContextProvider *assistantContextProvider; // @synthesize assistantContextProvider=_assistantContextProvider;
@property(retain, nonatomic) MFTextSelectionScrollHandler *textSelectionScrollHandler; // @synthesize textSelectionScrollHandler=_textSelectionScrollHandler;
@property(retain, nonatomic) id <MFMailboxPrediction> mailboxPrediction; // @synthesize mailboxPrediction=_mailboxPrediction;
@property(retain, nonatomic) MFTransferSplitViewController *transferController; // @synthesize transferController=_transferController;
@property(nonatomic) _Bool shouldShowNoMessageSelectedView; // @synthesize shouldShowNoMessageSelectedView=_shouldShowNoMessageSelectedView;
@property(copy, nonatomic) NSString *conversationSubject; // @synthesize conversationSubject=_conversationSubject;
@property(retain, nonatomic) NSIndexPath *pinnedIndexPath; // @synthesize pinnedIndexPath=_pinnedIndexPath;
@property(retain, nonatomic) MFConversationHandoffCoordinator *handoffCoordinator; // @synthesize handoffCoordinator=_handoffCoordinator;
@property(retain, nonatomic) MFMessageDisplayMetrics *displayMetrics; // @synthesize displayMetrics=_displayMetrics;
@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(nonatomic) id <MFConversationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGPoint initialScrollOffset; // @synthesize initialScrollOffset=_initialScrollOffset;
@property(retain, nonatomic) MFConversationViewNavigationAnimationController *animationController; // @synthesize animationController=_animationController;
@property(retain, nonatomic) MFMailMessage *referenceMessage; // @synthesize referenceMessage=_referenceMessage;
@property(readonly, nonatomic) _Bool shownAsConversation; // @synthesize shownAsConversation=_shownAsConversation;
@property(retain, nonatomic) MessageMiniMall *mall; // @synthesize mall=_mall;
@property(nonatomic, getter=isToolbarHidden) _Bool toolbarHidden; // @synthesize toolbarHidden=_toolbarHidden;
@property(retain, nonatomic) UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(nonatomic) _Bool messagesShowSourceMailbox; // @synthesize messagesShowSourceMailbox=_messagesShowSourceMailbox;
@property(nonatomic) _Bool isPrimary; // @synthesize isPrimary=_isPrimary;
@property(nonatomic) unsigned long long conversationSortOrder; // @synthesize conversationSortOrder=_conversationSortOrder;
@property(retain, nonatomic) UIBarButtonItem *transferButtonItem; // @synthesize transferButtonItem=_transferButtonItem;
@property(nonatomic) _Bool isBeingPreviewed; // @synthesize isBeingPreviewed=_isBeingPreviewed;
- (id)messageDisplayMetricsForTraitCollection:(id)arg1 layoutMargins:(struct UIEdgeInsets)arg2;
- (void)_updateDisplayMetrics;
- (void)_toggleCellGroupOpacityIfNeeded:(id)arg1 displaying:(_Bool)arg2;
- (void)_toggleCellsGroupOpacityDuringRotationWithCoordinator:(id)arg1;
- (id)_dragItemsForItemAtIndexPath:(id)arg1;
- (id)collectionView:(id)arg1 itemsForAddingToDragSession:(id)arg2 atIndexPath:(id)arg3 point:(struct CGPoint)arg4;
- (id)collectionView:(id)arg1 itemsForBeginningDragSession:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 dragPreviewParametersForItemAtIndexPath:(id)arg2;
- (long long)_collectionView:(id)arg1 dataOwnerForDragSession:(id)arg2 atIndexPath:(id)arg3;
- (_Bool)wantsBarHidingWhenVerticallyCompact;
- (void)presentationController:(id)arg1 willPresentWithAdaptiveStyle:(long long)arg2 transitionCoordinator:(id)arg3;
- (struct CGPoint)initialScrollOffsetForTracker:(id)arg1;
- (_Bool)isDisplayingSingleMessageForTracker:(id)arg1;
- (double)_expectedCellWidth;
- (struct CGSize)defaultCellSizeForTracker:(id)arg1;
- (_Bool)conversationViewController:(id)arg1 canAdvanceToNextConversationWithDirection:(int)arg2;
- (void)conversationViewController:(id)arg1 advanceToNextConversationWithDirection:(int)arg2;
- (id)shrinkAnimationContainerViewForConversationViewController:(id)arg1;
- (id)titleForSingletonConversationViewController:(id)arg1;
- (void)conversationViewController:(id)arg1 willRemoveAllVisibleMessages:(id)arg2;
- (id)presentingViewControllerForTriageInteraction:(id)arg1;
- (void)_splitViewDisplayModeDidChange:(id)arg1;
- (void)_fontMetricCacheDidInvalidate:(id)arg1;
- (void)_invalidateDisplayNameCache;
- (void)_updateIncludeRelatedMessages;
- (void)_updateConversationSortOrder;
- (id)passthroughViews;
- (void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2;
- (id)_triageInteractionForTriageAction:(unsigned long long)arg1 withMessages:(id)arg2 indexPath:(id)arg3;
- (id)_swipeActionForTriageInteraction:(id)arg1;
- (id)swipableCollectionViewLayout:(id)arg1 trailingSwipeActionsForItemAtIndexPath:(id)arg2;
- (id)swipableCollectionViewLayout:(id)arg1 leadingSwipeActionsForItemAtIndexPath:(id)arg2;
- (void)swipableCollectionViewLayout:(id)arg1 willBeginSwipeAtIndexPath:(id)arg2;
- (void)_endEditingAnimated:(_Bool)arg1;
- (struct CGRect)_defaultSourceRectForView:(id)arg1;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_showModalViewController:(id)arg1 fromView:(id)arg2 sourceRect:(struct CGRect)arg3 animated:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)_dismissPopover;
- (void)_displayViewController:(id)arg1 fromAtom:(id)arg2 animated:(_Bool)arg3;
- (void)updateArrowControlsView;
- (void)arrowControlsView:(id)arg1 didTapButtonWithDirection:(int)arg2;
@property(readonly, nonatomic) MFArrowControlsView *arrowControlsView;
- (id)currentlySelectedMailMessageForStackViewController:(id)arg1;
- (id)snapshotViewOfCurrentlySelectedMailMessageForStackViewController:(id)arg1;
- (void)markButtonTapped:(id)arg1;
- (void)presentTransferUIWithMoveInteraction:(id)arg1 prediction:(id)arg2 fromViewController:(id)arg3;
- (void)moveButtonTapped:(id)arg1;
- (void)_shrinkMessagesToBarButton:(id)arg1 withInteraction:(id)arg2;
- (void)deleteButtonLongPressed:(id)arg1;
- (void)deleteButtonTapped:(id)arg1;
- (void)_testDeleteSelectedMessage;
- (void)_doDeleteSelectedMessagesAskingConfirmation:(_Bool)arg1 presentationSourceButtonItem:(id)arg2;
- (void)replyButtonTapped:(id)arg1;
- (void)_clearSelectedMessageContentForMessage:(id)arg1;
- (id)_getCurrentlySelectedMessageContentForMessage:(id)arg1;
- (id)_defaultBarButtonsWithFlexibleSpacing:(_Bool)arg1 reverseOrder:(_Bool)arg2;
- (id)_fixedSpaceBarButton;
- (id)_flexibleSpaceBarButton;
- (void)done:(id)arg1;
- (void)_updateBarButtonsEnabled;
- (void)_updateBarButtonsAnimated:(_Bool)arg1 withDisplayMode:(long long)arg2 force:(_Bool)arg3;
- (void)_updateBarButtonsAnimated:(_Bool)arg1 force:(_Bool)arg2;
- (_Bool)_shouldShowArrowsForDisplayMode:(long long)arg1;
- (_Bool)shouldArchiveByDefault;
- (void)_pageKeyCommandInvoked:(id)arg1;
- (void)_flagMessageKeyCommandInvoked:(id)arg1;
- (void)_markReadKeyCommandInvoked:(id)arg1;
- (void)_markAsJunkKeyCommandInvoked:(id)arg1;
- (void)_navigateMessageDownKeyCommandInvoked:(id)arg1;
- (void)_navigateMessageUpKeyCommandInvoked:(id)arg1;
- (void)_forwardShortcutInvoked:(id)arg1;
- (void)_replyShortcutInvoked:(id)arg1;
- (id)keyCommands;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2 targetMessage:(id)arg3;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (long long)_codeForKeyCommand:(id)arg1;
- (id)_keyCommandForCode:(long long)arg1;
- (void)keyboardAvoidance:(id)arg1 adjustForOverlap:(double)arg2;
- (id)transitionCoordinatorForKeyboardAvoidance:(id)arg1;
- (id)viewForKeyboardAvoidance:(id)arg1;
- (void)miniMallDidFinishSearch:(id)arg1;
- (void)miniMallFinishedFetch:(id)arg1;
- (void)miniMallStartFetch:(id)arg1;
- (void)miniMallGrowingMailboxesChanged:(id)arg1;
- (void)miniMallMessagesAtIndexPathsChanged:(id)arg1;
- (void)miniMallCurrentMessageRemoved:(id)arg1;
- (struct CGPoint)collectionView:(id)arg1 targetContentOffsetForProposedContentOffset:(struct CGPoint)arg2;
- (void)_hideRemovedSingleMessageCellIfInRemovedIndexPaths:(id)arg1;
- (void)miniMallMessageCountDidChange:(id)arg1;
- (void)miniMallMessageCountWillChange:(id)arg1;
- (void)miniMallDidLoadMessages:(id)arg1;
- (id)mf_suppressedApplicationContexts;
- (id)mf_currentApplicationContexts;
- (id)_oldestIndexPath;
- (id)_nextIndexPathToSelectFromIndexPath:(id)arg1 withDirection:(int)arg2;
- (id)_nextMessageIndexWithDirection:(int)arg1;
- (void)_scrollToReferenceMessage;
- (void)_preloadMessagesAdjacentToMessage:(id)arg1;
- (id)_messageLoadingContextForMessage:(id)arg1;
- (id)_cellForMessage:(id)arg1;
- (CDUnknownBlockType)priorityLoadingComparatorForPinnedMessage:(id)arg1;
- (_Bool)_shouldAutomaticallyCollapseQuotedContentForCellAtIndex:(unsigned long long)arg1;
- (id)indexSetForRowsFromIndexPaths:(id)arg1 section:(long long)arg2;
- (void)invalidateAutomaticMarkAsReadForAllMessages;
- (void)cancelAutomaticMarkAsReadForMessage:(id)arg1;
- (void)scheduleAutomaticMarkAsReadForMessage:(id)arg1;
- (void)disableAutomaticMarkAsReadForMessages:(id)arg1;
- (_Bool)_shouldAutomaticallyMarkAsReadMessage:(id)arg1;
- (id)hostScrollViewForCollapsibleHeader:(id)arg1;
- (void)messageViewController:(id)arg1 loadingIndicatorDidChangeVisibility:(_Bool)arg2;
- (id)presentingViewControllerForAttachmentShowcase:(id)arg1;
- (id)presentingViewControllerForMessageViewController:(id)arg1;
- (id)messageViewController:(id)arg1 displayNameForEmailAddress:(id)arg2 abbreviated:(_Bool)arg3;
- (void)messageViewController:(id)arg1 didChangeSelectedHTML:(id)arg2;
- (void)messageViewControllerDidTapAddressAtom:(id)arg1 contactViewController:(id)arg2;
- (void)messageViewControllerDidTapToExpand:(id)arg1;
- (void)messageViewController:(id)arg1 contentViewDidEndZoomingMessageWithOffset:(struct CGPoint)arg2;
- (id)_visibleIndexPathForMessageViewController:(id)arg1;
- (id)messageViewController:(id)arg1 mostRecentAncestorMessageForMessage:(id)arg2;
- (id)_mostRecentAncestorMessageForMessage:(id)arg1;
- (_Bool)_isDisplayingSingleMessage;
- (void)_showSingleMessage:(id)arg1 animationOffset:(struct CGPoint)arg2 initialScrollOffset:(struct CGPoint)arg3;
- (void)messageViewControllerDidTapRevealActionsButton:(id)arg1;
- (void)messageViewController:(id)arg1 didTapShowMoreAtCollapsedOffset:(struct CGPoint)arg2 expandedOffset:(struct CGPoint)arg3;
- (void)messageViewControllerDidDisplayContent:(id)arg1;
- (void)messageViewControllerDidFinishFirstPaint:(id)arg1;
- (void)messageViewController:(id)arg1 didFinishRenderingWithHeight:(double)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (long long)_headerDisplayOptionsForMessage:(id)arg1 displayedAsSingleMessage:(_Bool)arg2;
- (_Bool)_shouldShowMailboxForMessage:(id)arg1;
- (void)_setFlagsForMessage:(id)arg1 atIndexPath:(id)arg2 flagReceiver:(id)arg3;
- (void)_configureCell:(id)arg1 atIndexPath:(id)arg2 loadingContext:(id)arg3 collapseQuotedContent:(_Bool)arg4;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (double)_autoscrollAdjustment;
- (double)_minimumItemHeight;
- (double)_itemSpacing;
- (double)_minimumEdgePadding;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)_indexPathForReferenceMessage;
- (_Bool)_messageIsReferenceMessage:(id)arg1;
- (id)_messageAtIndexPath:(id)arg1;
- (void)cellConfigurator:(id)arg1 didInvalidateConfigurationForCellsAtIndexPaths:(id)arg2;
- (id)cellConfigurator:(id)arg1 messageIdAtIndexPath:(id)arg2;
- (_Bool)cellConfigurator:(id)arg1 messageAtIndexPathShouldBeExpanded:(id)arg2;
- (void)cellConfigurator:(id)arg1 didConfigureCell:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)_setBottomPadding:(double)arg1;
- (void)_updateBottomPaddingWithLastItemHeight:(double)arg1;
- (void)_updateBottomPadding;
- (void)_ensureSubjectViewLayoutIfNeeded;
- (id)_layoutAttributesForItemAtIndexPath:(id)arg1;
- (void)_scrollToItemAtIndexPath:(id)arg1 animated:(_Bool)arg2 pin:(_Bool)arg3;
- (void)_shrinkBottomPaddingIfNecessary;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_attemptLoadMissingMessages;
- (id)_indexPathForTopMostVisibleRow;
- (void)updateUserActivityState:(id)arg1;
- (void)_updateLayout;
- (void)_updateConversationHeaderViewLayoutMarginsWithSuperviewMargins:(struct NSDirectionalEdgeInsets)arg1;
- (void)_updateWallpaperBackgroundVisibility;
- (void)_updateBackground;
- (id)_visibleNavigationBar;
- (_Bool)_shouldShowConversationHeader;
- (void)_updateTitle;
- (void)_updateEverything;
- (void)previewNewIndicatorForMessage:(id)arg1 triageAction:(unsigned long long)arg2;
- (void)_testReplyForSelectedMessage;
@property(readonly, nonatomic) MFMailMessage *targetMessageForBarButtonTriage;
- (id)_messagesForBarButtonTriage;
- (id)_allMessages;
- (void)_updateMallComparatorWithSortOrder:(unsigned long long)arg1;
@property(readonly, nonatomic) MFAttachmentManager *attachmentManager;
@property(readonly, nonatomic) MFMailMessageLibrary *library;
@property(readonly, nonatomic) MFMailMessage *focusedMessage;
- (void)setReferenceMessage:(id)arg1 showAsConversation:(_Bool)arg2 messageSources:(id)arg3 animated:(_Bool)arg4;
- (void)_doSetShouldShowNoMessageSelectedView:(_Bool)arg1;
- (void)_resetLoadingContext;
- (void)_updateSources;
- (CDUnknownBlockType)_duplicatePreferenceComparator;
- (id)_sourceForSingleMessage:(id)arg1;
- (void)_endUpdatingSources;
- (void)_beginUpdatingSources;
- (id)_previewActionForTriageAction:(unsigned long long)arg1 withMessages:(id)arg2 forSwipe:(_Bool)arg3;
- (id)_previewActionsForTriageActions:(id)arg1 excludingActions:(id)arg2;
- (id)trailingPreviewAction;
- (id)leadingPreviewAction;
- (id)previewActionItems;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidMoveToWindow:(id)arg1 shouldAppearOrDisappear:(_Bool)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)_updateCollectionViewMargins;
- (struct NSDirectionalEdgeInsets)layoutMarginsForCollectionViewFrame:(struct CGRect)arg1;
- (void)collectionViewMarginsDidChange:(struct NSDirectionalEdgeInsets)arg1;
- (void)viewDidLayoutSubviews;
- (void)endResizing;
- (void)beginResizing;
- (void)prepareForResizing;
- (void)_enumerateExpandedCellMessageContentViewsWithBlock:(CDUnknownBlockType)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(readonly, nonatomic) UICollectionView *collectionView;
- (void)dealloc;
- (void)_didRecognizeScreenEdgeGesture:(id)arg1;
- (void)popGestureDidRecognize:(id)arg1;
- (id)_currentSizeMetadataKey;
- (struct CGSize)cellConfigurator:(id)arg1 animationOffsetForExpandingCellAtIndexPath:(id)arg2;
- (double)cellConfigurator:(id)arg1 targetHeightForExpandingCellAtIndexPath:(id)arg2;
- (void)_expansionRecognizerDidRecognize:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)cellConfigurator;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSUserActivity *userActivity; // @dynamic userActivity;

@end

