//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NSLayoutManagerDelegate.h"
#import "UITextViewDelegate.h"

@class NSString, UITextView;

@interface MFCollapsibleHeaderContentView : UIView <UITextViewDelegate, NSLayoutManagerDelegate>
{
    struct CGPoint _firstCharacterPosition;
    double _fontCapHeight;
    double _lastBaselineY;
    _Bool _isPrimary;
    id <MFCollapsibleHeaderContentViewDelegate> _delegate;
    double _topToFirstBaseline;
    double _lastBaselineToBottom;
    double _contentWidth;
    unsigned long long _textAlignment;
    UITextView *_textView;
}

@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(nonatomic) unsigned long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(nonatomic) _Bool isPrimary; // @synthesize isPrimary=_isPrimary;
@property(nonatomic) double contentWidth; // @synthesize contentWidth=_contentWidth;
@property(nonatomic) double lastBaselineToBottom; // @synthesize lastBaselineToBottom=_lastBaselineToBottom;
@property(nonatomic) double topToFirstBaseline; // @synthesize topToFirstBaseline=_topToFirstBaseline;
@property(nonatomic) __weak id <MFCollapsibleHeaderContentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)fontCapHeight;
- (double)widthOfCharactersInRange:(struct _NSRange)arg1;
- (unsigned long long)indexOfCharacterAtTruncationOrBreakPoint;
- (struct CGPoint)firstCharacterPosition;
- (void)_invalidateCachedMetrics;
- (void)layoutManager:(id)arg1 didCompleteLayoutForTextContainer:(id)arg2 atEnd:(_Bool)arg3;
- (_Bool)_textViewIsNotEmpty;
@property(nonatomic) unsigned long long numberOfLines;
- (void)setFont:(id)arg1;
- (void)reflow;
- (void)setText:(id)arg1;
- (long long)_automaticTextAlignmentForText:(id)arg1;
- (void)_updateTextAlignmentForText:(id)arg1;
- (void)layoutMarginsDidChange;
- (void)setBounds:(struct CGRect)arg1;
- (void)_createPrimaryViews;
- (void)clearSelection;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

