//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFConversationViewController, MFMailMessage, NSSet, NSString, UIView;

@protocol MFConversationViewControllerDelegate <NSObject>
- (void)conversationViewController:(MFConversationViewController *)arg1 advanceToNextConversationWithDirection:(int)arg2;
- (_Bool)conversationViewController:(MFConversationViewController *)arg1 canAdvanceToNextConversationWithDirection:(int)arg2;

@optional
- (_Bool)canUpdateBackgroundWallpaperVisibilityForConversationViewController:(MFConversationViewController *)arg1;
- (NSSet *)currentAlertContextsForConversationViewController:(MFConversationViewController *)arg1;
- (void)didOrbOnMessageInConversationViewController:(MFConversationViewController *)arg1;
- (void)selectInitialMessageForConversationViewController:(MFConversationViewController *)arg1;
- (UIView *)shrinkAnimationContainerViewForConversationViewController:(MFConversationViewController *)arg1;
- (NSString *)titleForSingletonConversationViewController:(MFConversationViewController *)arg1;
- (NSSet *)conversationViewController:(MFConversationViewController *)arg1 messagesToActOnForReferenceMessage:(MFMailMessage *)arg2;
- (void)conversationViewController:(MFConversationViewController *)arg1 didRemoveAllVisibleMessages:(NSSet *)arg2;
- (void)conversationViewController:(MFConversationViewController *)arg1 willRemoveAllVisibleMessages:(NSSet *)arg2;
@end

