//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFConversationViewCellSizeTracker, UICollectionView;

@protocol MFConversationViewCellSizeTrackerDelegate <NSObject>
- (struct CGPoint)initialScrollOffsetForTracker:(MFConversationViewCellSizeTracker *)arg1;
- (_Bool)isDisplayingSingleMessageForTracker:(MFConversationViewCellSizeTracker *)arg1;
- (struct CGSize)defaultCellSizeForTracker:(MFConversationViewCellSizeTracker *)arg1;
- (UICollectionView *)collectionView;
@end

