//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFConversationViewCell.h"

#import "MBLSingleMessageClient.h"

@class MFAvatarView, MFVibrantCardView, MessageViewStatusIndicatorManager, NSString, UIDateLabel, UILabel;

@interface MFCollapsedMessageCell : MFConversationViewCell <MBLSingleMessageClient>
{
    MFVibrantCardView *_cellBackgroundView;
    UILabel *_senderLabel;
    UILabel *_summaryLabel;
    UIDateLabel *_timestampLabel;
    MFAvatarView *_avatarView;
    MessageViewStatusIndicatorManager *_statusIndicatorManager;
    unsigned long long _displayedConversationFlags;
    unsigned long long _displayedMessageFlags;
    unsigned long long _numberOfLoadAttempts;
}

+ (id)_highlightedBackgroundColor;
+ (double)defaultHeightWithDisplayMetrics:(id)arg1;
@property(nonatomic) unsigned long long numberOfLoadAttempts; // @synthesize numberOfLoadAttempts=_numberOfLoadAttempts;
@property(nonatomic) unsigned long long displayedMessageFlags; // @synthesize displayedMessageFlags=_displayedMessageFlags;
@property(nonatomic) unsigned long long displayedConversationFlags; // @synthesize displayedConversationFlags=_displayedConversationFlags;
@property(retain, nonatomic) MessageViewStatusIndicatorManager *statusIndicatorManager; // @synthesize statusIndicatorManager=_statusIndicatorManager;
@property(retain, nonatomic) MFAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UIDateLabel *timestampLabel; // @synthesize timestampLabel=_timestampLabel;
@property(retain, nonatomic) UILabel *summaryLabel; // @synthesize summaryLabel=_summaryLabel;
@property(retain, nonatomic) UILabel *senderLabel; // @synthesize senderLabel=_senderLabel;
@property(retain, nonatomic) MFVibrantCardView *cellBackgroundView; // @synthesize cellBackgroundView=_cellBackgroundView;
- (void).cxx_destruct;
- (void)_cancelBodyLoad;
- (void)_requestMessageBody;
- (void)notifyContentsUnavailableForMessage:(id)arg1 error:(id)arg2;
- (void)notifyContentsAvailable:(id)arg1 forMessage:(id)arg2;
- (id)_bodyLoader;
- (_Bool)wantsContentsOfType:(int)arg1;
- (id)message;
- (double)ordering;
- (long long)priority;
- (void)setHighlighted:(_Bool)arg1;
- (void)setMessageFlags:(unsigned long long)arg1 conversationFlags:(unsigned long long)arg2;
- (void)_updateSummaryDidCompleteLoad:(_Bool)arg1;
- (void)_updateForMessageLoadingContextChange;
- (void)setMessageLoadingContext:(id)arg1;
- (void)_updateSummaryNumberOfLines;
- (void)_updateFonts;
- (void)_fontMetricCacheDidInvalidate:(id)arg1;
- (void)_applyVibrancy:(_Bool)arg1 toLabel:(id)arg2;
- (void)_updateStatusIndicators;
- (void)layoutSubviews;
- (void)_displayMetricsDidChange;
- (void)_createPrimaryViews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

