//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFCollapsibleHeaderContentView;

@protocol MFCollapsibleHeaderContentViewDelegate <NSObject>
- (void)contentViewDidCompleteTextLayout:(MFCollapsibleHeaderContentView *)arg1;
- (void)contentView:(MFCollapsibleHeaderContentView *)arg1 didLayoutWithContentHeight:(double)arg2;
@end

