//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MFConversationViewCellExpansionTracker : NSObject
{
    id <MFConversationViewCellExpansionTrackerDelegate> _delegate;
    NSMutableDictionary *_expansionRecord;
}

+ (_Bool)allowsCollapsing;
@property(retain, nonatomic) NSMutableDictionary *expansionRecord; // @synthesize expansionRecord=_expansionRecord;
@property(nonatomic) __weak id <MFConversationViewCellExpansionTrackerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)resetRecord;
- (void)setMessageWithID:(id)arg1 expanded:(_Bool)arg2;
- (long long)expansionStatusForCellWithMessageID:(id)arg1;
- (void)_updateCollapsingAllowed;
- (id)initWithDelegate:(id)arg1;

@end

