//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class CNContactStore, MFMailMessage, MFMessageDisplayMetrics, MFMessageLoadingContext, UIView;

@interface MFConversationViewCell : UICollectionViewCell
{
    _Bool _roundsCellCorners;
    UIView *_contentWrapperView;
    MFMessageLoadingContext *_messageLoadingContext;
    MFMessageDisplayMetrics *_displayMetrics;
    CNContactStore *_contactStore;
}

+ (double)defaultCornerRadius;
@property(nonatomic) _Bool roundsCellCorners; // @synthesize roundsCellCorners=_roundsCellCorners;
@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(retain, nonatomic) MFMessageDisplayMetrics *displayMetrics; // @synthesize displayMetrics=_displayMetrics;
@property(retain, nonatomic) MFMessageLoadingContext *messageLoadingContext; // @synthesize messageLoadingContext=_messageLoadingContext;
@property(retain, nonatomic) UIView *contentWrapperView; // @synthesize contentWrapperView=_contentWrapperView;
- (void).cxx_destruct;
@property(readonly, nonatomic) MFMailMessage *message;
- (id)description;
- (_Bool)canBeginDragWithTouchAtPoint:(struct CGPoint)arg1;
- (_Bool)_disableRasterizeInAnimations;
- (void)prepareForReuse;
- (void)applyLayoutAttributes:(id)arg1;
- (void)layoutMarginsDidChange;
- (void)_displayMetricsDidChange;
@property(readonly, nonatomic, getter=isEligibleForAutomaticallyMarkingAsRead) _Bool eligibleForAutomaticallyMarkingAsRead;
- (void)setMessageFlags:(unsigned long long)arg1 conversationFlags:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

