//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MFMessageDisplayMetrics, NSString, UIButton;

@interface MFConversationItemFooterView : UIView
{
    id <MFMessageFooterViewDelegate> _delegate;
    UIButton *_seeMoreButton;
    UIButton *_revealActionsButton;
    NSString *_senderName;
    MFMessageDisplayMetrics *_displayMetrics;
}

+ (id)nameFont;
+ (id)prefixFont;
@property(retain, nonatomic) MFMessageDisplayMetrics *displayMetrics; // @synthesize displayMetrics=_displayMetrics;
@property(copy, nonatomic) NSString *senderName; // @synthesize senderName=_senderName;
@property(retain, nonatomic) UIButton *revealActionsButton; // @synthesize revealActionsButton=_revealActionsButton;
@property(retain, nonatomic) UIButton *seeMoreButton; // @synthesize seeMoreButton=_seeMoreButton;
@property(nonatomic) __weak id <MFMessageFooterViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_attributedButtonTitleWithSenderName:(id)arg1;
- (void)_fontMetricCacheDidInvalidate:(id)arg1;
- (void)_updateIcon;
- (void)_updateAttributedTitle;
- (void)layoutSeeMoreButton;
- (void)layoutActionButtonWithBounds:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)hideAttribution;
- (void)showAttributionWithSenderName:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)render:(id)arg1;

@end

