//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageHeaderViewBlockDelegate.h"

@class MFConversationItemHeaderBlock, MFModernAddressAtom, NSString, UIViewController;

@protocol MFConversationItemHeaderBlockDelegate <MFMessageHeaderViewBlockDelegate>
- (NSString *)conversationItemHeader:(MFConversationItemHeaderBlock *)arg1 displayNameForEmailAddress:(NSString *)arg2 abbreviated:(_Bool)arg3;
- (void)conversationItemHeaderWasTapped:(MFConversationItemHeaderBlock *)arg1;
- (UIViewController *)viewControllerForPresentationsFromConversationItemHeader:(MFConversationItemHeaderBlock *)arg1;

@optional
- (void)conversationItemHeader:(MFConversationItemHeaderBlock *)arg1 didSelectAddressAtom:(MFModernAddressAtom *)arg2 forSender:(_Bool)arg3;
@end

