//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFXPCServer.h"

#import "MSDDebugGathererProtocol.h"

@class NSString;

@interface MFDDebugGatherer : MFXPCServer <MSDDebugGathererProtocol>
{
}

+ (id)exportedInterface;
- (void)gatherDebugDiagnostics:(unsigned long long)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)_diagnosticsDump;
- (id)_rawSourceForCurrentEmail;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

