//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFDestructiveTriageInteraction.h"

@interface MFDeleteTriageInteraction : MFDestructiveTriageInteraction
{
}

+ (unsigned long long)deleteOrArchive;
- (_Bool)isDestructive;
- (id)_iconImageName;
- (id)color;
- (id)shortTitle;
- (id)title;
- (_Bool)_movesToTrash;
- (long long)_preferredAlertActionStyle;
- (_Bool)_requiresConfirmationPrompt;

@end

