//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MFDestructiveTriageInteractionFactory : NSObject
{
}

+ (id)interactionWithMessages:(id)arg1 mall:(id)arg2 deleteOrArchive:(unsigned long long)arg3;

@end

