//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFXPCServer.h"

#import "MSDFetchProtocol.h"

@class MFMailboxUid, NSString;

@interface MFDFetch : MFXPCServer <MSDFetchProtocol>
{
    CDUnknownBlockType _completionAfterFetchCompleted;
    MFMailboxUid *_waitingForMailbox;
}

+ (id)exportedInterface;
- (void)fetchMessagesForMailboxWithName:(id)arg1 options:(long long)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)_autoFetchCompleted:(id)arg1;
- (void)_waitForFetchCompletedForMailbox:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (_Bool)_isWaitingForMailboxFetch;
- (id)_findMailboxWithName:(id)arg1 inAccounts:(id)arg2;
- (id)_mailboxWithName:(id)arg1 forAccount:(id)arg2;
- (void)dealloc;
- (id)initWithClient:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

