//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MailboxContentViewCell, NSIndexPath, UITableView;

@protocol MFDisclosureSelectionTableViewDelegate <NSObject>
- (_Bool)tableView:(UITableView *)arg1 cell:(MailboxContentViewCell *)arg2 didSelectDisclosureButtonInRowAtIndexPath:(NSIndexPath *)arg3;
@end

