//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFDiskFreeSpaceMonitor.h"

@class NSLock, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString;

@interface MFDiskFreeSpaceMonitor : NSObject <MFDiskFreeSpaceMonitor>
{
    NSObject<OS_dispatch_queue> *_freeSpaceStatusQueue;
    NSObject<OS_dispatch_source> *_freeSpaceStatusTimerSource;
    NSLock *_freeSpaceStatusLock;
    unsigned long long _freeSpaceStatus;
}

+ (id)defaultMonitor;
- (void).cxx_destruct;
- (void)handleDidPurgeSpace:(id)arg1;
@property(readonly, nonatomic) _Bool hasAdequateFreeSpace;
@property(readonly, nonatomic) _Bool isFreeSpaceCritical;
- (void)getFreeSpaceStatusWithCompletionHandler:(CDUnknownBlockType)arg1;
- (unsigned long long)_retrieveFreeSpaceStatus:(id *)arg1;
@property(nonatomic) unsigned long long freeSpaceStatus; // @synthesize freeSpaceStatus=_freeSpaceStatus;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

