//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol MFDiskFreeSpaceMonitor <NSObject>
@property(readonly, nonatomic) _Bool hasAdequateFreeSpace;
@property(readonly, nonatomic) _Bool isFreeSpaceCritical;
@property(readonly, nonatomic) unsigned long long freeSpaceStatus;
- (void)getFreeSpaceStatusWithCompletionHandler:(void (^)(unsigned long long, NSError *))arg1;
@end

