//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSDiagnosticManager.h"

@interface MFDiagnostic : MSDiagnosticManager
{
}

+ (id)sharedManager;
- (_Bool)submitMailMessageDisplayErrorReport:(id)arg1;
- (void)submitMailCannotGetMailError:(id)arg1 forAccount:(id)arg2 submitNetworkDiags:(_Bool)arg3;
- (void)submitMailCannotGetMailErrorDueToErrorDomainCode:(int)arg1 submitNetworkDiags:(_Bool)arg2;
- (void)submitMailCannotGetMailErrorDueToMailErrorCode:(int)arg1 submitNetworkDiags:(_Bool)arg2;
- (void)submitMailCannotGetMailErrorForHostname:(id)arg1 protocol:(int)arg2 emailProvider:(int)arg3 mfErrorDomainCode:(int)arg4 submitNetworkDiags:(_Bool)arg5;
- (void)submitMailCannotGetMailErrorForHostname:(id)arg1 protocol:(int)arg2 emailProvider:(int)arg3 mailError:(id)arg4 submitNetworkDiags:(_Bool)arg5;
- (id)mailErrorFromErrorDomainCode:(int)arg1;
- (int)mailErrorReportProviderFromAccount:(id)arg1;
- (int)mailErrorReportProtocolFromAccount:(id)arg1;
- (id)_statisticsKindFromAccount:(id)arg1;
- (int)mailErrorReportProtocolFromAccountStatisticsKind:(id)arg1;
- (int)mailErrorCodeFromErrorDomainCode:(int)arg1;
- (void)submitMailNetworkDiagnosticsReport;
- (void)registerMetrics;
- (id)init;

@end

