//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFXPCServer.h"

#import "MSDVIPServicesProtocol.h"

@class NSString;

@interface MFDVIPServices : MFXPCServer <MSDVIPServicesProtocol>
{
}

+ (id)exportedInterface;
+ (id)_sharedInstance;
- (void)deleteVIPSenderWithIdentifier:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)saveVIPSender:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)allVIPSendersWithCompletion:(CDUnknownBlockType)arg1;
- (void)orderedVIPAddressesAndUnreadCountsWithCompletion:(CDUnknownBlockType)arg1;
- (id)_allVIPDictionaries;
- (id)_vipFromDictionary:(id)arg1;
- (id)_dictionaryFromVIP:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

