//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMailMessage, MMRowsChangedContext, NSIndexPath, NSNotification, NSSet, UITableView;

@protocol MFExpandedMessageCollectionStrategy <NSObject>
- (NSIndexPath *)indexPathOfLastMessageForCollectionContainingMessage:(id <MFBaseMessage>)arg1;
- (NSIndexPath *)indexPathOfRootMessageForCollectionContainingMessage:(id <MFBaseMessage>)arg1;
- (NSSet *)expandedIndexPathsForRootIndexPath:(NSIndexPath *)arg1;
- (NSIndexPath *)rootOrUnexpandedIndexPathForIndexPath:(NSIndexPath *)arg1;
- (_Bool)isExpandedIndexPath:(NSIndexPath *)arg1;
- (_Bool)isRootIndexPath:(NSIndexPath *)arg1;
- (_Bool)shouldArchiveByDefaultForTableIndexPath:(NSIndexPath *)arg1;
- (_Bool)needsSeparatorForIndexPath:(NSIndexPath *)arg1;
- (_Bool)hasExpandedCollectionContainingMessage:(MFMailMessage *)arg1;
- (long long)numberOfSections;
- (long long)numberOfRowsInSection:(long long)arg1;
- (void)reloadExpandedCollections;
- (void)resetExpandedCollections;
- (void)collapseAllExpandedCollectionsInTableView:(UITableView *)arg1;
- (void)collapseCollectionAtIndexPath:(NSIndexPath *)arg1;
- (_Bool)toggleCollectionAtIndexPath:(NSIndexPath *)arg1;
- (_Bool)canAdvanceToNextMessageFromMessage:(MFMailMessage *)arg1 withDirection:(int)arg2;
- (MFMailMessage *)messageToSelectFromMessage:(MFMailMessage *)arg1 withDirection:(int)arg2 currentIndexPath:(NSIndexPath *)arg3 showAsConversation:(out _Bool *)arg4;
- (MMRowsChangedContext *)cascadeMiniMallMessageCountDidChange:(NSNotification *)arg1;
- (MFMailMessage *)messageToSelectAfterDeletedMessage:(MFMailMessage *)arg1;
- (NSSet *)messageInfosAtTableIndexPath:(NSIndexPath *)arg1;
- (NSIndexPath *)tableIndexPathOfMessage:(id <MFBaseMessage>)arg1;
- (NSSet *)messagesAtTableIndexPath:(NSIndexPath *)arg1;
- (MFMailMessage *)messageAtTableIndexPath:(NSIndexPath *)arg1;
- (void)updateEntry:(id <MailboxContentTableEntry>)arg1 atTableIndexPath:(NSIndexPath *)arg2 addressList:(id *)arg3 options:(unsigned long long)arg4;
@end

