//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMMessagesChangedContext, MMRowsChangedContext;

@protocol MFExpandedMessageCollectionStrategyDelegate <NSObject>
- (void)messageCollectionStrategy:(id <MFExpandedMessageCollectionStrategy>)arg1 messagesAtIndexPathsChanged:(MMMessagesChangedContext *)arg2;
- (void)messageCollectionStrategy:(id <MFExpandedMessageCollectionStrategy>)arg1 messageCountDidChange:(MMRowsChangedContext *)arg2;
@end

