//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFExpandableCaptionView, MFModernAddressAtom, MFSimpleAnimationCoordinator, NSString;

@protocol MFExpandableCaptionViewDelegate <NSObject>
- (NSString *)expandableCaptionView:(MFExpandableCaptionView *)arg1 displayNameForEmailAddress:(NSString *)arg2 abbreviated:(_Bool)arg3;

@optional
- (void)expandableCaptionView:(MFExpandableCaptionView *)arg1 didTapAtom:(MFModernAddressAtom *)arg2 forSender:(_Bool)arg3;
- (void)expandableCaptionView:(MFExpandableCaptionView *)arg1 willBecomeExpanded:(_Bool)arg2 withAnimationCoordinator:(MFSimpleAnimationCoordinator *)arg3;
@end

