//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFCancelationToken, MFInvocationQueue, NSArray, NSCountedSet, NSMutableSet, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSSet, NSString;

@interface MFFetchProcessor : NSObject
{
    NSCountedSet *_mailboxFetchCounts;
    MFInvocationQueue *_workQueue;
    NSObject<OS_dispatch_queue> *_stateQueue;
    NSObject<OS_dispatch_semaphore> *_finishedProcessing;
    NSObject<OS_dispatch_semaphore> *_requestLimiter;
    unsigned long long _requestLimiterLimit;
    unsigned long long _runningRequests;
    NSMutableSet *_currentInvocations;
    NSMutableSet *_failedMailboxes;
    double _stopTime;
    MFCancelationToken *_cancelationToken;
    _Bool _loadMessageBodies;
    _Bool _includePushedMailboxes;
    _Bool _includeFavoritesMailboxes;
    _Bool _useMailboxFrecencyRanking;
    NSString *_name;
    NSSet *_accounts;
    long long _accountMailboxesBatchSize;
    long long _lastFetchDateCutoff;
    unsigned long long _loadNumOlderMessages;
    NSArray *_excludedMailboxTypes;
    id <MFActivityCondition> _condition;
}

+ (id)intelligentSkeletonFetchProcessor;
+ (id)powernapProcessor;
+ (id)processorWithName:(id)arg1 condition:(id)arg2;
+ (void)initialize;
@property(retain, nonatomic) id <MFActivityCondition> condition; // @synthesize condition=_condition;
@property(copy, nonatomic) NSArray *excludedMailboxTypes; // @synthesize excludedMailboxTypes=_excludedMailboxTypes;
@property(nonatomic) _Bool useMailboxFrecencyRanking; // @synthesize useMailboxFrecencyRanking=_useMailboxFrecencyRanking;
@property(nonatomic) _Bool includeFavoritesMailboxes; // @synthesize includeFavoritesMailboxes=_includeFavoritesMailboxes;
@property(nonatomic) _Bool includePushedMailboxes; // @synthesize includePushedMailboxes=_includePushedMailboxes;
@property(nonatomic) _Bool loadMessageBodies; // @synthesize loadMessageBodies=_loadMessageBodies;
@property(nonatomic) unsigned long long loadNumOlderMessages; // @synthesize loadNumOlderMessages=_loadNumOlderMessages;
@property(nonatomic) long long lastFetchDateCutoff; // @synthesize lastFetchDateCutoff=_lastFetchDateCutoff;
@property(nonatomic) long long accountMailboxesBatchSize; // @synthesize accountMailboxesBatchSize=_accountMailboxesBatchSize;
@property(copy, nonatomic) NSSet *accounts; // @synthesize accounts=_accounts;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (id)_mailboxesToFetch;
- (id)_accountsExcludingBlacklistedHostnames;
- (void)_fetchCompleted:(id)arg1;
- (void)_finishRequest;
- (void)_cancelCurrentInvocations;
- (id)_observeChangesInConditions;
- (_Bool)_processEligibleMailboxesAndWait;
- (_Bool)_runSynchronously:(long long)arg1;
- (_Bool)runSynchronouslyWithDuration:(double)arg1;
- (_Bool)runSynchronously;
- (void)_setRequestLimiterLimit:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1 condition:(id)arg2;

@end

