//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFFlagChangeTriageInteraction.h"

@interface MFFlagTriageInteraction : MFFlagChangeTriageInteraction
{
}

- (id)_iconImageName;
- (id)color;
- (id)shortTitle;
- (id)title;
- (unsigned long long)messageStateFlag;
- (void)_performInteraction_Internal;

@end

