//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerInteractiveTransitioning.h"

@class MFExpandedMessageCell, NSString, UINavigationBar, UIView, _MFConversationTransitionWrapperView;

@interface MFInteractiveMessageDismissalTransition : NSObject <UIViewControllerInteractiveTransitioning>
{
    _MFConversationTransitionWrapperView *_transitionView;
    UIView *_navBarTransitionView;
    UIView *_fromView;
    struct CGRect _toFrame;
    struct CGRect _fromFrame;
    UINavigationBar *_navBar;
    double _percentComplete;
    double _rangeOfMotion;
    double _targetScale;
    MFExpandedMessageCell *_conversationCell;
    id <UIViewControllerContextTransitioning> _transitionContext;
    struct CGPoint _translation;
    struct CGPoint _velocity;
}

@property(retain, nonatomic) id <UIViewControllerContextTransitioning> transitionContext; // @synthesize transitionContext=_transitionContext;
@property(retain, nonatomic) MFExpandedMessageCell *conversationCell; // @synthesize conversationCell=_conversationCell;
@property(nonatomic) struct CGPoint velocity; // @synthesize velocity=_velocity;
@property(nonatomic) struct CGPoint translation; // @synthesize translation=_translation;
@property(readonly, nonatomic) double rangeOfMotion; // @synthesize rangeOfMotion=_rangeOfMotion;
@property(readonly, nonatomic) double percentComplete; // @synthesize percentComplete=_percentComplete;
- (void)_completeTransitionAnimationCancelled:(_Bool)arg1;
- (void)finishInteractiveTransition;
- (void)cancelInteractiveTransition;
- (void)updateInteractiveTransition:(double)arg1;
- (void)startInteractiveTransition:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, nonatomic) long long completionCurve;
@property(readonly, nonatomic) double completionSpeed;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) _Bool wantsInteractiveStart;

@end

