//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFFlagChangeTriageInteraction.h"

@interface MFJunkTriageInteraction : MFFlagChangeTriageInteraction
{
}

- (id)color;
- (id)shortTitle;
- (id)title;
- (_Bool)flagState;
- (void)_performInteraction_Internal;

@end

