//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSHashTable;

@interface MFKeyboardAvoidance : NSObject
{
    NSHashTable *_keyboardAvoidables;
    NSDictionary *_currentKeyboardInfo;
    _Bool _registeredForNotifications;
}

+ (id)sharedController;
- (void)_unregisterForKeyboardNotifications;
- (void)_registerForKeyboardNotifications;
- (void)_keyboardWillChangeFrame:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (void)_keyboardWillHide:(id)arg1;
- (void)_adjustAvoidablesForKeyboardInfo:(id)arg1;
- (void)_adjustAvoidable:(id)arg1 forAutomaticKeyboardInfo:(id)arg2 animated:(_Bool)arg3;
- (double)_keyboardVerticalOverlapForView:(id)arg1 usingKeyboardInfo:(id)arg2;
- (void)unregisterKeyboardAvoidable:(id)arg1;
- (void)registerKeyboardAvoidable:(id)arg1;
- (id)_init;
- (void)dealloc;

@end

