//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFKeyboardAvoidance, UIView;

@protocol MFKeyboardAvoidable <NSObject>
- (void)keyboardAvoidance:(MFKeyboardAvoidance *)arg1 adjustForOverlap:(double)arg2;
- (id <UIViewControllerTransitionCoordinator>)transitionCoordinatorForKeyboardAvoidance:(MFKeyboardAvoidance *)arg1;
- (UIView *)viewForKeyboardAvoidance:(MFKeyboardAvoidance *)arg1;
@end

