//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

@class NSHashTable;

@interface MFKeyCommandRegistry : UIResponder
{
    NSHashTable *_reactorSet;
}

+ (id)globalRegistry;
- (void).cxx_destruct;
- (id)targetForAction:(SEL)arg1 withSender:(id)arg2;
- (id)nextResponder;
- (id)keyCommands;
- (id)combinedKeyCommands;
- (void)unregisterReactorForKeyCommands:(struct UIResponder *)arg1;
- (void)registerReactorForKeyCommands:(struct UIResponder *)arg1;
- (id)init;

@end

