//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSObject<OS_os_activity>;

@interface MFLibraryCompressor : NSObject
{
    NSArray *_mailboxUIDs;
    NSObject<OS_os_activity> *_libraryCompressionActivity;
}

+ (_Bool)libraryCompressionComplete;
@property(retain, nonatomic) NSObject<OS_os_activity> *libraryCompressionActivity; // @synthesize libraryCompressionActivity=_libraryCompressionActivity;
@property(readonly, nonatomic) NSArray *mailboxUIDs; // @synthesize mailboxUIDs=_mailboxUIDs;
- (void).cxx_destruct;
- (void)_removeCompressedXAttr:(id)arg1;
- (void)_markMailboxCompressed:(id)arg1;
- (_Bool)_mailboxNeedsCompression:(id)arg1;
- (_Bool)_compressionCanRun;
- (id)mailboxesNeedingCompression;
- (void)runLibraryCompressionShouldDefer:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithMailboxUIDs:(id)arg1;

@end

