//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFLibraryMessage.h"

@interface MFLibraryMessage (NanoServer)
+ (unsigned long long)nano_nnmkMailItemStatusFromMSResultsStatus:(unsigned long long)arg1;
+ (id)nanoMessageIdsForMailMessages:(id)arg1;
+ (unsigned long long)nnmkMailItemStatusFromMFMessageFlags:(unsigned long long)arg1 conversationFlags:(unsigned long long)arg2;
- (id)notificationMessageId;
- (id)nanoMessageId;
- (id)nanoMessageWithHeaders:(id)arg1;
- (id)nanoMessage;
@end

