//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageHeaderViewBlock.h"

@class MessageSuggestionTitleControl, NSArray;

@interface MFLoadBestAlternativeBannerView : MFMessageHeaderViewBlock
{
    id <MFLoadBestAlternativeBannerViewDelegate> _delegate;
    MessageSuggestionTitleControl *_titleControl;
    NSArray *_titleControlConstraints;
}

@property(retain, nonatomic) NSArray *titleControlConstraints; // @synthesize titleControlConstraints=_titleControlConstraints;
@property(retain, nonatomic) MessageSuggestionTitleControl *titleControl; // @synthesize titleControl=_titleControl;
@property(nonatomic) __weak id <MFLoadBestAlternativeBannerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setSeparatorDrawsFlushWithTrailingEdge:(_Bool)arg1;
- (void)setSeparatorDrawsFlushWithLeadingEdge:(_Bool)arg1;
- (void)requestLoad;
- (void)reloadData;
- (void)_titleControlTapped:(id)arg1;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

