//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MFMailboxUid;

@protocol MFMailboxPredictionEventCounter
- (void)countEvent:(unsigned long long)arg1 context:(unsigned long long)arg2 prediction:(id <MFMailboxPrediction>)arg3 mailbox:(MFMailboxUid *)arg4;
@end

