//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFActivityMonitor, MFMailboxUid, NSAttributedString, NSDate, NSString;

@interface MFMailboxStatus : NSObject
{
    _Bool _hasAccountError;
    int _localCount;
    int _totalCount;
    int _progress;
    MFMailboxUid *_mailbox;
    NSString *_status;
    unsigned long long _unreadCount;
    NSDate *_lastUpdate;
    MFActivityMonitor *_monitor;
    NSAttributedString *_icloudQuotaOffer;
    double _lastRefresh;
}

@property(nonatomic) double lastRefresh; // @synthesize lastRefresh=_lastRefresh;
@property(retain, nonatomic) NSAttributedString *icloudQuotaOffer; // @synthesize icloudQuotaOffer=_icloudQuotaOffer;
@property(nonatomic) _Bool hasAccountError; // @synthesize hasAccountError=_hasAccountError;
@property(retain, nonatomic) MFActivityMonitor *monitor; // @synthesize monitor=_monitor;
@property(nonatomic) int progress; // @synthesize progress=_progress;
@property(nonatomic) int totalCount; // @synthesize totalCount=_totalCount;
@property(nonatomic) int localCount; // @synthesize localCount=_localCount;
@property(retain, nonatomic) NSDate *lastUpdate; // @synthesize lastUpdate=_lastUpdate;
@property(nonatomic) unsigned long long unreadCount; // @synthesize unreadCount=_unreadCount;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(readonly, nonatomic) MFMailboxUid *mailbox; // @synthesize mailbox=_mailbox;
- (void).cxx_destruct;
- (id)initWithMailbox:(id)arg1;

@end

