//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFCachingMailboxPredictor, NSArray, NSDictionary, NSString;

@interface MFMailboxPredictionController : NSObject
{
    _Bool _currentlyPresentingDebugUI;
    id <MFQueryableLibraryAdapter> _libraryAdapter;
    Class _previousModelClass;
    NSDictionary *_previousParams;
    id <MFScheduler> _processingScheduler;
    MFCachingMailboxPredictor *_cachingPredictor;
    NSArray *_eventCounters;
    NSString *_previousDebugOutput;
}

+ (id)defaultInstance;
@property(copy) NSString *previousDebugOutput; // @synthesize previousDebugOutput=_previousDebugOutput;
@property(retain) NSArray *eventCounters; // @synthesize eventCounters=_eventCounters;
@property(retain) MFCachingMailboxPredictor *cachingPredictor; // @synthesize cachingPredictor=_cachingPredictor;
@property(retain, nonatomic) id <MFScheduler> processingScheduler; // @synthesize processingScheduler=_processingScheduler;
@property(retain, nonatomic) NSDictionary *previousParams; // @synthesize previousParams=_previousParams;
@property(nonatomic) Class previousModelClass; // @synthesize previousModelClass=_previousModelClass;
@property(nonatomic, getter=isCurrentlyPresentingDebugUI) _Bool currentlyPresentingDebugUI; // @synthesize currentlyPresentingDebugUI=_currentlyPresentingDebugUI;
@property(retain, nonatomic) id <MFQueryableLibraryAdapter> libraryAdapter; // @synthesize libraryAdapter=_libraryAdapter;
- (void).cxx_destruct;
- (void)_replaceMailboxPredictorIfRequired;
- (id)_mailboxForPersistentID:(id)arg1;
- (void)_invalidateCache;
- (void)_invalidateCacheForAddedMessages:(id)arg1;
- (id)_processPredictionForMessages:(id)arg1 limit:(unsigned long long)arg2 context:(unsigned long long)arg3;
- (void)presentDebugUIFromViewController:(id)arg1;
- (void)countEvent:(unsigned long long)arg1 prediction:(id)arg2 mailbox:(id)arg3;
- (void)countEvent:(unsigned long long)arg1 prediction:(id)arg2;
- (id)predictForMessages:(id)arg1 limit:(unsigned long long)arg2 context:(unsigned long long)arg3 diagnostics:(_Bool)arg4;
- (id)predictForMessages:(id)arg1 context:(unsigned long long)arg2;
- (void)dealloc;
- (id)init;

@end

