//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageHeaderViewBlock.h"

@class MFMailDropMetadata, MFProgressView, NSLayoutConstraint, NSMutableArray, NSProgress, UIButton, UILabel;

@interface MFMailDropBannerView : MFMessageHeaderViewBlock
{
    _Bool _hasLoaded;
    UILabel *_expirationLabel;
    UILabel *_downloadLabel;
    UIButton *_downloadIcon;
    MFProgressView *_progressView;
    NSLayoutConstraint *_iconWrapperWidth;
    NSLayoutConstraint *_labelFirstBaseline;
    NSLayoutConstraint *_expirationFirstBaseline;
    NSLayoutConstraint *_expirationBottom;
    NSMutableArray *_childProgresses;
    _Bool _hasDataLocally;
    MFMailDropMetadata *_metaData;
    NSProgress *_downloadProgress;
    unsigned long long _bannerState;
    unsigned long long _totalAttachmentSize;
    id <MFMailDropBannerDelegate> _delegate;
}

@property(nonatomic) id <MFMailDropBannerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long totalAttachmentSize; // @synthesize totalAttachmentSize=_totalAttachmentSize;
@property(nonatomic) _Bool hasDataLocally; // @synthesize hasDataLocally=_hasDataLocally;
@property(nonatomic) unsigned long long bannerState; // @synthesize bannerState=_bannerState;
@property(retain, nonatomic) NSProgress *downloadProgress; // @synthesize downloadProgress=_downloadProgress;
@property(retain, nonatomic) MFMailDropMetadata *metaData; // @synthesize metaData=_metaData;
- (void)setSeparatorIsHidden:(_Bool)arg1;
- (_Bool)shouldPresent;
- (void)contentSizeCategoryDidChangeNotification:(id)arg1;
- (void)reset;
- (_Bool)_shouldDisplayProgress;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)associateAttachment:(id)arg1;
- (void)startDownload:(id)arg1;
- (void)_setupDownloadIcon;
- (void)_setupExpirationLabel;
- (void)_setupDownloadLabel;
- (void)updateConstraints;
- (void)_updateBannerToState:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

