//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMessageCriterion, NSString, UIColor, UIImage;

@interface MFMailboxFilter : NSObject
{
    NSString *_name;
    NSString *_filterDescription;
    UIImage *_icon;
    UIColor *_iconTintColor;
    MFMessageCriterion *_criterion;
}

+ (id)filterForMailbox:(id)arg1;
+ (id)filterForSourceType:(unsigned long long)arg1;
+ (id)filterForSourceType:(unsigned long long)arg1 description:(id)arg2;
@property(readonly, nonatomic) MFMessageCriterion *criterion; // @synthesize criterion=_criterion;
@property(readonly, nonatomic) UIColor *iconTintColor; // @synthesize iconTintColor=_iconTintColor;
@property(readonly, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(readonly, copy, nonatomic) NSString *filterDescription; // @synthesize filterDescription=_filterDescription;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)debugDescription;
- (_Bool)isEqualToFilter:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (_Bool)hasCriterionOfType:(long long)arg1;
- (_Bool)isEquivalentToCriterion:(id)arg1;
- (id)initWithName:(id)arg1 description:(id)arg2 icon:(id)arg3 iconTintColor:(id)arg4 criterion:(id)arg5;
- (id)initWithMailbox:(id)arg1;
- (id)initWithSourceType:(unsigned long long)arg1 description:(id)arg2;

@end

