//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImage;

@interface MFMailboxFilterButton : UIButton
{
    _Bool _filterEnabled;
    UIImage *_notSelectedFlatImage;
    UIImage *_notSelectedFlatCompactImage;
    UIImage *_selectedFlatImage;
    UIImage *_selectedFlatCompactImage;
}

@property(retain, nonatomic) UIImage *selectedFlatCompactImage; // @synthesize selectedFlatCompactImage=_selectedFlatCompactImage;
@property(retain, nonatomic) UIImage *selectedFlatImage; // @synthesize selectedFlatImage=_selectedFlatImage;
@property(retain, nonatomic) UIImage *notSelectedFlatCompactImage; // @synthesize notSelectedFlatCompactImage=_notSelectedFlatCompactImage;
@property(retain, nonatomic) UIImage *notSelectedFlatImage; // @synthesize notSelectedFlatImage=_notSelectedFlatImage;
@property(nonatomic, getter=isFilterEnabled) _Bool filterEnabled; // @synthesize filterEnabled=_filterEnabled;
- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (id)_imageForFilterEnable:(_Bool)arg1;
- (void)_updateImage;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_commonInit;

@end

