//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMailboxUid.h"

@class NNMKMailbox, NSString;

@interface MFMailboxUid (NanoMail)
@property(readonly, nonatomic) unsigned long long nano_mailboxType;
@property(readonly, nonatomic) NNMKMailbox *nano_mailbox;
@property(readonly, nonatomic) NSString *nano_displayName;
@property(readonly, nonatomic) NSString *nano_mailboxId;
@end

