//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@interface MFMailboxFilterContext : NSObject
{
    NSSet *_mailboxes;
    unsigned long long _sourceType;
}

+ (id)contextWithMailboxes:(id)arg1 sourceType:(unsigned long long)arg2;
@property(readonly, nonatomic) unsigned long long sourceType; // @synthesize sourceType=_sourceType;
@property(readonly, copy, nonatomic) NSSet *mailboxes; // @synthesize mailboxes=_mailboxes;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (id)initWithMailboxes:(id)arg1 sourceType:(unsigned long long)arg2;

@end

