//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MFMailPurgeableStorage : NSObject
{
    id <MFAccountsProvider> _accountsProvider;
}

@property(retain, nonatomic) id <MFAccountsProvider> accountsProvider; // @synthesize accountsProvider=_accountsProvider;
- (void).cxx_destruct;
- (long long)deleteBodiesForMessages:(id)arg1 inMailboxFileURL:(id)arg2;
- (long long)deleteAttachmentsForMessages:(id)arg1 inMailboxFileURL:(id)arg2;
- (void)_batchEnumeratePurgeableMessageWithCutoffDate:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)_purgeableAccountsCriterion;
- (id)_criterionForPurgeableMessagesOlderThan:(id)arg1;
- (long long)purgeSpaceOlderThan:(id)arg1 spaceTarget:(long long)arg2;
- (long long)purgeableSpace;
- (id)library;
- (id)initWithAccountsProvider:(id)arg1;

@end

