//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSString, UILabel;

@interface MFMailboxFilterPickerControl : UIControl
{
    UILabel *_titleLabel;
    UILabel *_filtersLabel;
}

@property(retain, nonatomic) UILabel *filtersLabel; // @synthesize filtersLabel=_filtersLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *filterDescription;
- (struct CGSize)intrinsicContentSize;
- (void)_handleTapGestureRecognizer;
- (void)_setupGestureRecognizer;
- (void)layoutSubviews;
- (void)_setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

