//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFMailboxFilterProvider.h"

@class NSArray, NSSet, NSString;

@interface MFMailboxFilterProvider : NSObject <MFMailboxFilterProvider>
{
    NSArray *_mailboxFilters;
    NSArray *_filtersGroups;
    NSSet *_mailboxes;
    unsigned long long _sourceType;
}

@property(readonly, nonatomic) unsigned long long sourceType; // @synthesize sourceType=_sourceType;
@property(readonly, nonatomic) NSSet *mailboxes; // @synthesize mailboxes=_mailboxes;
@property(retain, nonatomic) NSArray *filtersGroups; // @synthesize filtersGroups=_filtersGroups;
- (void).cxx_destruct;
- (id)_addressLabelOfType:(long long)arg1;
- (id)_andFilterGroup;
- (id)_addressedGroup;
- (id)_flagsFilterGroup;
- (id)_mailboxFilterGroup;
- (id)_defaultCriterion;
@property(readonly, nonatomic) NSArray *mailboxFilters; // @synthesize mailboxFilters=_mailboxFilters;
- (id)reduce:(id)arg1;
- (id)filterMatchingCriterion:(id)arg1;
- (id)groupContainingFilter:(id)arg1;
@property(readonly, nonatomic) NSArray *defaultFilters;
@property(readonly, nonatomic) NSArray *allFilters;
- (id)initWithFilterContext:(id)arg1;
- (id)initWithMailboxes:(id)arg1 sourceType:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

