//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSSet;

@interface MFMailAccountsProviderState : NSObject
{
    unsigned long long _numberOfActiveAccounts;
    unsigned long long _numberOfInactiveAccounts;
    NSSet *_displayedAccountsIdentifiers;
    NSArray *_mailAccounts;
}

@property(readonly, copy, nonatomic) NSArray *mailAccounts; // @synthesize mailAccounts=_mailAccounts;
@property(readonly, copy, nonatomic) NSSet *displayedAccountsIdentifiers; // @synthesize displayedAccountsIdentifiers=_displayedAccountsIdentifiers;
@property(readonly, nonatomic) unsigned long long numberOfInactiveAccounts; // @synthesize numberOfInactiveAccounts=_numberOfInactiveAccounts;
@property(readonly, nonatomic) unsigned long long numberOfActiveAccounts; // @synthesize numberOfActiveAccounts=_numberOfActiveAccounts;
- (void).cxx_destruct;
- (id)initFromProvider:(id)arg1;

@end

