//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@interface MFMailboxFilterPickerCell : UITableViewCell
{
}

- (void)setIconTintColor:(id)arg1;
- (void)setIcon:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)bindWithMailboxFilter:(id)arg1;

@end

