//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFQueue, NSArray, NSObject<OS_dispatch_queue>;

@interface MFMailboxSourceMessageCache : NSObject
{
    struct __CFDictionary *_messageCache;
    CDUnknownBlockType _generator;
    NSObject<OS_dispatch_queue> *_queue;
    MFQueue *_messageQueue;
}

@property(retain, nonatomic) MFQueue *messageQueue; // @synthesize messageQueue=_messageQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) CDUnknownBlockType generator; // @synthesize generator=_generator;
- (id)_cachedMessageForMessageInfo:(id)arg1;
- (void)_evictMessageForMessageInfo:(id)arg1;
- (void)_storeMessage:(id)arg1 forMessageInfo:(id)arg2;
@property(readonly, nonatomic) unsigned long long count;
@property(readonly, nonatomic) NSArray *allMessages;
- (void)flush;
- (void)updateCachedMessage:(id)arg1;
- (id)cachedMessageForMessageInfo:(id)arg1;
- (id)messageForMessageInfo:(id)arg1 cacheIfNotAlready:(_Bool)arg2;
- (id)initWithCapacity:(unsigned long long)arg1 messageGenerator:(CDUnknownBlockType)arg2;
- (id)initWithMessageGenerator:(CDUnknownBlockType)arg1;
- (void)dealloc;

@end

