//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFDeviceStorage.h"

@class NSString;

@interface MFMailDeviceStorage : NSObject <MFDeviceStorage>
{
}

- (long long)freeSpaceGuidanceForSpaceIncrease:(long long)arg1 urgency:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

