//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMailPurgeableStorage;

@interface MFMailPurgableStorageMonitor : NSObject
{
    MFMailPurgeableStorage *_purgeableStorage;
    struct __CFString *_serviceName;
}

@property(readonly, nonatomic) struct __CFString *serviceName; // @synthesize serviceName=_serviceName;
@property(retain, nonatomic) MFMailPurgeableStorage *purgeableStorage; // @synthesize purgeableStorage=_purgeableStorage;
- (void).cxx_destruct;
- (void)pushPurgeableStateUpdate;
- (void)_schedulePushPurgeableSpaceUpdate;
- (id)init;
- (void)dealloc;

@end

