//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMailMessageLibrary, MFMailboxUid;

@interface MFMailboxMessageBodyProcessor : NSObject
{
    id <MFMailboxMessageBodyProcessorDelegate> _delegate;
    MFMailboxUid *_mailbox;
    id <MFDeviceStorage> _deviceStorage;
    unsigned long long _batchSize;
    id <MessageBodyLoader> _messageBodyLoader;
}

@property(readonly, nonatomic) id <MessageBodyLoader> messageBodyLoader; // @synthesize messageBodyLoader=_messageBodyLoader;
@property(readonly, nonatomic) unsigned long long batchSize; // @synthesize batchSize=_batchSize;
@property(readonly, nonatomic) id <MFDeviceStorage> deviceStorage; // @synthesize deviceStorage=_deviceStorage;
@property(readonly, nonatomic) MFMailboxUid *mailbox; // @synthesize mailbox=_mailbox;
@property(nonatomic) __weak id <MFMailboxMessageBodyProcessorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (long long)_spaceIncreaseUrgencyForMessage:(id)arg1;
- (long long)_freeSpaceGuidanceForSpaceIncreaseForMessage:(id)arg1;
- (_Bool)_shouldDownloadMessage:(id)arg1;
- (_Bool)_shouldTryToDownloadMessage:(id)arg1;
- (_Bool)_shouldContinueProcessing;
- (void)_enumerateMessagesToDownload:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) MFMailMessageLibrary *library;
- (void)runSynchronously;
- (id)initWithMailbox:(id)arg1 batchSize:(unsigned long long)arg2 deviceStorage:(id)arg3;

@end

