//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "MFPrefetchOperation.h"

@class MFCancelationToken, MFMessageInfo, MessageMiniMall, NSIndexPath, NSString;

@interface MFMessageMiniMallMessagePrefetchOperation : NSOperation <MFPrefetchOperation>
{
    MessageMiniMall *_mall;
    MFMessageInfo *_messageInfo;
    NSIndexPath *_indexPath;
    MFCancelationToken *_observationsToken;
}

@property(retain, nonatomic) MFCancelationToken *observationsToken; // @synthesize observationsToken=_observationsToken;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain, nonatomic) MFMessageInfo *messageInfo; // @synthesize messageInfo=_messageInfo;
@property(retain, nonatomic) MessageMiniMall *mall; // @synthesize mall=_mall;
- (void).cxx_destruct;
- (void)_registerAriadneSignpostObserver;
- (void)main;
- (id)initWithIndexPath:(id)arg1 mall:(id)arg2 messageInfo:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

