//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageLibrary.h"

@interface MFMessageLibrary (NanoServer)
- (id)loadLibraryMessagesFromLibraryMatchingCriterion:(id)arg1 count:(unsigned long long)arg2 protectedDataAvailable:(_Bool *)arg3;
- (id)libraryMessagesForMessageIds:(id)arg1 protectedDataAvailable:(_Bool *)arg2;
- (id)libraryMessageForMessageId:(id)arg1 libraryOptions:(unsigned int)arg2;
@end

