//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageHeaderViewBlock.h"

@class NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface MFMessageSashHeaderBlock : MFMessageHeaderViewBlock
{
    UIView *_backgroundView;
    UILabel *_titleLabel;
    UIImageView *_iconImageView;
    NSLayoutConstraint *_titleLabelFirstBaseline;
    NSLayoutConstraint *_titleLabelBottomToBaseline;
    NSLayoutConstraint *_iconVerticalConstraint;
}

+ (double)heightForCurrentFontMetrics;
+ (id)titleFont;
@property(retain, nonatomic) NSLayoutConstraint *iconVerticalConstraint; // @synthesize iconVerticalConstraint=_iconVerticalConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelBottomToBaseline; // @synthesize titleLabelBottomToBaseline=_titleLabelBottomToBaseline;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelFirstBaseline; // @synthesize titleLabelFirstBaseline=_titleLabelFirstBaseline;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void).cxx_destruct;
- (void)displayMessage:(id)arg1;
- (void)_updateMailboxIcon;
- (void)_updateFonts;
- (void)contentSizeCategoryDidChangeNotification:(id)arg1;
- (void)setDisplayMetrics:(id)arg1;
- (void)updateConstraints;
- (void)initializePrimaryLayoutConstraints;
- (void)createPrimaryViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

