//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MFLoadBestAlternativeBannerViewDelegate.h"
#import "MFLoadRemoteImagesBannerViewDelegate.h"
#import "MFMailDropBannerDelegate.h"
#import "MFMailWebProcessDelegate.h"
#import "MFMessageHeaderViewDelegate.h"
#import "MFReusable.h"
#import "MFSuggestionHandlingDelegate.h"
#import "UIPopoverPresentationControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WKNavigationDelegate.h"
#import "WKNavigationDelegatePrivate.h"
#import "WKUIDelegatePrivate.h"

@class MFAttachmentManager, MFCancelationToken, MFConversationItemFooterView, MFLoadBestAlternativeBannerView, MFLoadRemoteImagesBannerView, MFMailDropBannerView, MFMessageContentAttachments, MFMessageContentLoadingView, MFMessageDisplayMetrics, MFMessageHeaderView, MFMessageLoadingContext, MFWebViewDictionary, MFWebViewLoadingController, MessageSuggestionBannerView, MessageSuggestionSession, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, PartialMessageIndicator, UIBarButtonItem, UIScrollView, WKWebView, _MFMessageContentResizeWrapperView;

@interface MFMessageContentView : UIView <UIPopoverPresentationControllerDelegate, WKNavigationDelegate, WKNavigationDelegatePrivate, WKUIDelegatePrivate, MFLoadBestAlternativeBannerViewDelegate, MFLoadRemoteImagesBannerViewDelegate, MFMessageHeaderViewDelegate, MFMailDropBannerDelegate, MFMailWebProcessDelegate, MFSuggestionHandlingDelegate, UIScrollViewDelegate, MFReusable>
{
    MFCancelationToken *_loadingCancelable;
    MFMessageContentAttachments *_attachmentsInfo;
    NSMutableDictionary *_attachmentCancelablesByContentID;
    MFMessageHeaderView *_headerView;
    MFMailDropBannerView *_mailDropBanner;
    MFLoadBestAlternativeBannerView *_loadBestAlternativePartBanner;
    MFLoadRemoteImagesBannerView *_loadImagesHeaderBlock;
    MessageSuggestionBannerView *_suggestionBanner;
    PartialMessageIndicator *_partialMessageIndicator;
    UIView *_previousContentSnapshotWrapperView;
    UIView *_backgroundView;
    id <MFScheduler> _attachmentsScheduler;
    NSMutableArray *_scriptHandlers;
    MessageSuggestionSession *_suggestionSession;
    UIBarButtonItem *_presentedControllerDoneButtonItem;
    id <MFCancelable> _contentSizeObservation;
    _Bool _suppressContentSizeNotifications;
    struct UIEdgeInsets _originalZoomInsets;
    _Bool _paddingConstantsNeedUpdate;
    MFConversationItemFooterView *_footerView;
    unsigned long long _webProcessCrashCount;
    struct {
        unsigned int delegateRespondsToDidFinishLoadingMessages:1;
        unsigned int delegateRespondsToDidFinishFirstPaint:1;
        unsigned int delegateRespondsToDidDisplayContent:1;
        unsigned int delegateRespondsToDidFinishRenderingWithHeight:1;
        unsigned int delegateRespondsToExpandQuoteAtScrollOffset:1;
        unsigned int delegateRespondsToWillBeginZoomingMessage:1;
        unsigned int delegateRespondsToDidEndZoomingMessage:1;
        unsigned int delegateRespondsToDidTapRevealActionsButton:1;
        unsigned int delegateRespondsToLoadingIndicatorDidChangeVisibility:1;
    } _flags;
    _Bool _automaticallyCollapseQuotedContent;
    _Bool _showMessageFooter;
    _Bool _initiallyZoomsToShowAllContent;
    _Bool _suppressScrolling;
    _Bool _contentPaddingFollowsLayoutMargins;
    _Bool _hasVisibleContent;
    _Bool _showsBanners;
    _Bool _zoomEnabled;
    id <MFMessageContentViewDelegate> _delegate;
    id <MFMessageContentViewDataSource> _dataSource;
    MFMessageLoadingContext *_loadingContext;
    NSString *_selectedHTML;
    long long _remoteImagesBlockingReason;
    UIView *_previousContentSnapshot;
    MFMessageDisplayMetrics *_displayMetrics;
    id <MFCancelable> _loadingIndicatorCancelable;
    MFMessageContentLoadingView *_loadingView;
    double _initialScale;
    MFWebViewLoadingController *_webViewLoadingController;
    _MFMessageContentResizeWrapperView *_resizingWrapperView;
    NSDictionary *_attachmentDragPreviews;
    struct CGPoint _initialContentOffset;
}

@property(retain, nonatomic) NSDictionary *attachmentDragPreviews; // @synthesize attachmentDragPreviews=_attachmentDragPreviews;
@property(retain, nonatomic) _MFMessageContentResizeWrapperView *resizingWrapperView; // @synthesize resizingWrapperView=_resizingWrapperView;
@property(retain, nonatomic) MFWebViewLoadingController *webViewLoadingController; // @synthesize webViewLoadingController=_webViewLoadingController;
@property(nonatomic) double initialScale; // @synthesize initialScale=_initialScale;
@property(retain, nonatomic) MFMessageContentLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) id <MFCancelable> loadingIndicatorCancelable; // @synthesize loadingIndicatorCancelable=_loadingIndicatorCancelable;
@property(nonatomic, getter=isZoomEnabled) _Bool zoomEnabled; // @synthesize zoomEnabled=_zoomEnabled;
@property(nonatomic) _Bool showsBanners; // @synthesize showsBanners=_showsBanners;
@property(nonatomic) _Bool hasVisibleContent; // @synthesize hasVisibleContent=_hasVisibleContent;
@property(nonatomic) _Bool contentPaddingFollowsLayoutMargins; // @synthesize contentPaddingFollowsLayoutMargins=_contentPaddingFollowsLayoutMargins;
@property(nonatomic) _Bool suppressScrolling; // @synthesize suppressScrolling=_suppressScrolling;
@property(nonatomic) _Bool initiallyZoomsToShowAllContent; // @synthesize initiallyZoomsToShowAllContent=_initiallyZoomsToShowAllContent;
@property(retain, nonatomic) MFMessageDisplayMetrics *displayMetrics; // @synthesize displayMetrics=_displayMetrics;
@property(retain, nonatomic) UIView *previousContentSnapshot; // @synthesize previousContentSnapshot=_previousContentSnapshot;
@property(nonatomic) long long remoteImagesBlockingReason; // @synthesize remoteImagesBlockingReason=_remoteImagesBlockingReason;
@property(nonatomic) _Bool showMessageFooter; // @synthesize showMessageFooter=_showMessageFooter;
@property(nonatomic) _Bool automaticallyCollapseQuotedContent; // @synthesize automaticallyCollapseQuotedContent=_automaticallyCollapseQuotedContent;
@property(readonly, nonatomic) MFMessageHeaderView *headerView; // @synthesize headerView=_headerView;
@property(copy, nonatomic) NSString *selectedHTML; // @synthesize selectedHTML=_selectedHTML;
@property(nonatomic) struct CGPoint initialContentOffset; // @synthesize initialContentOffset=_initialContentOffset;
@property(retain, nonatomic) MFMessageLoadingContext *loadingContext; // @synthesize loadingContext=_loadingContext;
@property(nonatomic) __weak id <MFMessageContentViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) id <MFMessageContentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (id)viewForZoomingInScrollView:(id)arg1;
- (id)presentedControllerDoneButtonItem;
- (void)presentationController:(id)arg1 willPresentWithAdaptiveStyle:(long long)arg2 transitionCoordinator:(id)arg3;
- (void)_showModalViewController:(id)arg1 presentationSource:(id)arg2;
- (void)dismissPresentedViewController:(id)arg1;
- (void)displayMultipleCallsToAction:(id)arg1 presentationSource:(id)arg2;
- (void)didIgnoreAction:(id)arg1;
- (void)didConfirmAction:(id)arg1;
- (void)_updateSuggestionsBannerForAction:(id)arg1;
- (void)ignoreAction:(id)arg1;
- (void)showConfirmationForAction:(id)arg1 presentationSource:(id)arg2;
- (void)_clearSuggestionsBannerAnimated:(_Bool)arg1;
- (void)loadRemoteImagesBannerDidTriggerLoad:(id)arg1;
- (void)_clearLoadRemoteImagesBannerAnimated:(_Bool)arg1;
- (void)_clearLoadRemainingMessageContentFooterAnimated:(_Bool)arg1;
- (void)didTapLoadRemainingMessageContentFooterView:(id)arg1;
- (void)_addLoadRemainingMessageContentFooterWithRemainingBytes:(unsigned long long)arg1;
- (void)loadRemainingMessageContentIfNecessary;
- (void)_clearLoadBestAlternativeBannerAnimated:(_Bool)arg1;
- (void)didTapLoadBestAlternativeBannerView:(id)arg1;
- (void)_addLoadBestAlternativePartBanner;
- (void)loadBestAlternativePartIfNecessary;
- (id)viewPrintFormatter;
- (void)_downloadAllMailDropAttachments;
- (void)mailDropBannerDidTriggerDownload:(id)arg1;
- (void)_stopObservingContentHeight;
- (void)_notifyDelegateScrollViewSizeChanged:(struct CGSize)arg1;
- (void)_beginObservingContentHeight;
- (id)_attachmentForMailDropMetaData:(id)arg1;
- (id)_maildropMetadataFromMessageHeaders;
- (void)_injectAttachmentViewForElementWithSourceAttributeValue:(id)arg1 forAttachment:(id)arg2;
- (void)_injectAttachmentViewForMailDropAttachment:(id)arg1;
- (id)attachmentElementAttributesForAttachment:(id)arg1;
- (void)_didInjectAttachment:(id)arg1;
- (void)_parsedMailDropNodes:(id)arg1;
- (void)_resetHeaderOffsetForZoom;
- (void)_adjustHeaderOffsetForZoom;
- (double)_adjustWebViewInsetsToAccomodateHeaderAndFooter;
- (void)footerViewDidChangeHeight:(id)arg1;
- (void)headerViewDidChangeHeight:(id)arg1;
- (id)_attachmentForElement:(id)arg1;
- (unsigned long long)_webView:(id)arg1 indexIntoAttachmentListForElement:(id)arg2;
- (id)_attachmentListForWebView:(id)arg1 sourceIsManaged:(_Bool *)arg2;
- (unsigned long long)indexOfPreviewableAttachment:(id)arg1;
@property(readonly) NSArray *previewableAttachments;
- (id)_previewableAttachmentsExcludingBanner;
- (_Bool)_webView:(id)arg1 showCustomSheetForElement:(id)arg2;
- (long long)_webView:(id)arg1 dataOwnerForDragSession:(id)arg2;
- (id)_dataDetectionContextForWebView:(id)arg1;
- (id)_webView:(id)arg1 previewForCancellingItem:(id)arg2 withDefault:(id)arg3;
- (id)_webView:(id)arg1 previewForLiftingItem:(id)arg2 session:(id)arg3;
- (id)_webView:(id)arg1 previewItem:(id)arg2;
- (id)_attachmentPreviewsFromData:(id)arg1;
- (_Bool)_objectContainsNonEmptyString:(id)arg1;
- (id)_webView:(id)arg1 adjustedDataInteractionItemProvidersForItemProvider:(id)arg2 representingObjects:(id)arg3 additionalData:(id)arg4;
- (void)_webView:(id)arg1 dataInteraction:(id)arg2 session:(id)arg3 didEndWithOperation:(unsigned long long)arg4;
- (void)_webView:(id)arg1 dataInteraction:(id)arg2 sessionWillBegin:(id)arg3;
- (void)_webViewWebProcessDidBecomeUnresponsive:(id)arg1;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)_webView:(id)arg1 renderingProgressDidChange:(unsigned long long)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webProcessDidWriteToPasteboard;
- (void)webProcessDidCreateBrowserContextControllerLoadDelegate;
- (void)webProcessDidBlockLoadingResourceWithURL:(id)arg1;
- (void)webProcessDidFinishLoadForURL:(id)arg1;
- (void)webProcessDidFinishDocumentLoadForURL:(id)arg1;
- (void)webProcessDidFailLoadingResourceWithURL:(id)arg1;
- (id)_quotedContentAttributionForMessage:(id)arg1;
- (void)_revealActionsButtonTapped;
- (void)_seeMoreButtonTapped;
- (void)_expandQuoteWithCollapsedBlockquoteOffset:(double)arg1 expandedOffset:(double)arg2;
- (void)_handleAttachmentTapMessage:(id)arg1;
- (void)_longPressedAttachment:(id)arg1 rect:(struct CGRect)arg2 view:(id)arg3;
- (void)_attachmentNodeWasTappedWithContentId:(id)arg1 rect:(struct CGRect)arg2 view:(id)arg3;
- (void)_setAttachmentProgress:(double)arg1 forAttachment:(id)arg2;
- (void)_setAttachmentState:(long long)arg1 forAttachment:(id)arg2;
- (void)_stopObservingProgressForAttachment:(id)arg1;
- (void)_beginObservingProgressForAttachment:(id)arg1;
- (void)_alertMailDropDownloadIsTooLargeForCell:(_Bool)arg1;
- (void)_displayDismissibleAttachmentErrorWithTitle:(id)arg1 message:(id)arg2;
- (void)displayAttachmentWithMIMEPartNumber:(id)arg1;
- (void)_attachment:(id)arg1 displayViewerFromRect:(struct CGRect)arg2 inView:(id)arg3;
- (void)_attachment:(id)arg1 sendDisplayAction:(SEL)arg2 fromRect:(struct CGRect)arg3 iconRect:(struct CGRect)arg4 inView:(id)arg5;
- (_Bool)_startDownloadForAttachment:(id)arg1 userInitiated:(_Bool)arg2 shouldLoadRemainingMessageContent:(_Bool)arg3;
- (void)_attachment:(id)arg1 finishedLoadingWithData:(id)arg2;
- (id)_existingAttachmentForContentID:(id)arg1;
- (id)_existingAttachmentForURL:(id)arg1;
- (long long)_displayStateForAttachment:(id)arg1;
- (void)_foundImageCIDAttachments:(id)arg1;
- (id)mailDropAttachments;
- (id)imageAttachments;
@property(copy) NSArray *attachments;
- (void)addAttachments:(id)arg1;
- (id)_libraryMessage;
- (void)endResizing;
- (void)prepareContentViewForResizingWithSnapshotRect:(struct CGRect)arg1;
- (void)generateSnapshotImageWithCompletion:(CDUnknownBlockType)arg1;
- (void)loadingContext:(id)arg1 contentAnalysisFoundSuggestions:(id)arg2 error:(id)arg3;
- (void)_requestWebViewLoad;
- (void)loadingContext:(id)arg1 didLoadEvent:(id)arg2 error:(id)arg3;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)clearSelectedHTML;
- (void)reload;
- (void)setLoadingIndicatorVisible:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=isLoadingIndicatorVisible) _Bool loadingIndicatorVisible;
- (void)showDelayedProgressUI;
- (void)_removeLoadingSubview:(id)arg1;
- (void)_addLoadingSubview:(id)arg1;
- (void)updateForRedisplay;
- (void)_clearAllBannersAnimated:(_Bool)arg1;
- (void)clearMessage;
- (void)_reloadUserStyleSheets;
- (id)_styleSheetWithPadding:(struct UIEdgeInsets)arg1 useWideLayout:(_Bool)arg2;
- (void)_updateWebViewPaddingConstants;
- (void)_setNeedsPaddingConstantsUpdate;
- (void)_fontSizeDidChange:(id)arg1;
- (void)layoutMarginsDidChange;
- (void)_updateMinimumFontSize;
- (void)selectAll:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)_firstResponderIsInWebView;
- (void)setFrame:(struct CGRect)arg1;
- (double)_viewportWidth;
- (void)_layoutLoadingView;
- (void)_layoutBackgroundView;
- (void)_layoutFooterView;
- (void)layoutSubviews;
- (void)_setupWebProcessLocalizedStrings;
- (void)_addScriptHandlerForKey:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)_executeJavaScriptExpression:(id)arg1;
- (id)_executeJavaScriptMethod:(id)arg1 arguments:(id)arg2;
@property(readonly, nonatomic) _Bool sourceIsManaged;
@property(readonly, nonatomic) MFAttachmentManager *attachmentManager;
@property(readonly, nonatomic) MFWebViewDictionary *webViewConstants;
@property(readonly, nonatomic) WKWebView *webView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

