//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPrintPageRenderer.h"

#import "MFMessageViewControllerDelegate.h"
#import "UIPrintInteractionControllerDelegate.h"

@class MFMailMessage, MFMessageViewController, MFPromise, NSString, UIImage, UIViewPrintFormatter, UIWindow;

@interface MFMessagePrinter : UIPrintPageRenderer <MFMessageViewControllerDelegate, UIPrintInteractionControllerDelegate>
{
    UIWindow *_window;
    MFMailMessage *_message;
    MFMessageViewController *_messageViewController;
    MFPromise *_webLoadPromise;
    UIViewPrintFormatter *_headerFormatter;
    UIViewPrintFormatter *_bodyFormatter;
    UIImage *_contactPhoto;
    double _headerLastPageHeight;
    _Bool _isPrintableContentInitialized;
}

- (void)drawPageAtIndex:(long long)arg1 inRect:(struct CGRect)arg2;
- (void)drawContentForPageAtIndex:(long long)arg1 inRect:(struct CGRect)arg2;
- (void)messageViewController:(id)arg1 didFinishRenderingWithHeight:(double)arg2;
- (void)_setupPrintableContent;
- (struct CGRect)_printingRectForImageableRect:(struct CGRect)arg1;
- (long long)numberOfPages;
- (void)presentPrintSheet;
- (void)presentPrintPopoverFromBarButtonItem:(id)arg1;
- (id)initWithMessageLoadingContext:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

