//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFCancelationToken, MFDiagnostic, MFMessageLoadingContext;

@interface MFMessageLoadingContextErrorReportingMiddleware : NSObject
{
    MFCancelationToken *_cancellationToken;
    MFMessageLoadingContext *_loadingContext;
    MFDiagnostic *_diagnosticManager;
}

@property(retain, nonatomic) MFDiagnostic *diagnosticManager; // @synthesize diagnosticManager=_diagnosticManager;
@property(retain, nonatomic) MFMessageLoadingContext *loadingContext; // @synthesize loadingContext=_loadingContext;
- (void)_logToAWDWithError:(id)arg1;
- (void)_logToSystemWithError:(id)arg1;
- (void)_handleLoadEvent:(id)arg1 error:(id)arg2;
- (void)_observeLoadingContext;
@property(readonly, nonatomic) id <MFScheduler> scheduler;
@property(readonly, nonatomic) MFCancelationToken *cancellationToken; // @synthesize cancellationToken=_cancellationToken;
- (id)initWithLoadingContext:(id)arg1;
- (id)initWithLoadingContext:(id)arg1 diagnosticManager:(id)arg2;
- (void)dealloc;

@end

