//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageDisplayMetrics.h"

@interface MFMessageDisplayMetricsRegular : MFMessageDisplayMetrics
{
}

- (double)statusIndicatorVerticalSpacing;
- (double)headerBottomPadding;
- (double)firstSeparatorToSubjectBaseline;
- (double)recipientBaselineToFirstSeparatorInConversation;
- (double)recipientBaselineToFirstSeparator;
- (double)baselineToBaselineSpacingInConversation;
- (double)baselineToBaselineSpacing;
- (double)topToSenderBaselineInConversation;
- (double)topToSenderBaseline;
- (double)minHorizontalSpacing;
- (double)avatarDiameter;

@end

