//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableOrderedSet;

@interface MFMessageViewControllerReuseQueue : NSObject
{
    NSMutableOrderedSet *_keyOrdering;
    NSMutableDictionary *_messageViewControllers;
    unsigned long long _generatedMessageViewControllersCount;
}

@property(nonatomic) unsigned long long generatedMessageViewControllersCount; // @synthesize generatedMessageViewControllersCount=_generatedMessageViewControllersCount;
@property(retain, nonatomic) NSMutableDictionary *messageViewControllers; // @synthesize messageViewControllers=_messageViewControllers;
@property(retain, nonatomic) NSMutableOrderedSet *keyOrdering; // @synthesize keyOrdering=_keyOrdering;
- (void)drain;
- (void)enqueueMessageViewController:(id)arg1;
- (id)dequeueMessageViewControllerForLoadingContext:(id)arg1;
- (void)_evictLeastRecentlyUsedMessageViewControllers;
- (id)_dequeueLeastRecentlyUsedMessageViewController;
- (id)_dequeueMessageViewControllerForKey:(id)arg1;
- (id)debugDescription;
- (id)init;
- (void)dealloc;

@end

