//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UITraitCollection;

@interface MFMessageDisplayMetrics : NSObject
{
    UITraitCollection *_traitCollection;
    double _topToSenderBaseline;
    double _topToSenderBaselineInConversation;
    double _baselineToBaselineSpacing;
    double _baselineToBaselineSpacingInConversation;
    double _recipientBaselineToFirstSeparator;
    double _recipientBaselineToFirstSeparatorInConversation;
    double _firstSeparatorToSubjectBaseline;
    double _headerBottomPadding;
    double _statusIndicatorVerticalSpacing;
    struct UIEdgeInsets _layoutMargins;
}

+ (id)displayMetricsWithTraitCollection:(id)arg1 layoutMargins:(struct UIEdgeInsets)arg2;
@property(readonly, nonatomic) double statusIndicatorVerticalSpacing; // @synthesize statusIndicatorVerticalSpacing=_statusIndicatorVerticalSpacing;
@property(readonly, nonatomic) double headerBottomPadding; // @synthesize headerBottomPadding=_headerBottomPadding;
@property(readonly, nonatomic) double firstSeparatorToSubjectBaseline; // @synthesize firstSeparatorToSubjectBaseline=_firstSeparatorToSubjectBaseline;
@property(readonly, nonatomic) double recipientBaselineToFirstSeparatorInConversation; // @synthesize recipientBaselineToFirstSeparatorInConversation=_recipientBaselineToFirstSeparatorInConversation;
@property(readonly, nonatomic) double recipientBaselineToFirstSeparator; // @synthesize recipientBaselineToFirstSeparator=_recipientBaselineToFirstSeparator;
@property(readonly, nonatomic) double baselineToBaselineSpacingInConversation; // @synthesize baselineToBaselineSpacingInConversation=_baselineToBaselineSpacingInConversation;
@property(readonly, nonatomic) double baselineToBaselineSpacing; // @synthesize baselineToBaselineSpacing=_baselineToBaselineSpacing;
@property(readonly, nonatomic) double topToSenderBaselineInConversation; // @synthesize topToSenderBaselineInConversation=_topToSenderBaselineInConversation;
@property(readonly, nonatomic) double topToSenderBaseline; // @synthesize topToSenderBaseline=_topToSenderBaseline;
@property(nonatomic) struct UIEdgeInsets layoutMargins; // @synthesize layoutMargins=_layoutMargins;
@property(retain, nonatomic) UITraitCollection *traitCollection; // @synthesize traitCollection=_traitCollection;
- (void).cxx_destruct;
- (double)_scaledFloatWithValue:(double)arg1 fontStyle:(id)arg2;
- (id)_cachedFontForStyle:(id)arg1;
- (id)description;
@property(readonly, nonatomic) double messageBottomPaddingInConversation;
@property(readonly, nonatomic) double footerTopToFirstBaselineInConversation;
@property(readonly, nonatomic) double statusIndicatorHorizontalSpacing;
@property(readonly, nonatomic) double minHorizontalSpacing;
@property(readonly, nonatomic) double avatarDiameterForCurrentContentSize;
@property(readonly, nonatomic) double avatarDiameter;
@property(readonly, nonatomic) _Bool prefersFlushSeparator;
@property(readonly, nonatomic) _Bool hasGenerousMargins;
@property(readonly, nonatomic) _Bool hasCompactLayout;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)fontCacheKeyPrefix;

@end

