//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MFMessageBulletinsFilter : NSObject
{
    NSMutableDictionary *_notificationCutoffDateByMailbox;
}

@property(retain, nonatomic) NSMutableDictionary *notificationCutoffDateByMailbox; // @synthesize notificationCutoffDateByMailbox=_notificationCutoffDateByMailbox;
- (void).cxx_destruct;
- (id)notificationCutoffsByMailbox;
- (void)removeMailbox:(id)arg1;
- (void)removeMailboxesForAccount:(id)arg1;
- (void)_handleAccountsChanged:(id)arg1;
- (void)_updateCutoffForMailboxWithMessage:(id)arg1 afterDate:(id)arg2;
- (_Bool)_messagePassTest:(id)arg1;
- (void)updateCutoffForMailboxesWithDate:(id)arg1;
- (void)updateCutoffForMailboxesWithMessages:(id)arg1;
- (id)messagesNeedingNotification:(id)arg1 afterDate:(id)arg2;
- (id)init;

@end

