//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLProtocol.h"

@class MFCancelationToken, MFMessageLoadingContext, MFPromise;

@interface MFMessageContentURLProtocol : NSURLProtocol
{
    MFCancelationToken *_token;
    MFMessageLoadingContext *_loadingContext;
    MFPromise *_promise;
}

+ (_Bool)requestIsCacheEquivalent:(id)arg1 toRequest:(id)arg2;
+ (id)canonicalRequestForRequest:(id)arg1;
+ (_Bool)canInitWithRequest:(id)arg1;
+ (id)loadingContextForURL:(id)arg1;
+ (id)URLForLoadingContext:(id)arg1;
+ (id)scheme;
+ (void)setRegistry:(id)arg1;
+ (id)registry;
+ (void)initialize;
@property(retain, nonatomic) MFPromise *promise; // @synthesize promise=_promise;
@property(readonly) MFMessageLoadingContext *loadingContext; // @synthesize loadingContext=_loadingContext;
@property(readonly) MFCancelationToken *token; // @synthesize token=_token;
- (void)_didLoadContentEvent:(id)arg1 error:(id)arg2;
- (void)stopLoading;
- (void)startLoading;
- (id)_cachedResponseWithData:(id)arg1 error:(id *)arg2;
- (id)initWithRequest:(id)arg1 cachedResponse:(id)arg2 client:(id)arg3;
- (void)dealloc;

@end

