//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFMessageContentViewDelegate.h"

@class MFMessageContentView, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString;

@interface MFMessageScreenshotGenerator : NSObject <MFMessageContentViewDelegate>
{
    MFMessageContentView *_contentView;
    NSObject<OS_dispatch_queue> *_generationQueue;
    NSObject<OS_dispatch_semaphore> *_messageFinishedLoadingSemaphore;
}

- (void).cxx_destruct;
- (id)presentingViewControllerForMessageContentView:(id)arg1;
- (void)messageContentViewDidFinishLoadingMessage:(id)arg1;
- (void)_setupAndAddContentViewForMessage:(id)arg1 withTraitCollection:(id)arg2 layoutMargins:(struct UIEdgeInsets)arg3 imageSize:(struct CGSize)arg4;
- (void)_generateScreenshotImageForMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)generateScreenshotImageOfSize:(struct CGSize)arg1 forMessage:(id)arg2 traitCollection:(id)arg3 layoutMargins:(struct UIEdgeInsets)arg4 completion:(CDUnknownBlockType)arg5;
- (void)generateScreenshotOfSize:(struct CGSize)arg1 forMessage:(id)arg2 traitCollection:(id)arg3 layoutMargins:(struct UIEdgeInsets)arg4 completion:(CDUnknownBlockType)arg5;
@property(readonly, retain, nonatomic) MFMessageContentView *contentView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

