//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFCancelationToken, MFMessageLoadingContext, _MFMessageLoadingContextRetryRegistry;

@interface MFMessageLoadingContextRetryMiddleware : NSObject
{
    _Bool _shouldRetryOnNetworkChange;
    MFMessageLoadingContext *_loadingContext;
    CDUnknownBlockType _handler;
    _MFMessageLoadingContextRetryRegistry *_registry;
    MFCancelationToken *_cancellationToken;
}

@property(nonatomic) _Bool shouldRetryOnNetworkChange; // @synthesize shouldRetryOnNetworkChange=_shouldRetryOnNetworkChange;
@property(retain, nonatomic) MFCancelationToken *cancellationToken; // @synthesize cancellationToken=_cancellationToken;
@property(retain, nonatomic) _MFMessageLoadingContextRetryRegistry *registry; // @synthesize registry=_registry;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(retain, nonatomic) MFMessageLoadingContext *loadingContext; // @synthesize loadingContext=_loadingContext;
- (_Bool)_shouldRetry;
- (void)_retry;
- (void)_handleLoadEvent:(id)arg1 error:(id)arg2;
- (id)initWithLoadingContext:(id)arg1 registry:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (id)initWithLoadingContext:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)dealloc;

@end

