//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMessageViewingContext;

@protocol MFMessageViewingContextDelegate <NSObject>

@optional
- (void)messageViewingContextMessageAnalysisCompleted:(MFMessageViewingContext *)arg1;
- (void)messageViewingContextContentLoadCompleted:(MFMessageViewingContext *)arg1;
- (void)messageViewingContextFullMessageLoadFailed:(MFMessageViewingContext *)arg1;
- (void)messageViewingContextContentLoadWillBegin:(MFMessageViewingContext *)arg1;
@end

