//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFMailboxMessageBodyProcessorDelegate.h"

@class MailPersistentStorage, NSArray, NSDate, NSObject<OS_os_activity>, NSString;

@interface MFMessageBodyProcessor : NSObject <MFMailboxMessageBodyProcessorDelegate>
{
    NSString *_name;
    id <MFAccountsProvider> _accountsProvider;
    id <MFDeviceStorage> _deviceStorage;
    id <MFActivityCondition> _condition;
    NSObject<OS_os_activity> *_loggingActivity;
    NSArray *_excludedMailboxTypes;
    long long _lastFetchDateCutoff;
    long long _accountMailboxesBatchSize;
    long long _mailboxMessagesBatchSize;
    NSDate *_stopDate;
}

+ (id)powernapProcessor;
+ (void)initialize;
@property(nonatomic) NSDate *stopDate; // @synthesize stopDate=_stopDate;
@property(nonatomic) long long mailboxMessagesBatchSize; // @synthesize mailboxMessagesBatchSize=_mailboxMessagesBatchSize;
@property(nonatomic) long long accountMailboxesBatchSize; // @synthesize accountMailboxesBatchSize=_accountMailboxesBatchSize;
@property(nonatomic) long long lastFetchDateCutoff; // @synthesize lastFetchDateCutoff=_lastFetchDateCutoff;
@property(copy, nonatomic) NSArray *excludedMailboxTypes; // @synthesize excludedMailboxTypes=_excludedMailboxTypes;
@property(readonly, nonatomic) NSObject<OS_os_activity> *loggingActivity; // @synthesize loggingActivity=_loggingActivity;
@property(readonly, nonatomic) id <MFActivityCondition> condition; // @synthesize condition=_condition;
@property(readonly, nonatomic) id <MFDeviceStorage> deviceStorage; // @synthesize deviceStorage=_deviceStorage;
@property(readonly, nonatomic) id <MFAccountsProvider> accountsProvider; // @synthesize accountsProvider=_accountsProvider;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)_mailboxesToDownload;
- (_Bool)_shouldContinueProcessing;
- (void)_runSynchronously;
@property(readonly, nonatomic) MailPersistentStorage *persistentStorage;
- (_Bool)mailboxMessageBodyProcessorShouldContinueProcessing:(id)arg1;
- (void)runWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)runSynchronouslyWithDuration:(long long)arg1;
- (_Bool)runSynchronously;
- (id)initWithName:(id)arg1 accountsProvider:(id)arg2 deviceStorage:(id)arg3 condition:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

