//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMessageContentView, NSString, UIViewController;

@protocol MFMessageContentViewDelegate <NSObject>
- (UIViewController *)presentingViewControllerForMessageContentView:(MFMessageContentView *)arg1;

@optional
- (void)messageContentView:(MFMessageContentView *)arg1 loadingIndicatorDidChangeVisibility:(_Bool)arg2;
- (void)messageContentView:(MFMessageContentView *)arg1 didChangeSelectedHTML:(NSString *)arg2;
- (void)messageContentView:(MFMessageContentView *)arg1 didEndZoomingMessageWithOffset:(struct CGPoint)arg2;
- (void)messageContentViewWillBeginZoomingMessage:(MFMessageContentView *)arg1;
- (void)messageContentViewDidTapRevealActionsButton:(MFMessageContentView *)arg1;
- (void)messageContentView:(MFMessageContentView *)arg1 expandQuoteAtCollapsedOffset:(struct CGPoint)arg2 expandedOffset:(struct CGPoint)arg3;
- (void)messageContentView:(MFMessageContentView *)arg1 didFinishRenderingWithHeight:(double)arg2;
- (void)messageContentViewDidDisplayContent:(MFMessageContentView *)arg1;
- (void)messageContentViewDidFinishFirstPaint:(MFMessageContentView *)arg1;
- (void)messageContentViewDidFinishLoadingMessage:(MFMessageContentView *)arg1;
- (id <MFAttachmentHandlingDelegate>)attachmentHandlingDelegateForMessageContentView:(MFMessageContentView *)arg1;
@end

