//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MailChangeTransaction.h"

@interface MFMoveMessageTransaction : MailChangeTransaction
{
}

- (id)initWithMessages:(id)arg1 specialDestination:(int)arg2;
- (id)initWithMessages:(id)arg1 targetMailbox:(id)arg2;

@end

