//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFTriageInteractionDelegate.h"

@class MFMoveToPredictionTriageInteraction, UIViewController;

@protocol MFMoveToPredictionTriageInteractionDelegate <MFTriageInteractionDelegate>
- (void)presentTransferUIWithMoveInteraction:(MFMoveToPredictionTriageInteraction *)arg1 prediction:(id <MFMailboxPrediction>)arg2 fromViewController:(UIViewController *)arg3;
@end

