//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMoveMessageTriageInteraction.h"

#import "_MFLazyPreviewActionItemDataSource.h"

@class NSArray, NSString, UIViewController;

@interface MFMoveToPredictionTriageInteraction : MFMoveMessageTriageInteraction <_MFLazyPreviewActionItemDataSource>
{
    UIViewController *_transferUIViewController;
    id <MFMailboxPrediction> _prediction;
    NSArray *_previewActions;
    CDUnknownBlockType _previewActionHandler;
}

+ (id)interactionWithMessages:(id)arg1 mall:(id)arg2 predictionContext:(unsigned long long)arg3 existingPrediction:(id)arg4 presentationSource:(id)arg5 delegate:(id)arg6 presentingViewController:(id)arg7;
@property(copy, nonatomic) CDUnknownBlockType previewActionHandler; // @synthesize previewActionHandler=_previewActionHandler;
@property(retain, nonatomic) NSArray *previewActions; // @synthesize previewActions=_previewActions;
@property(retain, nonatomic) id <MFMailboxPrediction> prediction; // @synthesize prediction=_prediction;
@property(retain, nonatomic) UIViewController *transferUIViewController; // @synthesize transferUIViewController=_transferUIViewController;
- (void).cxx_destruct;
- (void)_presentTransferUI;
- (void)_enumeratePredictionActions:(CDUnknownBlockType)arg1;
- (void)_presentFollowUpActionSheetWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)_hasPrediction;
- (CDUnknownBlockType)lazyPreviewActionHandler;
- (id)lazyPreviewActions;
- (id)swipeAction;
- (id)miniSwipeAction;
- (id)previewActionItemForSwipe:(_Bool)arg1;
- (void)performInteractionWithCompletion:(CDUnknownBlockType)arg1;
- (void)_performInteraction_Internal;
- (void)moveToTargetMailbox:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

