//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFNanoServerMessageContentLoaderDelegate.h"
#import "NNMKSyncProviderDelegate.h"

@class MFMailboxUid, MFNanoAccountHandler, MFNanoServerFullMessageLoader, MFNanoServerMessageFetchService, MFNanoServerMessageSender, MFNanoServerMessageUpdater, NNMKSyncProvider, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface MFNanoServer : NSObject <NNMKSyncProviderDelegate, MFNanoServerMessageContentLoaderDelegate>
{
    NSObject<OS_dispatch_queue> *_nanoServerQueue;
    NNMKSyncProvider *_syncProvider;
    NSMutableDictionary *_messageContentLoadersKeyedByMessageId;
    MFNanoServerFullMessageLoader *_fullMessageLoader;
    MFNanoServerMessageUpdater *_messageUpdater;
    MFNanoServerMessageSender *_messageSender;
    MFMailboxUid *_mailboxListeningForNotificationsTo;
    MFNanoAccountHandler *_accountHandler;
    MFNanoServerMessageFetchService *_messageFetchService;
    _Bool _waitingForAutoFetchDone;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_fetchForMailboxes:(id)arg1 growFetchWindow:(_Bool)arg2;
- (id)_filteredMessagesArrayFromLibraryMessages:(id)arg1 syncedMailboxes:(id)arg2;
- (id)_filteredMessagesArrayFromLibraryMessages:(id)arg1 syncedMailbox:(id)arg2;
- (id)_libraryMessagesReceivedBefore:(id)arg1 count:(unsigned long long)arg2 inConversationWithId:(id)arg3 protectedDataAvailable:(_Bool *)arg4 limitDateReceived:(id)arg5 syncedMailboxes:(id)arg6;
- (id)_libraryMessagesReceivedBefore:(id)arg1 count:(unsigned long long)arg2 inConversationWithId:(id)arg3 protectedDataAvailable:(_Bool *)arg4 limitDateReceived:(id)arg5 syncedMailbox:(id)arg6;
- (id)_messageIdsForNanoMessages:(id)arg1;
- (void)_loadFullMesssagesForMessageIds:(id)arg1 messagesAlreadyLoadedByMessageId:(id)arg2 libraryMessagesRetrievalBlock:(CDUnknownBlockType)arg3 callback:(CDUnknownBlockType)arg4;
- (void)_cancelLoadingContentForLibraryMessageId:(id)arg1;
- (void)_loadContentForLibraryMessageId:(id)arg1 highPriority:(_Bool)arg2;
- (void)messageContentLoaderDidFailLoadingContent:(id)arg1;
- (void)messageContentLoaderDidFinishLoading:(id)arg1;
- (void)messageContentLoader:(id)arg1 receivedImageAttachment:(id)arg2 contentId:(id)arg3 loadedProtected:(_Bool)arg4;
- (void)messageContentLoader:(id)arg1 receivedMailContent:(id)arg2 forMessage:(id)arg3 loadedProtected:(_Bool)arg4;
- (void)_handleAutoFetchDone:(id)arg1;
- (void)_messagesCompacted:(id)arg1;
- (void)_conversationFlagsChanged:(id)arg1;
- (void)_messageFlagsChanged:(id)arg1;
- (void)_messagesAdded:(id)arg1;
- (void)syncProvider:(id)arg1 didRequestSendComposedMessage:(id)arg2;
- (void)syncProvider:(id)arg1 didRequestFetchForMailboxes:(id)arg2;
- (void)syncProviderDidRequestFetch:(id)arg1 forConversationId:(id)arg2 mailbox:(id)arg3;
- (void)syncProviderDidRequestStopDownloadingAllMessageElements:(id)arg1;
- (void)syncProvider:(id)arg1 didRequestStopDownloadingMessageElementsForMessageWithId:(id)arg2;
- (void)syncProvider:(id)arg1 didRequestContentForMessageWithId:(id)arg2 highPriority:(_Bool)arg3;
- (void)syncProvider:(id)arg1 didRequestResendAccountWithId:(id)arg2;
- (void)syncProvider:(id)arg1 didRequestMessagesToSendAsFetchResponseForMessageIds:(id)arg2;
- (void)syncProvider:(id)arg1 didRequestResendMessagesWithIds:(id)arg2;
- (void)syncProvider:(id)arg1 didRequestMessagesWithContext:(id)arg2;
- (void)syncProvider:(id)arg1 didRequestFirstMessages:(unsigned long long)arg2 mailboxes:(id)arg3;
- (void)syncProvider:(id)arg1 didUpdateMessagesStatus:(id)arg2;
- (void)syncProvider:(id)arg1 didUpdateMailboxSelection:(id)arg2;
- (void)syncProviderDidRequestAccounts:(id)arg1;
- (id)nanoBulletinFlagsForMessageFromAccount:(id)arg1 mailboxURLString:(id)arg2 status:(unsigned long long)arg3 dateReceived:(id)arg4;
- (id)watchedMailboxes;
- (void)_addObservers;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

