//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@interface MFNanoBridgeSettingsMailbox : NSObject <NSSecureCoding>
{
}

+ (_Bool)supportsSecureCoding;
+ (_Bool)pairedDeviceSupportsMultipleMailboxes;
+ (unsigned long long)sourceTypeForMailboxFilterType:(unsigned long long)arg1;
+ (id)defaultSelectedMailboxes;
- (_Bool)isEqual:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (_Bool)isValid;
- (void)configureCell:(id)arg1;
- (unsigned long long)level;
- (id)icon;
- (id)displayName;
- (unsigned long long)mailboxFilterType;

@end

