//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NNMKSyncProvider, NSArray, NSObject<OS_dispatch_queue>;

@interface MFNanoAccountHandler : NSObject
{
    NSObject<OS_dispatch_queue> *_executionQueue;
    NNMKSyncProvider *_syncProvider;
}

@property(retain, nonatomic) NNMKSyncProvider *syncProvider; // @synthesize syncProvider=_syncProvider;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *executionQueue; // @synthesize executionQueue=_executionQueue;
- (void).cxx_destruct;
- (void)_notifyFavoritesManagerSelectedMailboxesChanged;
- (id)favoriteMailboxUidList;
- (void)_checkIfSettingsChanged;
- (id)_nanoMailboxesFromMailAccount:(id)arg1;
- (id)nanoAccountFromMailAccount:(id)arg1;
- (void)_swipeActionsChanged:(id)arg1;
- (void)_settingsChanged:(id)arg1;
- (void)_accountsChanged:(id)arg1;
- (void)updateBridgeSettingsWithMailboxSelection:(id)arg1;
@property(readonly, nonatomic) NSArray *activeAccounts;
- (id)accountWithId:(id)arg1;
- (void)_addObservers;
- (id)initWithExecutionQueue:(id)arg1 syncProvider:(id)arg2;

@end

