//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MFNanoServerMessageFetchService : NSObject
{
}

- (id)_criterionForFilterType:(unsigned long long)arg1;
- (id)_filterTypeCriterionForMailbox:(id)arg1;
- (id)criterionForMailboxUrl:(id)arg1;
- (id)_criterionForMessagesFromMailbox:(id)arg1 param:(id)arg2;
- (id)_criterionForMessagesFromMailboxes:(id)arg1 param:(id)arg2;
- (id)messagesForMailboxes:(id)arg1 param:(id)arg2;

@end

