//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NPSDomainAccessor, NPSManager, NSArray, NSMutableDictionary, NSString;

@interface MFNanoBridgeSettingsManager : NSObject
{
    NPSManager *_syncManager;
    NPSDomainAccessor *_domainAccessor;
    NSMutableDictionary *_mailboxUidById;
    NSMutableDictionary *_accountByMailboxId;
    NSArray *_activeAccounts;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) NSArray *activeAccounts; // @synthesize activeAccounts=_activeAccounts;
- (id)domainAccessor;
- (id)_loadAccounts;
- (void)_handlePairedDeviceChanged;
- (void)_handleDidUnpair;
- (void)_setValue:(id)arg1 forKey:(id)arg2 syncWithClient:(_Bool)arg3 perGizmo:(_Bool)arg4;
- (void)_setValue:(id)arg1 forKey:(id)arg2 syncWithClient:(_Bool)arg3;
- (id)_getValueForKey:(id)arg1 perGizmo:(_Bool)arg2;
- (id)_getValueForKey:(id)arg1;
- (id)_mobileMailSwipeRightAction;
- (_Bool)_mobileMailOrganizeByThread;
- (_Bool)_mobileMailAskBeforeDeleting;
- (unsigned long long)_mobileMailFlagStyle;
- (void)_setSignature:(id)arg1;
- (void)_setSwipeRightAction:(id)arg1;
- (void)_setOrganizeByThread:(_Bool)arg1;
- (void)_setAskBeforeDeleting:(_Bool)arg1;
- (void)_setFlagStyle:(unsigned long long)arg1;
- (void)_setLinesOfPreview:(unsigned long long)arg1;
- (id)_mailboxSelectionFromPreviousOSVersion;
- (id)_includeMailMailboxesFromDisk;
- (void)_setIncludeMailMailboxes:(id)arg1;
- (id)_signature;
- (id)_swipeRightAction;
- (_Bool)_organizeByThread;
- (_Bool)_askBeforeDeleting;
- (unsigned long long)_flagStyle;
- (unsigned long long)_linesOfPreview;
- (id)_includeMailMailbox;
- (_Bool)_mirrorSettingsFromCompanion;
- (void)reloadCachedAccounts;
- (void)notifyMobileMailAccountsChanged;
- (void)notifyMobileMailSwipeRightActionChanged;
- (void)notifyMobileMailOrganizeByThreadChanged;
- (void)notifyMobileMailAskBeforeDeletingChanged;
- (void)notifyMobileMailFlagStyleChanged;
- (void)notifyMirrorSettingsFromCompanionChanged;
@property(retain, nonatomic) NSString *signature;
@property(retain, nonatomic) NSString *swipeRightAction;
@property(nonatomic) _Bool organizeByThread;
@property(nonatomic) _Bool askBeforeDeleting;
@property(nonatomic) unsigned long long flagStyle;
@property(nonatomic) unsigned long long linesOfPreview;
@property(retain, nonatomic) NSArray *includeMailMailboxes;
- (void)addSharedSettingsToArray:(id)arg1 ifFilterTypes:(unsigned long long)arg2 containsFilter:(unsigned long long)arg3;
- (void)setUpdateMailboxSelection:(id)arg1;
- (id)bridgeSettingsMailboxSelection;
@property(readonly, nonatomic) _Bool mirrorSettingsFromCompanion;
- (void)dealloc;
- (id)init;

@end

