//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFConversationFlagTriageInteraction.h"

@interface MFNotifyTriageInteraction : MFConversationFlagTriageInteraction
{
}

- (id)title;
- (void)_performInteraction_Internal;
- (void)performInteractionWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)isPermitted;
- (_Bool)flagState;

@end

