//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageHeaderViewBlock.h"

@class NSDateFormatter, NSMutableArray, UILayoutGuide, UIStackView, _MFFormEntry;

@interface MFPrintMessageHeaderViewBlock : MFMessageHeaderViewBlock
{
    UILayoutGuide *_firstColumn;
    UIStackView *_secondColumn;
    _MFFormEntry *_from;
    _MFFormEntry *_subject;
    _MFFormEntry *_date;
    _MFFormEntry *_to;
    _MFFormEntry *_cc;
    _MFFormEntry *_bcc;
    NSMutableArray *_entries;
    NSDateFormatter *_dateFormatter;
}

@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) NSMutableArray *entries; // @synthesize entries=_entries;
@property(retain, nonatomic) _MFFormEntry *bcc; // @synthesize bcc=_bcc;
@property(retain, nonatomic) _MFFormEntry *cc; // @synthesize cc=_cc;
@property(retain, nonatomic) _MFFormEntry *to; // @synthesize to=_to;
@property(retain, nonatomic) _MFFormEntry *date; // @synthesize date=_date;
@property(retain, nonatomic) _MFFormEntry *subject; // @synthesize subject=_subject;
@property(retain, nonatomic) _MFFormEntry *from; // @synthesize from=_from;
@property(retain, nonatomic) UIStackView *secondColumn; // @synthesize secondColumn=_secondColumn;
@property(retain, nonatomic) UILayoutGuide *firstColumn; // @synthesize firstColumn=_firstColumn;
- (long long)_textAlignmentForLayoutDirection;
- (id)_attributedStringForAddress:(id)arg1 appendComma:(_Bool)arg2;
- (id)_attributedStringForAddressList:(id)arg1;
- (void)_updateVisibility;
- (void)displayMessage:(id)arg1;
- (void)initializePrimaryLayoutConstraints;
- (void)_createFormEntries;
- (void)createPrimaryViews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

