//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFQueue, NSArray, NSLock;

@interface MFPriorityLoadingQueue : NSObject
{
    NSLock *_lock;
    id <MFScheduler> _scheduler;
    MFQueue *_queue;
    id <MFCancelable> _workItemCancelable;
    CDUnknownBlockType _comparator;
    CDUnknownBlockType _itemHandler;
}

@property(copy, nonatomic) CDUnknownBlockType itemHandler; // @synthesize itemHandler=_itemHandler;
@property(copy, nonatomic) CDUnknownBlockType comparator; // @synthesize comparator=_comparator;
@property(readonly, nonatomic) NSArray *allObjects;
- (id)drain;
- (void)dequeueObject:(id)arg1;
- (id)dequeue;
- (void)enqueue:(id)arg1;
- (void)_noteQueueNeedsProcessing;
- (void)_processQueue;
- (void)immediatelyProcessQueue;
- (void)_locked_cancelWorkItem;
- (void)_locked_reorderQueue;
- (id)initWithScheduler:(id)arg1;
- (void)dealloc;

@end

