//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface MFRoundedCornerCutoutView : UIView
{
    _Bool _pathNeedsUpdate;
    double _dimmingFactor;
    UIColor *_fillColor;
    struct UIEdgeInsets _extensionInsets;
    CDStruct_f4676b61 _radii;
}

+ (Class)layerClass;
@property(nonatomic) CDStruct_f4676b61 radii; // @synthesize radii=_radii;
@property(copy, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property(nonatomic) double dimmingFactor; // @synthesize dimmingFactor=_dimmingFactor;
@property(nonatomic) struct UIEdgeInsets extensionInsets; // @synthesize extensionInsets=_extensionInsets;
- (void).cxx_destruct;
- (id)debugDescription;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_updatePathIfNeeded;
- (void)_setPathNeedsUpdate;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (void)setRadius:(double)arg1 duration:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setRadii:(CDStruct_f4676b61)arg1 duration:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setFillColor:(id)arg1 animated:(_Bool)arg2;
- (id)_shapeLayer;
- (id)initWithFrame:(struct CGRect)arg1;

@end

