//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MFActorItemHeaderView, MFGradientView;

@interface MFSceneView : UIView
{
    _Bool _wantsFalseEdgeShadow;
    MFActorItemHeaderView *_headerView;
    double _shadowRadius;
    double _shadowOpacity;
    unsigned long long _falseShadowEdge;
    double _cornerRadius;
    MFGradientView *_falseEdgeShadowView;
}

+ (double)defaultCornerRadius;
@property(nonatomic) _Bool wantsFalseEdgeShadow; // @synthesize wantsFalseEdgeShadow=_wantsFalseEdgeShadow;
@property(retain, nonatomic) MFGradientView *falseEdgeShadowView; // @synthesize falseEdgeShadowView=_falseEdgeShadowView;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) unsigned long long falseShadowEdge; // @synthesize falseShadowEdge=_falseShadowEdge;
@property(nonatomic) double shadowOpacity; // @synthesize shadowOpacity=_shadowOpacity;
@property(nonatomic) double shadowRadius; // @synthesize shadowRadius=_shadowRadius;
@property(retain, nonatomic) MFActorItemHeaderView *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)uninstallMaskCutoutView;
- (void)installMaskCutoutView:(id)arg1;
- (void)updateCornerRadii;
- (void)_updateShadow;
- (void)_updateShadowPathIfNeededForChangeFromRect:(struct CGRect)arg1 toRect:(struct CGRect)arg2;
- (void)layoutSubviews;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

