//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFSearchSuggester.h"

#import "MessageMiniMallObserver.h"

@class MFMailMessageLibrary, MFSpotlightTopHitsQuery;

@interface MFSearchTopHitsSuggester : MFSearchSuggester <MessageMiniMallObserver>
{
    MFMailMessageLibrary *_messageLibrary;
    MFSpotlightTopHitsQuery *_topHitsQuery;
}

+ (id)suggester;
@property(retain, nonatomic) MFSpotlightTopHitsQuery *topHitsQuery; // @synthesize topHitsQuery=_topHitsQuery;
@property(retain, nonatomic) MFMailMessageLibrary *messageLibrary; // @synthesize messageLibrary=_messageLibrary;
- (void).cxx_destruct;
- (void)miniMallGrowingMailboxesChanged:(id)arg1;
- (void)miniMallCurrentMessageRemoved:(id)arg1;
- (void)miniMallFinishedFetch:(id)arg1;
- (void)miniMallStartFetch:(id)arg1;
- (void)miniMallMessageCountWillChange:(id)arg1;
- (void)miniMallDidLoadMessages:(id)arg1;
- (void)miniMallMessageCountDidChange:(id)arg1;
- (void)miniMallMessagesAtIndexPathsChanged:(id)arg1;
- (void)miniMallDidFinishSearch:(id)arg1;
- (id)_newTopHitsSuggesterMall;
- (id)_topHitsSuggestionsFromMiniMall:(id)arg1 queryResult:(id)arg2;
- (id)_performTopHitsMessageSearchUsingMall:(id)arg1 libraryIdentifiers:(id)arg2;
- (id)_topHitsMessageCriterionForLibraryIdentifiers:(id)arg1;
- (_Bool)_mailboxesAreSufficientlySyncedAndIndexed:(id)arg1 failureReason:(id *)arg2;
- (_Bool)_shouldGenerateTopHitsForPhrase:(id)arg1 scopeMailboxURLs:(id)arg2 outReason:(id *)arg3;
- (id)generateSuggestionsUsingPhraseManager:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)_invokeHandler:(CDUnknownBlockType)arg1 suggestions:(id)arg2 mall:(id)arg3 reason:(id)arg4;
- (id)_topHitsQueryWithPhraseManager:(id)arg1 handler:(CDUnknownBlockType)arg2 progress:(id)arg3;
- (id)categories;
- (id)init;

@end

