//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageCompositionTriageInteraction.h"

@interface MFSendAsEMLTriageInteraction : MFMessageCompositionTriageInteraction
{
    _Bool _forTriageTeam;
}

@property(nonatomic) _Bool forTriageTeam; // @synthesize forTriageTeam=_forTriageTeam;
- (id)icon;
- (id)title;
- (void)_performInteraction_Internal;

@end

