//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFSearchSuggestion.h"

@class MFMailMessage, MessageMiniMall;

@interface MFSearchMessageSuggestion : MFSearchSuggestion
{
    MessageMiniMall *_mall;
    MFMailMessage *_message;
}

@property(readonly, nonatomic) MFMailMessage *message; // @synthesize message=_message;
@property(readonly, nonatomic) MessageMiniMall *mall; // @synthesize mall=_mall;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long rankingIndex;
- (void)userDidInteract;
- (id)description;

@end

