//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MFSearchSuggestionsTableViewModelReuseConfiguration, NSMutableArray, NSMutableDictionary, NSString;

@interface MFSearchSuggestionsTableViewModel : NSObject <NSCopying, UITableViewDataSource, UITableViewDelegate>
{
    CDUnknownBlockType _comparator;
    NSMutableArray *_orderedIdentifiers;
    NSMutableDictionary *_objectsByIdentifier;
    MFSearchSuggestionsTableViewModelReuseConfiguration *_defaultReuseConfiguration;
    NSMutableDictionary *_categoryConfiguration;
}

@property(retain, nonatomic) NSMutableDictionary *categoryConfiguration; // @synthesize categoryConfiguration=_categoryConfiguration;
@property(copy, nonatomic) MFSearchSuggestionsTableViewModelReuseConfiguration *defaultReuseConfiguration; // @synthesize defaultReuseConfiguration=_defaultReuseConfiguration;
@property(retain, nonatomic) NSMutableDictionary *objectsByIdentifier; // @synthesize objectsByIdentifier=_objectsByIdentifier;
@property(retain, nonatomic) NSMutableArray *orderedIdentifiers; // @synthesize orderedIdentifiers=_orderedIdentifiers;
@property(copy, nonatomic) CDUnknownBlockType comparator; // @synthesize comparator=_comparator;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)viewControllerForForPreviewingContext:(id)arg1 indexPath:(id)arg2 view:(id)arg3;
- (id)_reuseConfigurationForSuggestion:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)indexPathForSuggestion:(id)arg1;
- (id)tableViewModelByRemovingItemsAtIndexPaths:(id)arg1;
- (void)registerCategory:(id)arg1 forReuseConfiguration:(id)arg2;
- (void)setSection:(id)arg1 forIdentifier:(id)arg2;
- (id)sectionForIdentifier:(id)arg1;
- (unsigned long long)indexOfIdentifier:(id)arg1;
- (id)identifierAtIndex:(unsigned long long)arg1;
- (id)sectionAtIndex:(unsigned long long)arg1;
- (void)enumerateSections:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) unsigned long long numberOfSections;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSectionComparator:(CDUnknownBlockType)arg1 defaultReuseConfiguration:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

