//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MFSearchSuggestionPhraseManager : NSObject
{
    _Bool _generateCannedSuggestions;
    NSString *_scopeIdentifierForPeopleSuggestions;
    NSString *_phrase;
    NSArray *_selectedSuggestions;
    NSArray *_implicitSuggestions;
    NSString *_keyboardLanguage;
}

+ (id)phraseManagerWithPhrase:(id)arg1 selectedSuggestions:(id)arg2;
@property(copy, nonatomic) NSString *keyboardLanguage; // @synthesize keyboardLanguage=_keyboardLanguage;
@property(copy, nonatomic) NSArray *implicitSuggestions; // @synthesize implicitSuggestions=_implicitSuggestions;
@property(readonly, copy, nonatomic) NSArray *selectedSuggestions; // @synthesize selectedSuggestions=_selectedSuggestions;
@property(readonly, copy, nonatomic) NSString *phrase; // @synthesize phrase=_phrase;
@property(copy, nonatomic) NSString *scopeIdentifierForPeopleSuggestions; // @synthesize scopeIdentifierForPeopleSuggestions=_scopeIdentifierForPeopleSuggestions;
@property(nonatomic) _Bool generateCannedSuggestions; // @synthesize generateCannedSuggestions=_generateCannedSuggestions;
- (void).cxx_destruct;
- (_Bool)hasSuggestionWithCriterion:(id)arg1;
@property(readonly) _Bool hasPhraseOrSuggestions;
@property(readonly) _Bool hasTimePeriodSuggestion;
@property(readonly) _Bool hasMailboxSuggestion;
@property(readonly) _Bool hasSubjectSuggestion;
- (_Bool)hasCategory:(id)arg1 andScope:(id)arg2;
- (id)_implicitAndSelectedSuggestions;
- (id)initWithPhrase:(id)arg1 selectedSuggestions:(id)arg2;
- (id)spotlightQueryStrings;
- (id)_spotlightQueryStringForVIP;
- (id)mailboxURLs;

@end

