//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFSearchSuggestion.h"

@class NSString, UIImage;

@interface MFSearchAtomSuggestion : MFSearchSuggestion
{
}

@property(readonly, nonatomic) UIImage *atomImage;
@property(readonly, nonatomic) UIImage *image;
@property(readonly, copy, nonatomic) NSString *atomTitle;
- (id)criterionWithSelectedScope:(id)arg1;
@property(readonly, nonatomic) NSString *contactIdentifier;
@property(readonly, copy, nonatomic) NSString *subtitle;
@property(readonly, copy, nonatomic) NSString *title;
- (id)description;

@end

