//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFSearchMessageVIPStatusSuggestion.h"

@class UIImage;

@interface MFSearchMessageVIPCannedStatusSuggestion : MFSearchMessageVIPStatusSuggestion
{
    UIImage *_coloredCategoryImage;
}

- (void).cxx_destruct;
- (id)image;
- (id)category;

@end

