//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFSearchAtomSuggestion.h"

@class MFPair, MFSearchHumanTimePeriod, NSDateComponents, NSString;

@interface MFSearchTimePeriodSuggestion : MFSearchAtomSuggestion
{
    MFSearchHumanTimePeriod *_humanTimePeriod;
    NSDateComponents *_dateComponents;
    NSString *_title;
    NSString *_atomTitle;
}

+ (id)_dateComponentsRangeForDateComponents:(id)arg1;
+ (id)_pinnedDateComponentsFromAbstract:(id)arg1;
+ (id)suggestionWithHumanTimePeriod:(id)arg1;
+ (id)suggestionWithAbstractDateComponents:(id)arg1;
+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
- (id)criterion;
@property(readonly, nonatomic) MFPair *dateComponentsRange;
- (id)atomTitle;
- (id)title;
- (id)contactIdentifier;
- (id)subtitle;
- (id)category;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAbstractDateComponents:(id)arg1;
- (id)initWithHumanTimePeriod:(id)arg1;
- (id)initWithPinnedDateComponents:(id)arg1;
- (id)init;

@end

