//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MFAtomTextViewAtomLayout.h"

@class MFSearchAtomSuggestion, NSArray, NSString, UIImageView, UILabel, _MFSearchAtomBackgroundView;

@interface MFSearchAtomView : UIView <MFAtomTextViewAtomLayout>
{
    CDStruct_513ff01d _flags;
    MFSearchAtomSuggestion *_suggestion;
    _MFSearchAtomBackgroundView *_backgroundView;
    UIImageView *_leadingImage;
    UILabel *_textLabel;
    NSArray *_defaultConstraints;
    NSArray *_withImageConstraints;
    NSArray *_withoutImageConstraints;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(copy, nonatomic) NSArray *withoutImageConstraints; // @synthesize withoutImageConstraints=_withoutImageConstraints;
@property(copy, nonatomic) NSArray *withImageConstraints; // @synthesize withImageConstraints=_withImageConstraints;
@property(copy, nonatomic) NSArray *defaultConstraints; // @synthesize defaultConstraints=_defaultConstraints;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIImageView *leadingImage; // @synthesize leadingImage=_leadingImage;
@property(retain, nonatomic) _MFSearchAtomBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) MFSearchAtomSuggestion *suggestion; // @synthesize suggestion=_suggestion;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGRect selectionBounds;
- (void)setSelectionStyle:(long long)arg1 animated:(_Bool)arg2;
@property(nonatomic) long long selectionStyle;
- (void)setEnabled:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=isEnabled) _Bool enabled;
- (id)viewForLastBaselineLayout;
- (void)_updateTextColor;
- (void)_updateImageColor;
- (void)updateConstraints;
- (double)_bottomMargin;
- (double)_topToBaselineDelta;
- (id)_font;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, nonatomic) long long baseWritingDirection;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

