//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "MFSearchSuggestionDelegate.h"
#import "UIViewControllerPreviewingDelegate.h"
#import "UIViewControllerPreviewingDelegate_Private.h"

@class MFSearchSuggestionsTableViewModel, MFSearchSuggestionsTableViewModelReuseConfiguration, NSMutableDictionary, NSMutableSet, NSString, SearchScopeControl;

@interface MFSearchSuggestionsViewController : UITableViewController <MFSearchSuggestionDelegate, UIViewControllerPreviewingDelegate, UIViewControllerPreviewingDelegate_Private>
{
    NSMutableSet *_touchedCategories;
    id <MFSearchSuggestionsViewControllerDelegate> _delegate;
    MFSearchSuggestionsTableViewModel *_tableViewModel;
    SearchScopeControl *_searchGlobalScopeControl;
    id <UIViewControllerPreviewing> _viewControllerPreviewing;
    NSMutableDictionary *_headerViews;
    MFSearchSuggestionsTableViewModelReuseConfiguration *_defaultReuseConfiguration;
    MFSearchSuggestionsTableViewModelReuseConfiguration *_topHitsReuseConfiguration;
}

+ (CDUnknownBlockType)categoryComparator;
@property(retain, nonatomic) MFSearchSuggestionsTableViewModelReuseConfiguration *topHitsReuseConfiguration; // @synthesize topHitsReuseConfiguration=_topHitsReuseConfiguration;
@property(retain, nonatomic) MFSearchSuggestionsTableViewModelReuseConfiguration *defaultReuseConfiguration; // @synthesize defaultReuseConfiguration=_defaultReuseConfiguration;
@property(retain, nonatomic) NSMutableDictionary *headerViews; // @synthesize headerViews=_headerViews;
@property(retain, nonatomic) id <UIViewControllerPreviewing> viewControllerPreviewing; // @synthesize viewControllerPreviewing=_viewControllerPreviewing;
@property(retain, nonatomic) SearchScopeControl *searchGlobalScopeControl; // @synthesize searchGlobalScopeControl=_searchGlobalScopeControl;
@property(retain, nonatomic) MFSearchSuggestionsTableViewModel *tableViewModel; // @synthesize tableViewModel=_tableViewModel;
@property(nonatomic) __weak id <MFSearchSuggestionsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)didRemoveSearchSuggestion:(id)arg1;
- (void)shouldReloadSearchSuggestion:(id)arg1;
- (id)searchSuggestionsForCategory:(id)arg1;
@property(readonly, nonatomic) _Bool hasSuggestions;
- (void)updateSuggestions:(id)arg1 categories:(id)arg2;
- (void)endUpdatingSuggestions;
- (void)beginUpdatingSuggestions;
- (void)clearSuggestions;
- (void)_clearPreviousSuggestions;
- (_Bool)_delegateAllowsCategory:(id)arg1 cachedValues:(id)arg2;
- (id)_newSearchSuggestionsTableViewModel;
- (CDUnknownBlockType)_topHitsTableViewMessagePreviewing;
- (CDUnknownBlockType)_topHitsTableViewRowSelector;
- (CDUnknownBlockType)_topHitsTableViewRowHeightCalculator;
- (CDUnknownBlockType)_topHitsTableViewCellPopulator;
- (CDUnknownBlockType)_defaultTableViewRowSelector;
- (CDUnknownBlockType)_defaultTableViewRowHeightCalculator;
- (CDUnknownBlockType)_defaultTableViewCellPopulator;
- (void)globalSearchScopeChanged:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_updateTableHeaderView;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

