//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFSearchMessageSuggestion.h"

#import "MessageMiniMallObserver.h"

@class MFMailMessage, MFSpotlightTopHitsQueryResult, MessageMiniMall;

@interface MFSearchTopHitsSuggestion : MFSearchMessageSuggestion <MessageMiniMallObserver>
{
    MessageMiniMall *_mall;
    MFMailMessage *_message;
    MFSpotlightTopHitsQueryResult *_queryResult;
}

@property(retain, nonatomic) MFSpotlightTopHitsQueryResult *queryResult; // @synthesize queryResult=_queryResult;
@property(retain, nonatomic) MFMailMessage *message; // @synthesize message=_message;
@property(retain, nonatomic) MessageMiniMall *mall; // @synthesize mall=_mall;
- (void).cxx_destruct;
- (void)miniMallGrowingMailboxesChanged:(id)arg1;
- (void)miniMallCurrentMessageRemoved:(id)arg1;
- (void)miniMallFinishedFetch:(id)arg1;
- (void)miniMallStartFetch:(id)arg1;
- (void)miniMallMessageCountWillChange:(id)arg1;
- (void)miniMallDidLoadMessages:(id)arg1;
- (void)miniMallDidFinishSearch:(id)arg1;
- (void)miniMallMessagesAtIndexPathsChanged:(id)arg1;
- (void)miniMallMessageCountDidChange:(id)arg1;
- (long long)rankingIndex;
- (void)userDidInteract;
- (id)category;
- (id)initWithMall:(id)arg1 message:(id)arg2 queryResult:(id)arg3;

@end

