//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISearchController.h"

@class MFAtomSearchBar;

@interface MFSearchController : UISearchController
{
    MFAtomSearchBar *_searchBar;
}

@property(retain, nonatomic) MFAtomSearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void).cxx_destruct;
- (void)_handleMailNavigationControllerShowViewController:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithSearchResultsController:(id)arg1;

// Remaining properties
@property(nonatomic) __weak id <MFSearchControllerDelegate> delegate; // @dynamic delegate;
@property(nonatomic) __weak id <MFSearchResultsUpdating> searchResultsUpdater; // @dynamic searchResultsUpdater;

@end

