//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFSwipableCollectionViewLayout, NSArray, NSIndexPath;

@protocol MFSwipableCollectionViewLayoutDelegate <NSObject>

@optional
- (void)swipableCollectionViewLayout:(MFSwipableCollectionViewLayout *)arg1 willBeginSwipeAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)swipableCollectionViewLayout:(MFSwipableCollectionViewLayout *)arg1 canEditItemAtIndexPath:(NSIndexPath *)arg2;
- (NSArray *)swipableCollectionViewLayout:(MFSwipableCollectionViewLayout *)arg1 trailingSwipeActionsForItemAtIndexPath:(NSIndexPath *)arg2;
- (NSArray *)swipableCollectionViewLayout:(MFSwipableCollectionViewLayout *)arg1 leadingSwipeActionsForItemAtIndexPath:(NSIndexPath *)arg2;
- (struct CGSize)sizeForItemAtIndexPath:(NSIndexPath *)arg1;
@end

