//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFSwipeAction, NSArray, NSIndexPath, UIScrollView, UIView;

@protocol MFSwipeActionHost <NSObject>
- (void)animateForDestructiveAction:(MFSwipeAction *)arg1 atIndexPath:(NSIndexPath *)arg2 withSwipeInfo:(CDStruct_b06b0113)arg3 completion:(void (^)(_Bool))arg4;
- (NSArray *)trailingSwipeActionsForItemAtIndexPath:(NSIndexPath *)arg1;
- (NSArray *)leadingSwipeActionsForItemAtIndexPath:(NSIndexPath *)arg1;
- (NSIndexPath *)indexPathForTouchLocation:(struct CGPoint)arg1;
- (UIView *)viewForItemAtIndexPath:(NSIndexPath *)arg1;
- (UIScrollView *)itemContainerView;
- (UIView *)gestureRecognizerView;

@optional
- (void)swipeDidEndForItemAtIndexPath:(NSIndexPath *)arg1;
- (void)swipeWillBeginForItemAtIndexPath:(NSIndexPath *)arg1;
- (_Bool)swipeMayBeginForItemAtIndexPath:(NSIndexPath *)arg1;
@end

