//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class MFSwipeActionUIConfigurator, MFSwipeDismissalGestureRecognizer, NSString, UIPanGestureRecognizer, _UIFeedbackStatesBehavior;

@interface MFSwipeHandler : NSObject <UIGestureRecognizerDelegate>
{
    MFSwipeDismissalGestureRecognizer *_dismissalGestureRecognizer;
    UIPanGestureRecognizer *_swipeActionPanRecognizer;
    CDStruct_324b76a9 _currentSwipeConfiguration;
    unsigned long long _currentSwipeState;
    double _initialTranslation;
    double _confirmationTranslationAdjustment;
    _Bool _active;
    MFSwipeActionUIConfigurator *_configurator;
    _UIFeedbackStatesBehavior *_swipeFeedbackBehavior;
}

@property(retain, nonatomic) _UIFeedbackStatesBehavior *swipeFeedbackBehavior; // @synthesize swipeFeedbackBehavior=_swipeFeedbackBehavior;
@property(nonatomic) MFSwipeActionUIConfigurator *configurator; // @synthesize configurator=_configurator;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(readonly, nonatomic) unsigned long long currentSwipeState; // @synthesize currentSwipeState=_currentSwipeState;
- (void)_moveSwipedItemToOffset:(double)arg1 animated:(_Bool)arg2 usingSpringWithStiffness:(double)arg3;
- (CDStruct_b06b0113)_currentSwipeInfoWithTargetOffset:(double)arg1 animated:(_Bool)arg2 usingSpringWithStiffness:(double)arg3;
@property(readonly, nonatomic) CDStruct_324b76a9 currentSwipeConfiguration;
- (void)_clearSwipeInfo;
- (void)cancelSwipe;
- (void)updateSwipeConfiguration:(CDStruct_324b76a9)arg1;
- (void)initiateSwipeWithDirection:(unsigned long long)arg1 location:(struct CGPoint)arg2 userInitiated:(_Bool)arg3;
- (void)_swipeRecognizerEnded:(id)arg1 wasCancelled:(_Bool)arg2;
- (void)_swipeRecognizerChanged:(id)arg1;
- (void)_swipeRecognizerBegan:(id)arg1;
- (void)_swipeRecognizerDidRecognize:(id)arg1;
- (void)_dismissalRecognizerDidRecognize:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)dealloc;
- (void)_setUp;
- (id)initWithSwipeUIConfigurator:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

