//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFConversationViewFlowLayout.h"

#import "MFSwipeActionHost.h"

@class MFSwipeActionUIConfigurator, NSIndexPath, NSString;

@interface MFSwipableCollectionViewLayout : MFConversationViewFlowLayout <MFSwipeActionHost>
{
    double _swipedItemHeight;
    id <MFSwipableCollectionViewLayoutDelegate> _swipeDelegate;
    MFSwipeActionUIConfigurator *_swipeConfigurator;
    NSIndexPath *_deletedIndexPath;
}

@property(copy, nonatomic) NSIndexPath *deletedIndexPath; // @synthesize deletedIndexPath=_deletedIndexPath;
@property(retain, nonatomic) MFSwipeActionUIConfigurator *swipeConfigurator; // @synthesize swipeConfigurator=_swipeConfigurator;
@property(nonatomic) __weak id <MFSwipableCollectionViewLayoutDelegate> swipeDelegate; // @synthesize swipeDelegate=_swipeDelegate;
- (void).cxx_destruct;
- (void)swipeWillBeginForItemAtIndexPath:(id)arg1;
- (void)animateForDestructiveAction:(id)arg1 atIndexPath:(id)arg2 withSwipeInfo:(CDStruct_b06b0113)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setSwipedIndexPath:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)viewForItemAtIndexPath:(id)arg1;
- (id)indexPathForTouchLocation:(struct CGPoint)arg1;
- (id)trailingSwipeActionsForItemAtIndexPath:(id)arg1;
- (id)leadingSwipeActionsForItemAtIndexPath:(id)arg1;
- (id)itemContainerView;
- (id)gestureRecognizerView;
@property(readonly, nonatomic) NSIndexPath *swipedIndexPath;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (void)prepareForTransitionToLayout:(id)arg1;
- (void)prepareForTransitionFromLayout:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

