//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFSwipeAction, MFSwipeActionPullView;

@protocol MFSwipeActionPullViewDelegate <NSObject>
- (double)confirmationDistanceForPrimaryActionInSwipeActionPullView:(MFSwipeActionPullView *)arg1;
- (void)swipeActionPullView:(MFSwipeActionPullView *)arg1 tappedAction:(MFSwipeAction *)arg2;
@end

