//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMailMessage, MFTransferStackViewController, UIView;

@protocol MFTransferStackControllerDelegate <NSObject>
- (MFMailMessage *)currentlySelectedMailMessageForStackViewController:(MFTransferStackViewController *)arg1;
- (UIView *)snapshotViewOfCurrentlySelectedMailMessageForStackViewController:(MFTransferStackViewController *)arg1;
@end

