//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "StackDataSource.h"
#import "StackDelegate.h"

@class CNContactStore, NSMutableDictionary, NSString, StackController, UIColor, UIView, _MFStackContainerView;

@interface MFTransferStackViewController : UIViewController <StackDelegate, StackDataSource>
{
    UIView *_defaultItemSnapshotView;
    id <MFScheduler> _messageLoadScheduler;
    NSMutableDictionary *_loadingContexts;
    NSMutableDictionary *_cancellationTokens;
    CDUnknownBlockType _removeStackedViewsAnimationCompletionBlock;
    StackController *_stackController;
    id <MFTransferStackControllerDelegate> _delegate;
    _MFStackContainerView *_stackContainerView;
    unsigned long long _transferOptions;
    UIColor *_conversationColor;
    CNContactStore *_contactStore;
}

@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(retain, nonatomic) UIColor *conversationColor; // @synthesize conversationColor=_conversationColor;
@property(nonatomic) unsigned long long transferOptions; // @synthesize transferOptions=_transferOptions;
@property(retain, nonatomic) _MFStackContainerView *stackContainerView; // @synthesize stackContainerView=_stackContainerView;
@property(nonatomic) id <MFTransferStackControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) StackController *stackController; // @synthesize stackController=_stackController;
- (void)stackController:(id)arg1 willRemoveViewForItem:(id)arg2;
- (void)stackControllerDidStopStackingViews:(id)arg1;
- (void)stackControllerWillStartStackingViews:(id)arg1;
- (void)stackController:(id)arg1 loadDataForItem:(id)arg2 inView:(id)arg3;
- (_Bool)stackController:(id)arg1 isDataLoadedForItem:(id)arg2 inView:(id)arg3;
- (id)stackController:(id)arg1 viewForItem:(id)arg2;
- (id)defaultItemForStackController:(id)arg1;
- (struct UIEdgeInsets)stackContainerViewEdgeInsetsForStackController:(id)arg1;
- (id)stackContainerViewForStackController:(id)arg1;
- (struct CGRect)_stackItemRect;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)_updateTitleAnimated:(_Bool)arg1;
- (id)_titleForTransferOptions:(unsigned long long)arg1;
- (void)_updateStackController;
- (_Bool)_isStackControllerVisible;
- (void)removeStackedViewsAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)displayStackedViewsForMessages:(id)arg1 animated:(_Bool)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

