//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MFTriageActionUtilities : NSObject
{
}

+ (_Bool)isActionDestructive:(unsigned long long)arg1;
+ (id)defaultColorForTriageAction:(unsigned long long)arg1;
+ (id)actionKeyForTriageAction:(unsigned long long)arg1;
+ (unsigned long long)triageActionForActionKey:(id)arg1;

@end

