//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FavoritesManager, MFMailMessageLibrary, NSObject<OS_dispatch_queue>;

@interface MFUnreadCountHealer : NSObject
{
    MFMailMessageLibrary *_library;
    FavoritesManager *_favoritesManager;
    unsigned long long _state;
    NSObject<OS_dispatch_queue> *_processingQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *processingQueue; // @synthesize processingQueue=_processingQueue;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) FavoritesManager *favoritesManager; // @synthesize favoritesManager=_favoritesManager;
@property(retain, nonatomic) MFMailMessageLibrary *library; // @synthesize library=_library;
- (id)_mailboxes;
- (void)_executeHealing;
- (void)_heal;
- (void)_handleApplicationDidBecomeActiveNotification:(id)arg1;
- (void)_handleAutoFetchDoneNotification:(id)arg1;
- (void)unregisterNotifications;
- (void)registerNotifications;
- (void)dealloc;
- (id)initWithLibrary:(id)arg1 favoritesManager:(id)arg2;

@end

