//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CNContact, NSArray, NSSet;

@protocol MFUserProfileProvider <NSObject>
@property(readonly, copy, nonatomic) NSSet *contactEmailAddresses;
@property(readonly, copy, nonatomic) NSSet *accountsEmailAddresses;
@property(readonly, copy, nonatomic) NSSet *allEmailAddresses;
- (CNContact *)contact;
- (CNContact *)contactWithKeysToFetch:(NSArray *)arg1;
@end

