//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, _MFVelocityIntegratorDataPoint;

@interface MFVelocityIntegrator : NSObject
{
    _MFVelocityIntegratorDataPoint *_initialDataPoint;
    NSMutableArray *_samples;
    struct CGVector _totalTranslation;
}

- (struct CGVector)_computeVelocity;
@property(readonly, nonatomic) struct CGVector offset;
@property(readonly, nonatomic) struct CGVector velocity;
- (void)reset;
- (void)addTouchLocation:(struct CGPoint)arg1;
- (void)dealloc;

@end

