//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView, UIView<MFReclaimable>;

@interface MFViewFreezer : NSObject
{
    _Bool _viewIsFrozen;
    UIView<MFReclaimable> *_freezableView;
    UIView *_freezableViewSnapshot;
    id <MFCancelable> _freezableViewFrameObservation;
}

@property(retain, nonatomic) id <MFCancelable> freezableViewFrameObservation; // @synthesize freezableViewFrameObservation=_freezableViewFrameObservation;
@property(retain, nonatomic) UIView *freezableViewSnapshot; // @synthesize freezableViewSnapshot=_freezableViewSnapshot;
@property(retain, nonatomic) UIView<MFReclaimable> *freezableView; // @synthesize freezableView=_freezableView;
- (void)thawView;
- (void)refreshView;
- (void)freezeView;
- (_Bool)_viewIsFrozen;
- (void)dealloc;
- (id)initWithReclaimableView:(id)arg1;

@end

