//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CNContactViewController, EMVIP;

@interface MFVIPContactMessageInteraction : NSObject
{
    CNContactViewController *_contactViewController;
    EMVIP *_currentVIP;
}

+ (id)vipContactMessageInteractionWithViewController:(id)arg1;
@property(retain, nonatomic) EMVIP *currentVIP; // @synthesize currentVIP=_currentVIP;
@property(nonatomic) __weak CNContactViewController *contactViewController; // @synthesize contactViewController=_contactViewController;
- (void).cxx_destruct;
- (void)_updateVIPContactButtonForViewController:(id)arg1 addVIP:(_Bool)arg2 removePreviousAction:(_Bool)arg3;
- (void)_addVIP:(id)arg1;
- (void)_removeVIP:(id)arg1;
- (void)configureVIPInteractionForMessage:(id)arg1;
- (id)contact;
- (void)dealloc;
- (id)initWithViewController:(id)arg1;

@end

