//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WKNavigationDelegate.h"
#import "WKNavigationDelegatePrivate.h"

@class MFWebViewDictionary, NSString, NSURL, WKWebView, _WKRemoteObjectInterface;

@interface MFWebViewLoadingController : NSObject <WKNavigationDelegate, WKNavigationDelegatePrivate>
{
    _Bool _webProcessPluginNeedsUpdate;
    WKWebView *_webView;
    MFWebViewDictionary *_webViewConstants;
    id <MFMailWebProcessDelegate> _webProcessDelegate;
    _WKRemoteObjectInterface *_remoteObjectInterface;
    NSURL *_loadingURL;
}

@property(nonatomic) _Bool webProcessPluginNeedsUpdate; // @synthesize webProcessPluginNeedsUpdate=_webProcessPluginNeedsUpdate;
@property(retain, nonatomic) NSURL *loadingURL; // @synthesize loadingURL=_loadingURL;
@property(retain, nonatomic) _WKRemoteObjectInterface *remoteObjectInterface; // @synthesize remoteObjectInterface=_remoteObjectInterface;
@property(nonatomic) __weak id <MFMailWebProcessDelegate> webProcessDelegate; // @synthesize webProcessDelegate=_webProcessDelegate;
@property(readonly, retain, nonatomic) MFWebViewDictionary *webViewConstants; // @synthesize webViewConstants=_webViewConstants;
@property(retain, nonatomic) WKWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)webProcessBrowserContextControllerDidBecomeAvailable;
- (void)_reconveneWebProcessBundle;
- (void)requestWebViewLoadWithContext:(id)arg1;
- (void)_doIssueLoadRequestForLoadingURL;
- (void)stopLoading;
- (void)reload;
- (void)slapWebView;
- (void)_registerWebProcessDelegate:(id)arg1;
- (void)_unregisterWebProcessDelegate:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

