//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFQueue, WKProcessPool;

@interface MFWKWebViewFactory : NSObject
{
    MFQueue *_preallocatedWebViews;
    WKProcessPool *_processPool;
}

+ (id)sharedWebViewFactory;
@property(retain, nonatomic) WKProcessPool *processPool; // @synthesize processPool=_processPool;
@property(retain, nonatomic) MFQueue *preallocatedWebViews; // @synthesize preallocatedWebViews=_preallocatedWebViews;
- (id)webView;
- (void)preallocateWebViews;
- (id)_instantiateWebView;
- (void)_didReceiveMemoryWarning:(id)arg1;
- (void)dealloc;
- (id)init;

@end

