//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSXPCService.h"

@class MFXPCClient;

@interface MFXPCServer : MSXPCService
{
    MFXPCClient *_client;
}

+ (id)endpointInfo;
+ (id)exportedInterface;
- (id)remoteObjectProxyWithErrorHandler:(CDUnknownBlockType)arg1;
- (id)newConnectionForInterface:(id)arg1;
- (void)dealloc;
- (id)initWithClient:(id)arg1;
- (id)initWithRemoteObjectInterface:(id)arg1;
- (id)init;

@end

