//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UITraitCollection;

@protocol MSDMessageSnapshotProtocol <NSObject>
- (void)loadMessageFromLibraryID:(NSString *)arg1 size:(struct CGSize)arg2 traitCollection:(UITraitCollection *)arg3 layoutMargins:(struct UIEdgeInsets)arg4 completion:(void (^)(UIImage *, NSError *))arg5;
@end

