//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@protocol MSDStorageProtocol <NSObject>
- (void)reclaimableSpaceWithCompletion:(void (^)(NSNumber *, NSError *))arg1;
- (void)reclaimSpaceOlderThan:(NSDate *)arg1 spaceTarget:(long long)arg2 completion:(void (^)(NSNumber *, NSError *))arg3;
@end

