//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol MSDSuggestMailboxesProtocol <NSObject>
- (void)suggestBest:(unsigned long long)arg1 mailboxesForMessageID:(NSString *)arg2 verbose:(_Bool)arg3 withCompletion:(void (^)(NSArray *, NSString *, NSError *))arg4;
@end

