//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AWDMailError, MSDiagnosticManager;

@protocol MSFetchMetricsControllerDataSource <NSObject>
- (_Bool)didTimeout;
- (_Bool)isForeground;
- (_Bool)shouldReport;
- (unsigned long long)localNonDeletedCount;
- (unsigned long long)numMessagesFetched;
- (unsigned long long)totalBytesReceived;
- (unsigned long long)totalBytesSent;
- (AWDMailError *)mailError;
- (int)newMessagesState;
- (int)mailboxType;
- (int)trigger;
- (int)protocol;
- (int)emailProvider;
- (MSDiagnosticManager *)diagnosticManager;
@end

