//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NNMKComposedMessage, NNMKMailbox, NNMKMailboxSelection, NNMKRequestContext, NNMKSyncProvider, NSArray, NSDictionary, NSString;

@protocol NNMKSyncProviderDelegate <NSObject>
- (void)syncProvider:(NNMKSyncProvider *)arg1 didRequestMessagesWithContext:(NNMKRequestContext *)arg2;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didUpdateMailboxSelection:(NNMKMailboxSelection *)arg2;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didRequestFetchForMailboxes:(NSArray *)arg2;
- (void)syncProviderDidRequestFetch:(NNMKSyncProvider *)arg1 forConversationId:(NSString *)arg2 mailbox:(NNMKMailbox *)arg3;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didRequestSendComposedMessage:(NNMKComposedMessage *)arg2;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didRequestResendAccountWithId:(NSString *)arg2;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didRequestResendMessagesWithIds:(NSArray *)arg2;
- (void)syncProviderDidRequestStopDownloadingAllMessageElements:(NNMKSyncProvider *)arg1;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didRequestStopDownloadingMessageElementsForMessageWithId:(NSString *)arg2;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didRequestContentForMessageWithId:(NSString *)arg2 highPriority:(_Bool)arg3;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didUpdateMessagesStatus:(NSDictionary *)arg2;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didRequestMessagesToSendAsFetchResponseForMessageIds:(NSArray *)arg2;
- (void)syncProvider:(NNMKSyncProvider *)arg1 didRequestFirstMessages:(unsigned long long)arg2 mailboxes:(NSArray *)arg3;
- (void)syncProviderDidRequestAccounts:(NNMKSyncProvider *)arg1;
@end

