//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CriterionSource.h"

@interface NotifyThreadsCriterionSource : CriterionSource
{
}

+ (id)criterionForSource:(id)arg1;
- (void)reloadPreferences;
- (id)noMessagesLabelText;
- (_Bool)shouldIncludeWholeThreads;
- (id)bulletinsContext;
- (id)mailboxName;
- (unsigned long long)type;

@end

