//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@class NSString;

@interface NSDictionary (PPTTestOptions)
@property(readonly, nonatomic) long long mf_testInterfaceOrientation;
@property(readonly, nonatomic) int mf_scrollOffset;
@property(readonly, nonatomic) int mf_maxScrollLength;
@property(readonly, nonatomic) int mf_iterations;
@property(readonly, nonatomic) NSString *mf_mailboxName;
@property(readonly, nonatomic) NSString *mf_testName;
@end

