//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RemoteSearchOperation;

@protocol RemoteSearchOperationDelegate <NSObject>
- (void)remoteSearchOperation:(RemoteSearchOperation *)arg1 didFindResults:(_Bool)arg2;
- (_Bool)remoteSearchOperationShouldStopEarly:(RemoteSearchOperation *)arg1;
@end

