//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSProgress, NSString, SourceSearchContext;

@interface RemoteSearchOperation : NSOperation
{
    id <MiniMallSource> _source;
    SourceSearchContext *_searchContext;
    NSString *_logPrefix;
    NSProgress *_progress;
    id <RemoteSearchOperationDelegate> _delegate;
    CDUnknownBlockType _foundMessages;
    CDUnknownBlockType _stopEarly;
    CDUnknownBlockType _finishedSearchingSource;
}

@property(copy, nonatomic) CDUnknownBlockType finishedSearchingSource; // @synthesize finishedSearchingSource=_finishedSearchingSource;
@property(copy, nonatomic) CDUnknownBlockType stopEarly; // @synthesize stopEarly=_stopEarly;
@property(copy, nonatomic) CDUnknownBlockType foundMessages; // @synthesize foundMessages=_foundMessages;
@property(readonly, nonatomic) __weak id <RemoteSearchOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(readonly, copy, nonatomic) NSString *logPrefix; // @synthesize logPrefix=_logPrefix;
@property(readonly, nonatomic) SourceSearchContext *searchContext; // @synthesize searchContext=_searchContext;
@property(readonly, nonatomic) id <MiniMallSource> source; // @synthesize source=_source;
- (void).cxx_destruct;
- (id)_followUpContextForSearchContext:(id)arg1 searchResult:(id)arg2 totalSearchResultCount:(unsigned long long)arg3;
- (void)_emitFoundMessagesForResult:(id)arg1 totalSearchResultCount:(inout unsigned long long *)arg2;
- (void)main;
- (id)initWithSource:(id)arg1 searchContext:(id)arg2 logPrefix:(id)arg3 progress:(id)arg4 delegate:(id)arg5;

@end

