//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RemoteSearchOperationDelegate.h"

@class MailAccount, NSOperationQueue, NSProgress, NSString, SourceSearchContext;

@interface RemoteSearchCoordinator : NSObject <RemoteSearchOperationDelegate>
{
    _Bool _foundResults;
    _Bool _cancelled;
    CDUnknownBlockType _nextSearchableSource;
    CDUnknownBlockType _foundMessages;
    CDUnknownBlockType _stopEarly;
    CDUnknownBlockType _finishedSearchingSource;
    MailAccount *_account;
    SourceSearchContext *_searchContext;
    NSString *_logPrefix;
    NSProgress *_progress;
    NSOperationQueue *_workQueue;
}

@property(nonatomic) _Bool cancelled; // @synthesize cancelled=_cancelled;
@property _Bool foundResults; // @synthesize foundResults=_foundResults;
@property(readonly, nonatomic) NSOperationQueue *workQueue; // @synthesize workQueue=_workQueue;
@property(readonly, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(readonly, copy, nonatomic) NSString *logPrefix; // @synthesize logPrefix=_logPrefix;
@property(readonly, nonatomic) SourceSearchContext *searchContext; // @synthesize searchContext=_searchContext;
@property(readonly, nonatomic) MailAccount *account; // @synthesize account=_account;
@property(copy, nonatomic) CDUnknownBlockType finishedSearchingSource; // @synthesize finishedSearchingSource=_finishedSearchingSource;
@property(copy, nonatomic) CDUnknownBlockType stopEarly; // @synthesize stopEarly=_stopEarly;
@property(copy, nonatomic) CDUnknownBlockType foundMessages; // @synthesize foundMessages=_foundMessages;
@property(copy, nonatomic) CDUnknownBlockType nextSearchableSource; // @synthesize nextSearchableSource=_nextSearchableSource;
- (void).cxx_destruct;
- (void)_addSearchOperations:(unsigned long long)arg1;
- (void)remoteSearchOperation:(id)arg1 didFindResults:(_Bool)arg2;
- (_Bool)remoteSearchOperationShouldStopEarly:(id)arg1;
- (void)cancel;
- (void)performSearch;
- (id)initWithAccount:(id)arg1 searchContext:(id)arg2 logIdentifier:(id)arg3 progress:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

