//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMailMessageLibrary, NSArray, NSMutableDictionary, NSOperationQueue;

@interface SearchManager : NSObject
{
    MFMailMessageLibrary *_library;
    NSArray *_sources;
    struct os_unfair_lock_s _lock;
    NSMutableDictionary *_searches;
    NSOperationQueue *_workQueue;
    id <SearchManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <SearchManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_finishedSearchOperation:(id)arg1;
- (void)_searchOperation:(id)arg1 foundMessages:(id)arg2 shouldWait:(_Bool)arg3;
- (void)cancelAllSearches;
- (void)cancelSearchWithIdentifier:(id)arg1;
- (id)_addSearchOperation:(id)arg1;
- (id)_sourcesForSearchContext:(id)arg1;
- (void)synchronousLocalSearchUsingContext:(id)arg1 withIdentifier:(id)arg2;
- (id)fullSearchUsingSearchContext:(id)arg1;
- (void)dealloc;
- (id)initWithLibrary:(id)arg1 primarySources:(id)arg2;

@end

