//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"

@class MFMessageCriterion, MFSparseMutable64IndexSet, NSArray, NSDate, NSSet, NSString;

@interface SourceSearchContext : NSObject <NSCopying, NSMutableCopying>
{
    _Bool _shouldSearchAllMail;
    _Bool _shouldSkipLocalSearch;
    _Bool _shouldSkipRemoteSearch;
    _Bool _shouldSuppressErrors;
    NSString *_searchText;
    NSArray *_searchTerms;
    MFMessageCriterion *_criterion;
    CDUnknownBlockType _shouldStopSearching;
    double _timeoutDelay;
    NSSet *_currentMailboxes;
    NSDate *_offset;
}

@property(retain, nonatomic) NSDate *offset; // @synthesize offset=_offset;
@property(copy, nonatomic) NSSet *currentMailboxes; // @synthesize currentMailboxes=_currentMailboxes;
@property(nonatomic) double timeoutDelay; // @synthesize timeoutDelay=_timeoutDelay;
@property(nonatomic) _Bool shouldSuppressErrors; // @synthesize shouldSuppressErrors=_shouldSuppressErrors;
@property(nonatomic) _Bool shouldSkipRemoteSearch; // @synthesize shouldSkipRemoteSearch=_shouldSkipRemoteSearch;
@property(nonatomic) _Bool shouldSkipLocalSearch; // @synthesize shouldSkipLocalSearch=_shouldSkipLocalSearch;
@property(nonatomic) _Bool shouldSearchAllMail; // @synthesize shouldSearchAllMail=_shouldSearchAllMail;
@property(copy, nonatomic) CDUnknownBlockType shouldStopSearching; // @synthesize shouldStopSearching=_shouldStopSearching;
@property(retain, nonatomic) MFMessageCriterion *criterion; // @synthesize criterion=_criterion;
@property(copy, nonatomic) NSArray *searchTerms; // @synthesize searchTerms=_searchTerms;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) MFSparseMutable64IndexSet *referencedConversations;
@property(readonly, copy, nonatomic) NSArray *referencedMailboxes;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

