//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GenericSource.h"

@class NSArray;

@interface StaticSource : GenericSource
{
    NSArray *_messages;
}

- (id)oldestKnownMessage;
- (id)cachedMessageForMessageInfo:(id)arg1;
- (id)messageForMessageInfo:(id)arg1 cacheIfNotAlready:(_Bool)arg2;
- (id)copyMessageInfosMatchingCriterion:(id)arg1;
- (unsigned long long)allMessageCount;
- (unsigned long long)messageCount;
- (id)mailboxUids;
- (id)initWithMessages:(id)arg1;
- (void)dealloc;

@end

