//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (MobileMail)
+ (id)mailVibrantLightColor;
+ (id)mailVibrantDarkColor;
+ (id)mailSortOfNavBarBackgroundColor;
+ (id)mailHighlightedChevronBoxColor;
+ (id)mailExpandedChevronBoxColor;
+ (id)mailChevronBoxColor;
+ (id)mailSelectedCellSystemUltraLightGrayColor;
+ (id)mailSelectedCellSystemLightGrayColor;
+ (id)mailSelectedCellColor;
+ (id)mailSystemUltraLightGrayColor;
+ (id)mailSystemLightGrayColor;
+ (id)mailSiriTransparentLightGrayColor;
+ (id)mailSiriFlaggedColor;
+ (id)mailSiriInteractiveColor;
+ (id)mailAppBackgroundColor;
+ (id)mailMoreButtonGrayColor;
+ (id)mailSubtitleGrayColor;
+ (id)mailDarkGrayColor;
+ (id)mailLightGrayColor;
+ (id)mailTransparentLightGrayColor;
+ (id)mailMoveMessageColor;
+ (id)mailArchiveActionColor;
+ (id)mailDestructiveActionColor;
+ (id)mailFlaggedColor;
+ (id)mailInteractiveColor;
- (_Bool)mf_isTranslucent;
@end

