//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class UISplitViewController, UIViewController;

@protocol UISplitViewControllerDelegatePrivate

@optional
- (_Bool)_splitViewControllerShouldRestoreResponderAfterTraitCollectionTransition:(UISplitViewController *)arg1;
- (_Bool)_splitViewController:(UISplitViewController *)arg1 collapseSecondaryViewController:(UIViewController *)arg2 ontoPrimaryViewController:(UIViewController *)arg3 forRestorationOfCollapsedWhileSuspendedWithPrimaryVisible:(_Bool)arg4;
- (_Bool)_splitViewControllerIsPrimaryVisible:(UISplitViewController *)arg1;
@end

