//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSSet;

@interface UIViewController (MailNavigationController)
- (id)mf_unreadCountForDisplay;
- (id)mf_statusBarSubtitleString;
- (void)mf_updateAlertSuppressionContextsForReason:(id)arg1;
@property(readonly, nonatomic) NSSet *mf_suppressedApplicationContexts;
@property(readonly, nonatomic) NSSet *mf_currentApplicationContexts;
- (void)removedFromMailNavigationController:(id)arg1;
@end

